### ISSUE TITLE
Where can i learn to code a smooth aim / buy one, for mac

### ISSUE THREAD

**Issue by extrenebiibues** [iseekwonderful/csgoGlow#102]
does anyone have one i can get for mac? UC is for pc no one helps u if ur on os x

**Comment by rissc** [comment]
But u can port any PC hack to Mac OS X (as I did ;-) )

**Comment by aKalisch** [comment]
U can port the sources from PC to OS X as I did ;-)

**Comment by MyNameIsLebronJames** [comment]
@aKalisch you say these things but don't tell us how to do it!!! (may I have your OS X hack ;))

**Comment by aKalisch** [comment]
@Acornay 

First: No u don't. Will keep it private.

Second: I needed to learn it myself. If u have a bit of coding knowledge u will do fine recreating stuff from PC Cheats to OSX Cheats. Both system are not to different from each other.

Third: I try to help as much as I can. But I'm not willing to show you every line of C++ code until u've made ur Hack working.

U may should look at UC, download source code and recode the Windows Stuff into OSX Stuff.

My Aimbot source is from this repository: https://github.com/A5-/CSGO-External/tree/master/csgo-extern

Adapting this source to OS X is not that hard ;-) Took me about 2 or 3 hours.

Also look into this internal to get some more understanding of Aimbots: https://github.com/A5-/Gamerfood_CSGO

PS: Internal or External : The math behind is the same ;-)

**Comment by MyNameIsLebronJames** [comment]
@aKalisch okay thank you! I'll try to see what I can do this week. ;D

**Comment by iPredictable** [comment]
@Acornay tell me what happens. I'll help u out

**Comment by MyNameIsLebronJames** [comment]
@PredictEr do you have Skype? i have a question on how to do this
