### ISSUE TITLE
Toggle Issue..

### ISSUE THREAD

**Issue by Eggsdee** [iseekwonderful/csgoGlow#107]
Can someone please specify how to literally toggle the hacks..
Step by step thanks :)

I might be doing it wrong or it doesn't work at all.

**Comment by aKalisch** [comment]
@Eggsdee Look carefully at this commit c2c6f59662171495b8044aa7cd843840229bbc52 and you will have the answer.

Hint: Look the inserted comment on top of the file ;-)

**Comment by aKalisch** [comment]
Oooops made a mistake at the comment. Will fix!

**Comment by aKalisch** [comment]
@Eggsdee Fixed in commit 4226e4a

**Comment by Eggsdee** [comment]
Hey man!! Thank you :)
