### ISSUE TITLE
How To Use Source Code?

### ISSUE THREAD

**Issue by xxShrekxx** [iseekwonderful/csgoGlow#109]
Hi, if anyone could help. How do you use source codes? Im trying to use @aKalisch Bhop script, I've been watching videos and looking at threads about C++ and coding for hours but I still don't know how. If anyone would help I would love you. 
Thanks

**Comment by aKalisch** [comment]
What the fuck? I closed the other issue to not spam the Issue function and you still open a new one.
This Issue tracker is for this repository and its code. And not for Code from other places.
Please respect that and search for other places (Hint: www.unknowncheats.me) where you can ask those questions.

Will close/delete every ISSUE that is related to that.
Thank you!
