### ISSUE TITLE
Toggle?

### ISSUE THREAD

**Issue by FlyingPotato69** [iseekwonderful/csgoGlow#112]
Toggle still isnt working for me, dunno if anyone else has the same issue, also if we edit the code toggle button to like v on its own is that possible or does it have to be a multi button press?

EDIT: In terminal it says that it is being toggled on and off however on screen it never toggles off

**Comment by aKalisch** [comment]
I've tested it and it works for me. If you want toggle it with just `V` you need to remove the `if` statement `if (ctr && alt) { .. }` at line 226 ;-)

**Comment by FlyingPotato69** [comment]
All sorted now I changed the button to just v, thanks

**Comment by extrenebiibues** [comment]
it doesnt work

**Comment by MyNameIsLebronJames** [comment]
@extrenebiibues maybe instead of "it doesnt work". Explain what doesn't, why doesn't it, what happens, why it happens, if your gonna say that, no one's gonna answer.

**Comment by aKalisch** [comment]
When I've tested it, it works.
Remember: The Hotkey is now `CTRL` + `ALT` + `V`

**Comment by extrenebiibues** [comment]
@Acornay i dont need to over complicate it, it doesn't work and he can see what could be the problem in this tiny thread

**Comment by aKalisch** [comment]
It works definitly. Remember the Hotkey ;-)

**Comment by FlyingPotato69** [comment]
@aKalisch since the new update I cant seem to find the line of code that I need to edit to allow the toggle to be 'v' on its own, could you point me to it please?

**Comment by aKalisch** [comment]
@FlyingPotato69 

File: Wall/utils/keyboard.h
Line: 164

**Comment by FlyingPotato69** [comment]
@aKalisch Thanks!
