### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Alanpxc** [iseekwonderful/csgoGlow#115]
Hello, csgo just updated, they renew their random code, can i ask where can i find that code?

**Comment by Alanpxc** [comment]
Can someone help?

**Comment by DooubleO** [comment]
Use the pattern scanner found here: github.com/gabsens/Pattern-scanner-for-OSX
Video By Gabens on how to use it: https://www.youtube.com/watch?v=aP99mdDzwQk

**Comment by Alanpxc** [comment]
Thank you... but it still hard..

**Comment by DooubleO** [comment]
If that is too hard for you, even with a tutorial then this hack isnt for you.

**Comment by Alanpxc** [comment]
well, i understand, thank you

**Comment by AdsL1221** [comment]
uint64_t glowInfoOffset = 0x59e9c10;
uint64_t LocalPlayerBase = 0x51da2e8;
uint64_t playerBase = 0x5156bf8;

uint64_t m_iGlowIndex = 0xAC10;

**Comment by aKalisch** [comment]
Fixed!
