### ISSUE TITLE
My in-game menu won't work anymore

### ISSUE THREAD

**Issue by bertrand2012** [iseekwonderful/csgoGlow#119]
After I downloaded these cheats my shift tab doesn't allow me to open my in-game menu. Can anyone relate to this or give me a solution? (This could be a coincidence that the in-game menu stopped working at the same time as i downloaded this cheat)

**Comment by sacredgeo** [comment]
They have nothing to do with each other. You can set this up yourself. Go to preferences -> In Game. Change it to something other than shift + tab, so you can see the score while walking. I use Alt + / which allows me to quickly do it with one hand.
