### ISSUE TITLE
after the upate

### ISSUE THREAD

**Issue by deezysleazy** [iseekwonderful/csgoGlow#121]
so i tried using this after the update and it seems it has stopped working

**Comment by bertrand2012** [comment]
Redownload it because all of the offsets have changed

**Comment by deezysleazy** [comment]
yeah man i tried to, still

**Comment by DooubleO** [comment]
If you redownloaded it, make sure you remember to change it to 'Run with root' again.

**Comment by sacredgeo** [comment]
Use the pattern scanner to find the offsets yourself. It's still working.
