### ISSUE TITLE
RCS for mac

### ISSUE THREAD

**Issue by bertrand2012** [iseekwonderful/csgoGlow#123]
Anyone willing to share with me a rcs cheat for osx? I've been looking everywhere for one of these and just can't find one.

**Comment by extrenebiibues** [comment]
why the fuck are people begging for this. An aimbot would be nice but why do you need RCS? YOU KNOW WHERE EVERYONE ON THE MAP IS GO LEARN IT OR SOMETHING WTF RECOIL CONTROL IS NOT HARD
