### ISSUE TITLE
Is this a normal problem?

### ISSUE THREAD

**Issue by bertrand2012** [iseekwonderful/csgoGlow#124]
Whenever i start the cheat and use it everything on my computer is fine but a while afterwards random stuff would happen such as my computer hold ing down shift, command etc without me actually pressing anything. Normal?

**Comment by DooubleO** [comment]
Happens to me also, just restart the hack and you should be good to go.

**Comment by iseekwonderful** [comment]
yeah, but I find it difficult to debug this issue, just restart hack or re-enter the game
