### ISSUE TITLE
FACEIT Walls?

### ISSUE THREAD

**Issue by markwu-sde** [iseekwonderful/csgoGlow#126]
Just played my first game of FACEIT and it seems like I can only see the glow of players when there are no wall between us.

**Comment by gabsens** [comment]
this is normal, Faceit sends limited information regarding other players (compared to a classic MM server)

**Comment by FlyingPotato69** [comment]
You can see them through some walls but its more distance effected than on mm so youll only be able to see people that are semi close

**Comment by iseekwonderful** [comment]
So they have a much better PVS system?

**Comment by iseekwonderful** [comment]
And do not use this in Faceit, 5E and B5

**Comment by gabsens** [comment]
@iseekwonderful Faceit anticheat is a fork of Sourcemod anticheat.

The latter has some anti-wallhack feature with custom PVS https://bitbucket.org/anticheat/smac/wiki/Wallhack

**Comment by FlyingPotato69** [comment]
Ive used it for 28 games on faceit and no ban or nothing

**Comment by gabsens** [comment]
@FlyingPotato69 yes, this wallhack specifically won't trigger an automatic ban from Faceit (since their anticheat is server-sided). Nevertheless, perfect bhop or perfect trigger and other such robotic hacks will.

**Comment by joejoepojoe** [comment]
@FlyingPotato69 @gabsens  i used it for 3 games and got banned in my 3rd game? i wasnt using anything othe than this and wasnt just straightup looking through walls

**Comment by MyNameIsLebronJames** [comment]
@joejoepojoe well, you definitely didn't get vac banned. 3 games? in a row? cause people can report you to overwatch

**Comment by joejoepojoe** [comment]
@Acornay nope, my steam is here: http://steamcommunity.com/id/d2dreamer1/

**Comment by Moeinich** [comment]
@joejoepojoe Pretty stupid linking that here..

**Comment by joejoepojoe** [comment]
@Shadiezz I dont care much tbh, i admit i hack in chat everygame i play on it - i dont use it for actual playing
