### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by AdsL1221** [iseekwonderful/csgoGlow#128]
I would pay a donation for this wall with aimbot, anyone is encouraged to realize my dream, attentive to your comments...

**Comment by AdsL1221** [comment]
some interested?

**Comment by BlackCrab** [comment]
Hmu if you get anything, Willing to pay 50$ for a smooth aimbot

**Comment by gabsens** [comment]
Github is not a marketplace. If you want to trade, go to https://hackforums.net/index.php
