### ISSUE TITLE
update new offsets

### ISSUE THREAD

**Issue by tkriews** [iseekwonderful/csgoGlow#130]
New update has been released does anyone know the new updated offsets?

**Comment by columbusblue34** [comment]
i have no idea how to get the offsets so i am no help

**Comment by DooubleO** [comment]
Do some digging before posting an issue. Really its not an issue but laziness.
But.
Use this.
https://github.com/gabsens/Pattern-scanner-for-OSX

**Comment by ggothreau** [comment]
```
uint64_t glowInfoOffset = 0x59ec010;
uint64_t LocalPlayerBase = 0x51dc6e8;
uint64_t playerBase = 0x5158fe8;
```

**Comment by AdsL1221** [comment]
dont work inferno, why?

**Comment by columbusblue34** [comment]
it dose work just played it
