### ISSUE TITLE
Any way of changing toggle button?

### ISSUE THREAD

**Issue by Eggsdee** [iseekwonderful/csgoGlow#132]
Thanks.

**Comment by FlyingPotato69** [comment]
If you want toggle it with just V you need to remove the if statement if (ctr && alt) { .. } at line 226

**Comment by bertrand2012** [comment]
Or you just press ctrl, alt and V

**Comment by acer2245** [comment]
Just start messing around with the code and see what you can find. 

{
        if (keycode == keyCodeForKeyString("v")) {
            states = !states;
            printf("State Changed! %s\n", states ? "ON" : "OFF");
        }

I think this is it though.
