### ISSUE TITLE
When Are you guys going to Put up aimbots? 

### ISSUE THREAD

**Issue by GAMESTAND** [iseekwonderful/csgoGlow#135]

**Comment by columbusblue34** [comment]
there is no fov aimbots for mac that are external if you want one you half to code it youre self

**Comment by columbusblue34** [comment]
@aKalisch  @iseekwonderful  please close this

**Comment by GAMESTAND** [comment]
Why can't you put up aimbots?

**Comment by GAMESTAND** [comment]
do u guys know how to do it?

**Comment by columbusblue34** [comment]
please stop posting this there is no aimbot on osx

**Comment by columbusblue34** [comment]
and if there are you have to pay for it

**Comment by aKalisch** [comment]
@GAMESTAND We dont put an Aimbot to it because there are some kids that steal this work and let other ppl pay for it.
