### ISSUE TITLE
I hate people who sell these hacks

### ISSUE THREAD

**Issue by bertrand2012** [iseekwonderful/csgoGlow#136]
Ok. So from what I am hearing, it is that we cannot be given an aimbot or rage bot or whatever because there are stupid people on the internet who will take this and sell it. I mean there has already been someone who is selling this hack and this infuriates me in the sense that these people are letting all of us down. Now I don't know if this would work but if you were to maybe give this in the exec form then maybe it would work? I really don't know and this is only a suggestion but this seriously sucks because I've just wanted something simple like a RCS or a bunnyhop script but these people are letting us down. Anyway just wanted to share my thoughts.

**Comment by DooubleO** [comment]
Isnt a place to share thoughts. Go to a forum for that.

**Comment by gazababon123** [comment]
eh.. its a glowhack, there is no aimbot or shit in here.. i kno.. i know.. im also sad, but just enjoy the hack, if u want that you have to pay there is no way to get those scripts free, because mac is kinda... idk

**Comment by bertrand2012** [comment]
@gazababon123 know any websites?

**Comment by zisirawu** [comment]
@acer2245 looks like the one on ... has triggerbot, not sure about aimbot tho... ~~maybe the paid version has aimbot too~~

Edit: paid version is the same as free trial, no aimbot, just triggerbot right now :(

**Comment by gabsens** [comment]
Github is not a marketplace nor an advertising forum. If you want to trade or to find information about trade, go elsewhere.

If you want an aimbot or some other features so badly, **buy** yourself some **motivation**, learn C++ and  get information by browsing [Unknowncheats](https://www.unknowncheats.me/forum/counterstrike-global-offensive/) instead of getting scammed by other people.

If you're not willing to invest some time and energy, you can keep whining and let others make money off your laziness.

**Comment by aKalisch** [comment]
@gabsens is right.
If u put some effort and time into coding you can simply create ur own aimbot.
All basics you need are in this repository. For all other informations you can watch tutorials on youtube or browse www.unknowncheats.me .

I did the same and have now a custom hack with legit aimbot and other stuff.

**Comment by aKalisch** [comment]
You need some Netvars for an Aimbot:
- m_vecOrigin (Position on map)
- m_angRotation (The view angels)
- m_vecViewOffset (Eye Position)
- (optional) BoneMatrix for other Bones than head
- CClientState + SetViewAngles (for setting view angles)

To find the SetViewAngles you need todo the following. Read LocalPlayer + m_angRotation as float. Then Search for this value. Move ur Mouse, pick the value of m_angRotation and search again for the value in Bit Slicer. Repeat this Step until the results not decreasing.

For finding the function now freeze (right-click -> Freeze Value) the Results one by one. Go Ingame and move ur mouse. If ur mouse is snapping back you got the right address for it. Byte Array search for the Pointer (watch https://www.youtube.com/watch?v=3HhD7WNzSno to find out how to byte array search).

When you have the SetViewAngles you have all you need to auto-aim until ur math is correct.
