### ISSUE TITLE
When there is a new update how can i fix it myself? 

### ISSUE THREAD

**Issue by GAMESTAND** [iseekwonderful/csgoGlow#137]

**Comment by swayamz** [comment]
Look at the issue called "CSGO Structs/Offsetts" Scroll to the bottom and you can find a good samaritan posted the new offsets 5 minutes ago

**Comment by DooubleO** [comment]
To fix it yourself you need to go to https://github.com/gabsens/Pattern-scanner-for-OSX
Then watch the tutorial.

**Comment by GAMESTAND** [comment]
bro thank you life saver

**Comment by DooubleO** [comment]
Np

**Comment by DooubleO** [comment]
Thankfully you wanted to find out how to fix it yourself, not to be lazy and just ask and wait for someone to do it for you

**Comment by GAMESTAND** [comment]
Np

**Comment by GAMESTAND** [comment]
I tried but it doesn't work

**Comment by DooubleO** [comment]
Did you follow the steps correctly? If so it should work

**Comment by DooubleO** [comment]
You can try this tutorial also. 
https://www.youtube.com/watch?v=3kMyiZ5yuvE

**Comment by swayamz** [comment]
Play on use promo code for free dollar

**Comment by GAMESTAND** [comment]
Yo got it thank you

**Comment by aKalisch** [comment]
I've implemented pattern scanning directly to my hack. I don't need to Update my Offsets when there is an update for CS:GO. 

I'll maybe contact @gabsens for implementing some of his pattern scanner to csgoGlow.
