### ISSUE TITLE
Glow loop and updated spam terminal.

### ISSUE THREAD

**Issue by Yakultie** [iseekwonderful/csgoGlow#14]
Congratulations on your project's opening, but...

I tried sudo -s, I "cd" to directory, I run "./External" still no work.
I open CS:GO before hack inject, still not work. 

The pid is 1624
Version: 14, 290 images at offset 0x2003400
[Gaben:] I tell U /Users/Bern/Library/Application Support/Steam/steamapps/common/Counter-Strike Global Offensive/bin/engine.dylib
, address is 0x63b4000 
[Gaben:] I tell U /Users/Bern/Library/Application Support/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/bin/client.dylib
, address is 0x21800000 
glow loop address is 0x0----------updated----------

WTF. I don't even...

**Comment by iseekwonderful** [comment]
It seem is that u using this app before enter a game, due to the glow class instance may not inited so we cant get glow loop address
try open this when u in a game

**Comment by Yakultie** [comment]
Thank you so much!

I cannot express my gratitude in words.
