### ISSUE TITLE
New Offsets

### ISSUE THREAD

**Issue by rawrchad** [iseekwonderful/csgoGlow#142]
uint64_t glowInfoOffset     = 0x59ebf90;
uint64_t LocalPlayerBase    = 0x51dc668;
uint64_t playerBase         = 0x5158f68;

**Comment by ghost** [comment]
What do these do/how do you apply this?

**Comment by sacredgeo** [comment]
@benehret Read the readme file. Watch the youtube video.

**Comment by joejoepojoe** [comment]
@benehret open XCode, then go the the 'Wall' directory - and then click on main.cpp - in here you should see 3 lines very similar to the ones shown above just with a few differences, this is found close to the top and if you set them to these the walls should work fine.
