### ISSUE TITLE
Hack doset works now

### ISSUE THREAD

**Issue by pcpaul1** [iseekwonderful/csgoGlow#143]
Hello, the new hack from 14.10 doesn't work since today ;(

what is the Problem?

Best Regards

**Comment by rawrchad** [comment]
uint64_t glowInfoOffset     = 0x59ebf90;
uint64_t LocalPlayerBase    = 0x51dc668;
uint64_t playerBase         = 0x5158f68;

**Comment by ghost** [comment]
How do you apply this code?

**Comment by pcpaul1** [comment]
now ;D

**Comment by Alanpxc** [comment]
![2016-10-18 9 04 07](https://cloud.githubusercontent.com/assets/22509854/19478795/e53fb7f8-9511-11e6-90c4-1bdc0d70d945.png)
