### ISSUE TITLE
Color Change When Behind Walls

### ISSUE THREAD

**Issue by iPredictable** [iseekwonderful/csgoGlow#145]
Is it possible if the color would change when its behind walls, and when the player is in the open? Like other premium hacks have the option that makes the players color change when they're peaking

**Comment by extrenebiibues** [comment]
[https://github.com/iseekwonderful/csgoGlow/issues/129](Already made a issue about it)

**Comment by gabsens** [comment]
you need vischeck for that, not easy

**Comment by extrenebiibues** [comment]
@gabsens where can i learn c++ for os x? Not like learning shit from UC where they tell u how to code 2 letters but like a proper tutorial. How did you learn?

**Comment by NexieCSGO** [comment]
@extrenebiibues 
c++ runs on anything if coded correctly, if you need to learn the basics try a course on edx.

**Comment by extrenebiibues** [comment]
@NexieCSGO i remember @aKalisch saying something about turning an aimbot from github into a working one for os x so im just wondering what he meant

**Comment by sacredgeo** [comment]
@extrenebiibues I believe the main difference is the CSGO offsets for PC and Mac are different.

**Comment by sacredgeo** [comment]
Sometimes it's hard to tell when someone is behind a wall or box. Especially in dark areas. I found that if I decreased the glow effect I could more easily distinguish visible players. Look for this line:

```
    Color color = {float((100 - health) / 100.0), float((health) / 100.0), 0.0f, 0.8f};
    applyGlowEffect(task, startAddress, glowIndex, color);
```

Change the 0.8f to something lower like 0.5f.

**Comment by iPredictable** [comment]
@sacredgeo u make os x hacks too?

**Comment by sacredgeo** [comment]
@PredictEr No but I like playing with the code. I know some basics of programming.

**Comment by gazababon123** [comment]
@PredictEr please accept my skype request friend

**Comment by veb** [comment]
I wonder if we can utilise this to change colours @sacredgeo  https://www.unknowncheats.me/forum/counterstrike-global-offensive/139310-spottedbymask-netvaaaaarrrrr.html
