### ISSUE TITLE
Team Shows

### ISSUE THREAD

**Issue by Noriaela** [iseekwonderful/csgoGlow#147]
Is it possible to show ur team in the walls

**Comment by sacredgeo** [comment]
Yes. You'll see a section in the code that says:

```
    if (playerTeamNum == iTeamNum || playerTeamNum == 0) {
        continue;
    }
    if (playerTeamNum == 0) {
        continue;
    }
```

Change it to:

```
    if (playerTeamNum == iTeamNum) {
        Color color {(0 / 255), (255 / 255), (255 / 255), 0.5f};
        applyGlowEffect(task, startAddress, glowIndex, color);
        continue;
    }
    if (playerTeamNum == 0) {
        continue;
    }
```

This will make your team a light blue color. The interesting thing about showing your team is that you can see them through the entire map. I guess the server sends limited data on enemy players.

**Comment by Noriaela** [comment]
Thank you!

**Comment by sacredgeo** [comment]
Changing it to this will have them start at light blue and the glow will change to purple as they lose health. 

 Color color = {float((100 - health) / 200.0), float((health) / 100.0), (255 / 255), 0.5f};
