### ISSUE TITLE
Support Français & informations

### ISSUE THREAD

**Issue by Switcherz** [iseekwonderful/csgoGlow#152]
Bonjour,
Tout d'abord merci pour le boulot à toute l'équipe c'est fantastique. Je voudrais savoir si vous aviez un support Français, j'ai vue que Gabsens était français.

Je voulais savoir si il y avait une app premium pour garantir ce wall hack ?

Merci pour vos réponses,
Et bon boulot !

**Comment by PredictEr** [comment]
Fuck off mate.

**Comment by acer2245** [comment]
@PredictEr Chill out brother

**Comment by Noriaela** [comment]
Qu'entendez-vous par la prime?

**Comment by sacredgeo** [comment]
@PredictEr What's the problem? If you use google translate you can see his message was very friendly.

**Comment by sonicrules11** [comment]
Yeah thats what I was using to translate it :D

**Comment by PredictEr** [comment]
@sacredgeo @sonicrules11 @acer2245 Its all banter, Im joking

**Comment by aKalisch** [comment]
There is no premium app for this. This is open source and 100% free.

**Comment by PredictEr** [comment]
@aKalisch Sorry im not sorry, fuck off nerd.

**Comment by aKalisch** [comment]
In the future you want help?

Not from me anymore.
Bye kid ;-)
