### ISSUE TITLE
Counter Strike Source

### ISSUE THREAD

**Issue by Noriaela** [iseekwonderful/csgoGlow#153]
Does anyone know if there is a way to port this to CS:S by any chance?

**Comment by gabsens** [comment]
The engine is almost exactly the same, there should be very little difference...

**Comment by extrenebiibues** [comment]
dont cheat on such an old game man its just sad

**Comment by aKalisch** [comment]
Due to the fact CS:Source is 32 Bit you need to compile it in 32 Bit. Also you need to port all 64 Bit stuff (uint64 addresses) to 32 bit. 
I also think that glow is working different in CS Source (does it have glow?).
