### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by GreyWolf25** [iseekwonderful/csgoGlow#154]
Can anyone upload the new offsets much appreciated assuming csgo updated today there is a new offset?

**Comment by columbusblue34** [comment]
hold on wait for me to find them

**Comment by GreyWolf25** [comment]
cheers @columbusblue34

**Comment by columbusblue34** [comment]
yep

**Comment by GreyWolf25** [comment]
soo any luck? @columbusblue34

**Comment by qitongsun** [comment]
Gotta love communism and the people in this place

**Comment by columbusblue34** [comment]
uint64_t glowInfoOffset     = 0x59ed160;
uint64_t LocalPlayerBase    = 0x51dd828;
uint64_t playerBase         = 0x515a128;

**Comment by columbusblue34** [comment]
there you goo

**Comment by columbusblue34** [comment]
@GreyWolf25

**Comment by qitongsun** [comment]
does anyone know how to change the offsets by ourselves

**Comment by GreyWolf25** [comment]
THANK U @columbusblue34

**Comment by Switcherz** [comment]
Hello, it's safe to play with the new update or we must wait update ? Thanks for u jobs teams !

**Comment by MyNameIsLebronJames** [comment]
@Switcherz it's safe as long as you don't get overwatched? xD

**Comment by columbusblue34** [comment]
@Switcherz just update the code then it will be safe just dont be obvious

**Comment by Switcherz** [comment]
@Acornay Nop i'm not overwatched :p And VAC is not sea this code open in my OSX ?

@columbusblue34 Ok thanks i  download a code, it's was updated ? I have no see them

Thanks u my friends, you have not à link for dotation for u works ?

**Comment by columbusblue34** [comment]
hold on

**Comment by columbusblue34** [comment]
ill make a file for you

**Comment by Switcherz** [comment]
OK thanks, he'll get what's different?

**Comment by columbusblue34** [comment]
yes ill send it to you

**Comment by columbusblue34** [comment]
[csgoGlow-master.zip](https://github.com/iseekwonderful/csgoGlow/files/552095/csgoGlow-master.zip)
download this and do what you would for the other ones

**Comment by Switcherz** [comment]
Ok thank lot, and is update off Glow ? What is the difference with that on the post?

**Comment by Switcherz** [comment]
Ok thanks i see the difference, it's a code you have say later in this post. Thanks for update. You have links for give you $, ill like your job for this hack :)

**Comment by qitongsun** [comment]
clombus ur a life saver

**Comment by qitongsun** [comment]
columbus the file.zip isnt opening

**Comment by Switcherz** [comment]
Yes @columbusblue34 u are life saver !!
@qitongsun is good for me, i have open it

**Comment by columbusblue34** [comment]
it should m8
@Switcherz you could send me cs skins lol

**Comment by qitongsun** [comment]
its strange

**Comment by columbusblue34** [comment]
what is???

**Comment by columbusblue34** [comment]
hold on im fixing it

**Comment by Switcherz** [comment]
@columbusblue34 I don't have good skins to change but  i can buy one for u with pleasure ;) Can u give me id in private ?

**Comment by columbusblue34** [comment]
yes

**Comment by columbusblue34** [comment]
@Switcherz just add me

**Comment by Switcherz** [comment]
@columbusblue34 who ? Give me id, i can just fallow u here

**Comment by columbusblue34** [comment]
okay fallow and send me a message

**Comment by columbusblue34** [comment]
or just add me here

**Comment by columbusblue34** [comment]
http://steamcommunity.com/profiles/76561198336127474/

**Comment by Switcherz** [comment]
I can't send u a message on GitHub ...

**Comment by columbusblue34** [comment]
add me i sent the link

**Comment by MyNameIsLebronJames** [comment]
@Switcherz do you have Skype?

**Comment by columbusblue34** [comment]
@Acornay hes french

**Comment by MyNameIsLebronJames** [comment]
@Switcherz As-tu Skype? J'ai quelque chose qui va vous faire super heureux!

**Comment by Switcherz** [comment]
@Acornay Yes you can add me
