### ISSUE TITLE
I've implemented no-flash

### ISSUE THREAD

**Issue by sacredgeo** [iseekwonderful/csgoGlow#155]
If this is inappropriate for github please remove it.

I've added a no-flash. Here's the code. You just need to find the flash offset. I did it with Bit Slicer in about 20 minutes.

```
int flashed;
Utils::ReadMemAndDeAllocate(csgo, current_task(), playerAddress + 0x????, &flashed);

if(flashed > 0.0f){
    WriteMem(csgo, playerAddress + 0x????, 0.0f);
}
```

This was much easier than I expected. I'm trying to play with the code so it doesn't completely remove the flash, but just reduces it. No luck so far. 

Also, does anyone know if this method is VAC detectable? Thanks.

**Comment by veb** [comment]
what was the offset that you found? I'll give this a try.

**Comment by iPredictable** [comment]
@sacredgeo you're really helping out this simple glow hack bro. Thanks a lot

**Comment by sacredgeo** [comment]
@PredictEr The hack was already amazing. I'm just adding small tweaks. 

@veb 0xABE4

I've been reading on unknown cheats about some offsets called flashAlpha (m_flFlashMaxAlpha) and flashDuration (m_flFlashDuration). I'm not sure if the offset I've found is one of those. If you find flashAlpha you can specify the transparency, which seems like the best option.

**Comment by veb** [comment]
Perfect! Works well.

**Comment by sacredgeo** [comment]
@veb Awesome. Are you good with Bit Slicer? Can you help me find the m_flFlashMaxAlpha offset? Complete no-flash isn't ideal because sometimes you won't even know if you were flashed. Overwatch will catch that. I really want it reduced by like 75%.

I read that m_flFlashMaxAlpha and m_flFlashDuration are 4 bytes apart, and found from the Local Player offset. I've found 0xABE4, 0xABE8, and 0xABEC all change when you're flashed, including a few other addresses nearby.

**Comment by ggothreau** [comment]
You can change the float value to something like 0.5f

i.e.
`WriteMem(csgo, playerAddress + 0x????, 0.5f);`

**Comment by sacredgeo** [comment]
@ggothreau That's the first thing I tried. It didn't work.

I have one idea that might do it. Testing now.

**Comment by bertrand2012** [comment]
@sacredgeo why not add it onto the one you made?

**Comment by ggothreau** [comment]
@sacredgeo Yeah, I just tested it. It will show the initial flash but not the screen overlay. It's likely a linear function that controls the screen overlay based on the initial flash (which I suspect is offset 0xABE4). There is likely another offset that controls the flash overlay, which is what we want.

**Comment by sacredgeo** [comment]
@acer2245 It seems the creators didn't intend to release this with extra features so I'm honoring that. Feel free to add it yourself.

**Comment by bertrand2012** [comment]
@sacredgeo Honestly that is fair enough i do see alot of people on here begging for cheats and all that so i do feel sorry for them

**Comment by sacredgeo** [comment]
@ggothreau 

I found it. From reading on UnknownCheats, I found that apparently m_flFlashMaxAlpha has a range of 0 - 255. And we know it's near the Local Player in memory.

In Bit Slicer I tried searching for all integers with a value of 255. Returned ~850,000. None near Local Player. No luck. So I tried looking for floats of 255. Only one was near my local player. The offset is 0xABF4, only 0x10 away from the previous value I found. I changed the value to 100 and froze it (40% flash). It worked!

m_flFlashMaxAlpha gets set to 255 the first time you get flashed on a map. If the map changes, it will get set to 255 again. It doesn't need to be done every time you're flashed. I'm using a 20% overlay and it works nicely.

Change your int to a float, read the memory as a float, and you're good. I did a simple if statement to alter it.

```
if(MaxFlashAlpha == 255){
    WriteMem(task, playerAddress + 0xABF4, 51.0f);
}
```

**Comment by sacredgeo** [comment]
I've noticed that m_flFlashMaxAlpha + 0x1C = m_iGlowIndex. I checked older offsets and it seems to be constant. Now we can find them easier if they're updated.

**Comment by veb** [comment]
@sacredgeo GitHub is all about collaboration and such, each change you do you should push it to your forked repo. They won't mind, otherwise it wouldn't have been open sourced. :)

**Comment by aKalisch** [comment]
Get Hopper Dissambler and you never use Bit Slicer to find offsets ;-)

**Comment by aKalisch** [comment]
@sacredgeo 
It makes no sense if you check for flashmaxalpha to be 255.

Why don't you just check if flashmaxalpha is bigger than your "reduced flash alpha" ... makes more sense (remember what if flashmaxalpha is not 255 but u are still blind)

**Comment by sacredgeo** [comment]
@aKalisch 
Does flashmaxalpha change? I watched it in memory and it just stayed at 255.

**Comment by sacredgeo** [comment]
@aKalisch 
I've downloaded Hopper Disassembler. Not really sure where to go from here. I tried "Read Executable to Disassemble" and opened csgo_osx64. I've read that in Olly Dbg you can search for a string like "m_iHealth", but it's not returning any results here. Can you point me in the right direction. Thanks.

**Comment by aKalisch** [comment]
Opening csgo executeable will not work. 
Go by this way: Read executable to dissamble, open client.dylib, wait for hopper to dissamble the file. On the left change to the Strings Tab. Search for m_iHealth. Click on it. Then there are some XREF entries behind the found string (like sub_123456+123). Click on the 123. Then you just need to look the next line (sometimes the second next line). 

Picked the m_iHealth because you already know the value for it. So it might be easier to understand where you have to look for the offset.

**Comment by sacredgeo** [comment]
Ok that worked! It returned this:

     0000000000b861dc    db    "m_iHealth", 0    ; XREF=sub_361690+197, sub_5888b0+525, sub_5e2300+900

I'll keep working on it tomorrow. Going to sleep for now. Thanks again.

**Comment by sacredgeo** [comment]
Ok it worked. It returned a few XREF entries:  XREF=sub_361690+197, sub_5888b0+525, sub_5e2300+900. 

Clicking +197 shows:

```
 0000000000361755         lea       rsi, qword [ds:0xb861dc]                   
 000000000036175c         mov      edx, 0x134                                  
 0000000000361761         mov      ecx, 0x4                                    
```

I see the 0x134 and know LocalPlayer + 0x134 is my health. Is there a way to find the LocalPlayer from Hopper? (Currently 0x51dd828)

Thanks again. I really appreciate the help.

Edit: I just used this to find m_flFlashMaxAlpha. It took me hours in Bit Slicer, and 5 seconds in Hopper. I love it!

For fun I found m_fFlags =  0x138 and m_vecVelocity = 0x148, 0x14C, and 0x150. I'm assuming that's X, Y and Z. Maybe I'll try to add your bunnyhop.

**Comment by aKalisch** [comment]
The find the localplayer offset you just need to implement pattern scanning. There is no way to find the localPlayer Pointer like that. But u can use Hopper to find the signature for it.

But why you don't just use @gabsens pattern scanner?

**Comment by sacredgeo** [comment]
@akalisch I use the pattern scanner after updates. I'm just trying to learn more.

**Comment by aKalisch** [comment]
yeah, but you could implement a pattern scanner into your hack... so you never update pointer offsets again ;-)

**Comment by sacredgeo** [comment]
That's a great idea. I'll try it sometime this week. I'd have to directly copy gabsen's code though. This stuff is rather complex xD

**Comment by aKalisch** [comment]
If I find some time I'll implement pattern scanning to it. Will be a complete rollover of the old code as i also implement a better memory class and some other usefull stuff to it.

**Comment by sacredgeo** [comment]
Sounds great! Looking forward to it. 

I was looking into adding a radar hack. There's an offset m_bSpotted involved. Apparently you just set it to "1" for each entity and they'll appear on radar. I'll be working on that.

**Comment by aKalisch** [comment]
It will not work since Valve patched Far-ESP (Glow) The Player is only visible until he gets dormant. Then he disappears from radar.

Updated the Hack and added auto updating Pointers to localPlayer, Entitylist and GlowManager

**Comment by sacredgeo** [comment]
Wow the new code looks great. Very organized. I'll try it out later. Gonna add the top enemy player glow and no flash back into it. Would you like my code for that? You could probably do it yourself in 5 minutes,  but I figured I should offer.

**Comment by sacredgeo** [comment]
I just realized I already have the code in the csglow I forked to my account. I'm so busy at work I can't concentrate @_@

**Comment by bertrand2012** [comment]
@sacredgeo Have you added no flash to your forked account?

**Comment by aKalisch** [comment]
@sacredgeo 

> For fun I found m_fFlags = 0x138 and m_vecVelocity = 0x148, 0x14C, and 0x150. I'm assuming
> that's X, Y and Z. Maybe I'll try to add your bunnyhop.

Maybe you get an Vector3 class to just read 0x148 as Vector3 reads the following floats with it.

For example like this:

`Vector3 velocity = mem->read<Vector3>(base + m_vecVelocity);`

As result you can output every float as `velocity.x, velocity.y, velocity.z`

**Comment by sacredgeo** [comment]
I couldn't get vectors to work, but this is how I did it.

```
float velocity[3];
for(int i = 0; i < 3; i++){
    velocity[i] = mem->read<float>(playerAddress + 0x148 + 0x4 * i);
}
```

Basically the same thing I think.

**Comment by aKalisch** [comment]
@sacredgeo basically yes... but you read 3 times from memory.

Pick my vector3 class at https://gist.github.com/aKalisch/d57734c10ed23d68ac82961c36f8ce6d
and implement it. Then you should be able to read a Vector in one call.

**Comment by sacredgeo** [comment]
Okay I'll give it a shot. Thanks!

So now that I've got noflash and bunnyhop, I'm thinking what else can I try to implement. What do you think about aimbot, triggerbot, or nospread? They all seem rather complicated.

**Comment by aKalisch** [comment]
Nospread has been patched by Valve. No way to get that working. 

There are 2 Types of Triggerbot.
1. Crosshair Triggerbot (easy) 
2. Hitbox Triggerbot with Ray Tracing and visibility checks (hard for a novice) 

An Aimbot is not that hard as you might think. It's just tons of math ;-) 
Did it on my own with some other aimbot sources for Windows. What can I say. It's still overwatch undetected.

**Comment by sacredgeo** [comment]
My last trigonometry class was in 2007. I'll see what I can do :D

**Comment by GAMESTAND** [comment]
ok how the fuck do u add amibot

**Comment by sacredgeo** [comment]
You find the enemy location, then use trigonometry to find the correct angle to aim at them.

There's more to it than that, obviously. But that's the basic idea. In game everything is represented in 3 dimensions (x, y, and z), but your screen is 2-dimensional, so you need to take that into account. Here's a good explanation: https://www.unknowncheats.me/forum/counterstrike-global-offensive/137492-math-behind-hack-1-coding-better-aimbot-stop-using-calcangle.html

I'm kind of learning as I go. So far I'm able to get the enemy locations and my location from memory. Working on the rest...

**Comment by sacredgeo** [comment]
Here's what I've got so far. These are all float values.

```
 my angles
 local player + 0x160 = x
 local player + 0x164 = y

 my position 
 local player + 0x16C = x
 local player + 0x170 = y
 local player + 0x174 = z
```

Enemy position is the same offsets from entity list (we call it playerBase in this cheat).

Edit:  "local player + 0x174 = z" seems to be the location (height) of my feet. 

I had to add m_vecViewOffset located at 0x144 to correct for this. Now it refers to where my view is. This takes into  account crouching. 

So it's basically: z= float(local player + 0x174) + float(local player + 0x144)

I assume the same concept will be the location of the enemy's head.

**Comment by bertrand2012** [comment]
@sacredgeo Are you planning on sharing these?

**Comment by sacredgeo** [comment]
@acer2245 

If I can get it working I'll tell you exactly how to do it. You should check out that tutorial on unknowncheats I posted.

**Comment by gazababon123** [comment]
@sacredgeo what is your unknowncheat username?

**Comment by sacredgeo** [comment]
@gazababon123 I don't post there. I just read.

**Comment by gazababon123** [comment]
@sacredgeo oooo, kk. But eh is there anyway i can know the program u use to make the code work in game, i tried bit slicer, but i dont really get how to use it XD

sorry, yes fyi i am a stupid :(

**Comment by gazababon123** [comment]
@aKalisch eh, how do you use the vector thing?, idgi can you teach me sometime. if you dont want i also dont mind

**Comment by sacredgeo** [comment]
@gazababon123 

I'm using Bit Slicer and Hopper Disassembler to find the offsets. I'm using XCode to write the code. I'm using tutorials on UnknownCheats to help me.

**Comment by gazababon123** [comment]
@sacredgeo what is the code for the bhop? may i know the one that i can just type in my xcode?

**Comment by columbusblue34** [comment]
@gazababon123 if you are wanting a bhop script its not that hard to find a source code for it

**Comment by gazababon123** [comment]
@columbusblue34 so what am i suppose to search?, im new to coding. sorry if im making your life hard

**Comment by columbusblue34** [comment]
how to code a bhop script or source code for bhop on xcode

**Comment by sacredgeo** [comment]
@gazababon123 

aKalisch has a bunnyhop source code here: https://github.com/aKalisch/source-bunnyhop

It took  me a few hours to implement. I'm a terrible coder. Someone more experienced could probably do it in 10 minutes.

**Comment by columbusblue34** [comment]
@sacredgeo why dont you just upload the code that is implemented that you coded to your own github

**Comment by sacredgeo** [comment]
@columbusblue34 

I'm not going to do that. aKalisch has the source code for all to use. If he wanted people to just copy and paste it, he'd have uploaded it in the complete form.

**Comment by gazababon123** [comment]
@sacredgeo i tried that, but do i paste that code into the main.cpp or i make another code and build it?

**Comment by sacredgeo** [comment]
@gazababon123 

You can make a new .cpp file or take the functions out and stick them in your main.cpp like I did.

**Comment by gazababon123** [comment]
@sacredgeo so i copy it, and paste it in the glowhack main.cpp?
sorry i feel bad now :v

**Comment by sacredgeo** [comment]
@gazababon123 

You can have it in bunnyhop.cpp or stick the functions in main.cpp. Either will work. Do you have any coding experience? I spent 4 years learning many different programming languages when I was a teenager. I've forgotten a lot of it, but I rely on that limited experience to help me with these CSGO cheats.

**Comment by gazababon123** [comment]
@sacredgeo welp sorry to say.
no :(

**Comment by gazababon123** [comment]
![screen shot 2016-10-29 at 10 19 03 am](https://cloud.githubusercontent.com/assets/22512969/19826885/23cf3388-9dc1-11e6-8295-130c35c1ae8e.png)
 weird, it says cannt detect.

**Comment by gazababon123** [comment]
you know why?

**Comment by sacredgeo** [comment]
@gazababon123 

It's really going to be difficult for you then. I'm sorry. 

Vector3 is a class aKalisch linked above. https://gist.github.com/aKalisch/d57734c10ed23d68ac82961c36f8ce6d

Where it says LocalPlayer it's referring to a location in memory. You'll need to read the memory to get that data. The offsets are m_fFlags and m_vecVelocity. There is code in the csgoGlow cheat you can use as an example for how to read the memory.

My advice is to study the csgoGlow code and try to understand how it works. Then you can adapt it to your own needs.

**Comment by gazababon123** [comment]
@sacredgeo what memory?

**Comment by sacredgeo** [comment]
@gazababon123 

https://en.wikipedia.org/wiki/Random-access_memory

http://www.webopedia.com/TERM/R/RAM.html

```
RAM (pronounced ramm) is an acronym for random access memory, 
a type of computer memory that can be accessed randomly; that is, 
any byte of memory can be accessed without touching the preceding 
bytes. RAM is the most common type of memory found in computers 
and other devices, such as printers.
```

It's where CS:GO stores information such as your health, your position, etc.

**Comment by gazababon123** [comment]
@sacredgeo https://www.youtube.com/watch?v=Uv5tJXA04zU this is a tutorial for it?
gabsens make it

**Comment by sacredgeo** [comment]
@gazababon123 That's a good tutorial. You need to download Bit Slicer first. The video will show you how to find the current LocalPlayer offset. From there you can find a lot of information about your player in CS:GO such as health and team number. LocalPlayer is needed for these cheats to work, including the bunnyhop. aKalisch updated the cheat recently to automatically find the offset, but it's still good to know how to find it.

**Comment by gazababon123** [comment]
@sacredgeo hmm.... so do i need to find the health code? which part needs to be filled by me, by looking at the local player base?

**Comment by sacredgeo** [comment]
@gazababon123 Did you watch the video?

**Comment by gazababon123** [comment]
@sacredgeo yes

**Comment by sacredgeo** [comment]
@gazababon123 I don't understand your question.

**Comment by gazababon123** [comment]
@sacredgeo hmm so.
you said the problem with localplayer not detected is that, its a memory that i need to look at
but im not sure i know what is missing.

**Comment by sacredgeo** [comment]
@gazababon123 

For example, in the code it says "localPlayer.iHealth" but that doesn't really refer to anything. You need to add the code to read that portion of memory. Same for localPlayer.iFlags, velo.x, and velo.y.

These offsets are called m_iHealth, m_fFlags, and m_vecVelocity.

If you study the csgoGlow code and also read the posts on this github you will have all the information you need. 

It took me hours and hours to get it working. Even with 4 years coding experience. These are difficult topics. Study the code. Use google. Read the posts on  this github.

**Comment by gazababon123** [comment]
@sacredgeo 1 last question
![screen shot 2016-10-29 at 10 52 51 am](https://cloud.githubusercontent.com/assets/22512969/19827026/db96a948-9dc5-11e6-94b8-07475e42e2bb.png) is the localplayer.ihealth >= 1

is the "1" the value that i have to change?, just like the oterhs

**Comment by gazababon123** [comment]
@sacredgeo can you explain me how to get the automated way, you say aKalisch update the cheat

**Comment by sacredgeo** [comment]
Download the cheat again. aKalisch updated it the code to automatically get the offsets.
 https://github.com/iseekwonderful/csgoGlow

**Comment by gazababon123** [comment]
@sacredgeo i know how to use the glowhack, and how to update its offset, im just so damn confused about the bhop. 

the glowhack is not hard to use, i use gabsen's pattern scanner 

but idk how to find the offset of my m_fFlags

**Comment by gazababon123** [comment]
i am talking about the bhop not the glowhack

**Comment by sacredgeo** [comment]
aKalisch already explained it above. Read his posts.

**Comment by bertrand2012** [comment]
@sacredgeo Hey bro just one question. I'm looking to learn c++ but im worried that i might spend hours upon hours learning it about windows but i have a mac so could or might be usless. My question is, what are the differences between c++ on OS X and Windows?

**Comment by ggothreau** [comment]
There is (essentially) no difference in the language between platforms. The difference will be the operating system's API's you'd be using (for example loading dynamic libraries and reading / writing memory for a process). C++ itself is a language that is independent of any operating system.

**Comment by bertrand2012** [comment]
@ggothreau So it'll be alright if i learn c++ on windows?

**Comment by ggothreau** [comment]
Yeah, you can learn the basics on Windows and then learn the API necessary for macOS when you're ready.

**Comment by aKalisch** [comment]
For all who want an aimbot: https://github.com/A5-/CSGO-External

This is the base I used for my Aimbot. With some effort and some time everybody can implement that.

**Comment by sacredgeo** [comment]
@aKalisch 

Wow thanks. That's impressive. I'll try to implement it tomorrow. I've been working on my aimbot for about 6 hours... I've got it working somewhat, but it's total trash. I planned to add your vector3 class once I got it working better. Also, I think I've mixed up an x and y somewhere in there I need to fix.

```
void aim(){
    //read vecorigin
    float myAngle[2];
    for(int i = 0; i < 2; i++){
        myAngle[i] = mem->read<float>(playerAddress + 0x160 + 0x4 * i);
    }

    //read my position
    float myPos[3];
    for(int i = 0; i < 3; i++){
        myPos[i] = mem->read<float>(playerAddress + 0x16C + 0x4 * i);
    }

    //add distance from ground to eyes
    myPos[2] += mem->read<float>(playerAddress + 0x144);

    float angles[3];

    //calc distance to enemy
    double delta[3] = { (myPos[0]-ePos[0]), (myPos[1]-ePos[1]), (myPos[2]-ePos[2]) };
    double hyp = sqrt(delta[0]*delta[0] + delta[1]*delta[1]);

    // calc pitch and yaw to look at enemy
    angles[0] = (float) (asinf(delta[2]/hyp) * 57.295779513082f);
    angles[1] = (float) (atanf(delta[1]/delta[0]) * 57.295779513082f);
    angles[2] = 0.0f;

    if(delta[0] >= 0.0){
        angles[1] += 180.0f;
    }

    if(angles[1] > 180){
        angles[1] -= 360;
    }

    //get the current mouse position
    CGEventRef ourEvent = CGEventCreate(NULL);
    CGPoint point = CGEventGetLocation(ourEvent);
    float currentX = (float)point.x;
    float currentY = (float)point.y;
    CFRelease(ourEvent);

    //check if the enemy is witin 20 degrees of xhair
    //if within 1 degree stop aiming
    if(
       fabs(myAngle[0] - angles[0]) > 0.5 &&
       fabs(myAngle[1] - angles[1]) > 0.5 &&
       fabs(myAngle[0] - angles[0]) < 20 &&
       fabs(myAngle[1] - angles[1]) < 20
   ){             
        //move mouse y
        CGEventRef moveMouse;
        if(myAngle[1] > angles[1]){
            moveMouse = CGEventCreateMouseEvent(NULL, kCGEventMouseMoved, CGPointMake(currentX, currentY - 2), kCGMouseButtonLeft );
        }else if(myAngle[1] < angles[1]){
            moveMouse = CGEventCreateMouseEvent(NULL, kCGEventMouseMoved, CGPointMake(currentX, currentY + 2), kCGMouseButtonLeft );
        }
        CGEventPost(kCGHIDEventTap, moveMouse);

        //move mouse x
        if(myAngle[0] > angles[0]){
            moveMouse = CGEventCreateMouseEvent(NULL, kCGEventMouseMoved, CGPointMake(currentX + 2, currentY), kCGMouseButtonLeft );
        }else if(myAngle[0] < angles[0]){
            moveMouse = CGEventCreateMouseEvent(NULL, kCGEventMouseMoved, CGPointMake(currentX - 2, currentY), kCGMouseButtonLeft );   
        }
        CGEventPost(kCGHIDEventTap, moveMouse);
        CFRelease(moveMouse);
    }  
}
```

**Comment by ggothreau** [comment]
Did you get `CGEventCreateMouseEvent` to work? I've always found it difficult to work with.

**Comment by sacredgeo** [comment]
@ggothreau Yes I did and that part took me about an hour by itself. What a pain...

**Comment by ggothreau** [comment]
@sacredgeo Good progress. Keep up the good work!

**Comment by sacredgeo** [comment]
@ggothreau Thanks! If I get it working correctly I'll let you know. Then I'll probably delete it and add aKalish's. He's probably gonna laugh at my terrible code haha!

**Comment by aKalisch** [comment]
@sacredgeo are u planning to aim by mouseevent? Why don't write to viewangles in CS:GO? Then you don't need any WorldToScreen method.

Look my Wiki Entry at https://github.com/iseekwonderful/csgoGlow/wiki/Guides----Get-SetViewAngle-memory-address to obtain the writeable viewangles memory address.

**Comment by sacredgeo** [comment]
That seems like a better option. I'll play around with it and see how it works.

**Comment by veb** [comment]
This doesn't work on 64bit though, does it?

**Comment by veb** [comment]
When you find the XREF for say, m_iHealth, what's the next step? I can't seem to find 0x134 as per your example @aKalisch 

![image](https://cloud.githubusercontent.com/assets/376245/19833005/46d7f1ac-9e8f-11e6-8df5-1c35c12ffa87.png)

**Comment by sacredgeo** [comment]
@veb did you click on the first set of numbers with a plus sign? Mine had 3. I'll see if I can help you later tonight. 

I've been at work all day, but I've been handwriting code for a smooth aim based on the viewangles. The y axis was easy enough, but the X axis was tricky due to the range going from +/- 0-180. I'll get to test it later!

**Comment by veb** [comment]
I did this:
-  Searched for String `m_iHealth`
- Found 
  ![image](https://cloud.githubusercontent.com/assets/376245/19833166/f96da6a4-9e94-11e6-8583-80a0536da493.png)
- Clicked `+297`
- Found 
  ![image](https://cloud.githubusercontent.com/assets/376245/19833169/090e52c0-9e95-11e6-872d-dfa857ce0db4.png)

I'm not sure what to do next!

**Comment by sacredgeo** [comment]
@veb 

I have:

    0000000000b88fe2   db   "m_iHealth", 0   ; XREF=sub_363b50+197, sub_58b3d0+525, sub_5e4e20+900

Clicking +197 shows me:

    lea        rsi, qword [ds:0xb88fe2]       ; "m_iHealth", argument #2 for method sub_2bb870
    mov      edx, 0x134                              ; argument #3 for method sub_2bb870
    mov      ecx, 0x4                                  ; argument #4 for method sub_2bb870
    xor        r8d, r8d                                  ; argument #5 for method sub_2bb870
    xor        r9d, r9d                                  ; argument #6 for method sub_2bb870
    call       sub_2bb870

**Comment by sacredgeo** [comment]
@veb Here's my screen:

![screen shot 2016-10-29 at 8 06 59 pm](https://cloud.githubusercontent.com/assets/22250686/19833564/61fc1d5e-9e13-11e6-9184-b4e2f42b6a03.png)

![screen shot 2016-10-29 at 8 07 35 pm](https://cloud.githubusercontent.com/assets/22250686/19833566/64b1fb7c-9e13-11e6-9224-36af9fd0128d.png)

**Comment by veb** [comment]
@sacredgeo could you give me the complete steps as to what you do? :)

**Comment by sacredgeo** [comment]
@veb 

Open Hopper. Go to File -> Read executable to disassemble. Open client.dylib. A window will pop up. I used the default settings which are shown here:

![screen shot 2016-10-29 at 8 12 02 pm](https://cloud.githubusercontent.com/assets/22250686/19833579/fde3d392-9e13-11e6-8b2e-0ee1280e39fd.png)

Wait for it to process. You'll see little colored bars filling the top area of the screen. On the left select strings and type "m_iHealth". Click the result below that says "m_iHealth". It will locate the netvar. Click on the XREF section. You'll see something like " XREF=sub_363b50+197, sub_58b3d0+525, sub_5e4e20+900"

Click the +197 and it takes you to the next screen. You should see something like this:

![screen shot 2016-10-29 at 8 07 35 pm](https://cloud.githubusercontent.com/assets/22250686/19833588/655d96fc-9e14-11e6-97ea-ab3c2d1aa283.png)

Hopefully you see a 0x134 somewhere in there.

**Comment by veb** [comment]
haha... that was easy @sacredgeo I went "shit, am I actually opening the _RIGHT_ client.dylib?". I wasn't.

For anyone else, the path is `/Users/<username>/Library/Application Support/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/bin/osx64/client.dylib`

**Comment by veb** [comment]
@sacredgeo did you end up finding the flag for the flash in Hopper as well? What did you look for?

**Comment by sacredgeo** [comment]
@veb Good! I'm glad you got it. I had a feeling you had that step wrong! I went and checked the other dylibs in the same folder (server.dylib, etc) for m_iHealth just in case there was a mix-up. Were you looking at client.dylib for another game like TF2?

Well... remember the netvar was called "m_flFlashMaxAlpha" so why don't you tell me ;-)

**Comment by veb** [comment]
👍  yeah, I totally forgot that.

I looked at m_fFlashDuration instead:

```
    if(flashed) {
        mem->write<float>(playerAddress + 0xABF8, 0);
    }
```

(ignore my float)

**Comment by sacredgeo** [comment]
So m_fFlashDuration refers to how long the flash lasts, and m_flFlashMaxAlpha refers to how transparent / opaque your screen gets when flashed. You can change either to zero to have no flash. My method was to turn m_flFlashMaxAlpha to a lower number (range = 0 - 255), so I still get flashed, but it's minimal and I can still see everything. You can react like you're flashed so overwatch / spectators won't notice.

**Comment by veb** [comment]
Yep. Bunny Hop, Glow, No Flash... what's next to add? I did want no recoil, but @aKalisch said Valve had fixed that, it seems!

**Comment by sacredgeo** [comment]
I'm not an expert, but I believe recoil and spread are related yet different concepts. I've seen threads about RCS (recoil control system). I haven't read enough to know if that means nospread. Too bad they fixed that :[

I've been thinking about what to add. I'd like either a triggerbot or aimbot. I'm currently working on an aimbot. It's hard as ever... I'm making progress though. Vis checks seem like an impossible task. I'm gonna get this basic aimbot working then worry about that later.

How's your bunnyhop? I'm getting velocities of 290 easily. Sometimes 300+

**Comment by extrenebiibues** [comment]
@sacredgeo are you going for a legit one or for a rage one? There are already rage ones on the internet so i suggest going for a smooth one that goes for head bone

**Comment by sacredgeo** [comment]
@extrenebiibues Hoping to make it look legit. We'll see.

**Comment by bertrand2012** [comment]
@sacredgeo Thank you so much I absolutely love watching you guys talk about this stuff it makes me want to get into it !

**Comment by aKalisch** [comment]
RCS is totally possible.
First of you need the netvar for m_Local and m_aimPunchAngle.

Then read LocalPlayer + m_Local + m_aimPunschAngle. 

Then you just need to substract those angles from your ViewAngles.

**Comment by aKalisch** [comment]
Here are 2 screenshots about VisCheck:

<img width="535" alt="bildschirmfoto 2016-10-30 um 11 05 16" src="https://cloud.githubusercontent.com/assets/3403599/19835818/fcd971b4-9e90-11e6-9d41-1adc5d87fd7e.png">

<img width="352" alt="bildschirmfoto 2016-10-30 um 11 05 44" src="https://cloud.githubusercontent.com/assets/3403599/19835821/025d3c2e-9e91-11e6-9d62-304069bea1ec.png">

What you need is BSP Parsing :-)

**Comment by sacredgeo** [comment]
@aKalisch I've got the aimbot working with setting viewangle in clientstate. Thanks for the info. I read about BSP parsing and ray tracing. Seems awfully complex. Could we do a vischeck with m_bSpotted or m_bSpottedby? If I'm looking at an enemy their m_bSpotted should be 1. If they're behind a wall it should be 0 (unless a teammate sees them). 

Edit: I looked into, and it's possible, but apparently it's not a good method. I'm thinking maybe I'll only enable the aimbot if I'm holding shift or some other key.  Won't be able to use it all the time, but it will help when I need it.

**Comment by aKalisch** [comment]
You can do it like this... But it is inaccurate and also it might be hard to handle as you need your own ID (no online it is not "zero").

BSP Parsing is way more simple as it relies on Bones. m_bSpotted relies on anything. So what if your aimbot is set to bone 4 and you just see the Head. Your Aimbot would aim at the wall but the bone is not visible.

If u ask urself how to get Bones: m_nForceBone + 0x1C is a Pointer to the BoneMatrix.

And you read a bone by: BoneMatrix + 0x30 \* nBone + 0x0C (x), BoneMatrix + 0x30 \* nBone + 0x1C (y), BoneMatrix + 0x30 \* nBone + 0x2C (z)

Or you read a Matrix3x4 Type from Memory for each Bone.

**Comment by extrenebiibues** [comment]
@sacredgeo Well if you are going to make it go for head bone you shouldn't lock the crosshair on the head or it will stutter. Is this going to be released lol

**Comment by sacredgeo** [comment]
@extrenebiibues I'm not even using bones yet. I'm basically using the enemy position and adding m_vecViewOffset to the z-axis, which is the location of their head. It works okay depending on their orientation to me. 

@aKalisch I appreciate the info. I'll give the bone matrix a shot. BSP parsing still seems so complicated. I probably won't be able to do it. I'm okay with that though!

**Comment by gabsens** [comment]
BSP parsing doesn't account for props and models (that is to say boxes, crates)... good luck with that

**Comment by extrenebiibues** [comment]
@gabsens so they way you did it if an enemy was behind another enemy would you be able to know that?

**Comment by skoshx** [comment]
@aKalish @gabsens So i was wondering what applications on mac are capable of making signatures? Or do you have to do all of that manually?

Thanks in advance.

**Comment by iseekwonderful** [comment]
So, does anyone willing to push pull requests containing what you are discussing?

**Comment by aKalisch** [comment]
I used Hopper and Bit Slicer for it. The Signatures i need to transform manually. But it was not that hard as I've followed some guides at UC.
