### ISSUE TITLE
hack does not work for me

### ISSUE THREAD

**Issue by moistgoat** [iseekwonderful/csgoGlow#157]
I follow the tut yesterday to set up hack, it works well with no issues.

Next day I run the wall executable I built and hack does not work
I tried to do the Pattern scanner as well and get this error

`goatmansMBP4:Desktop goat$ g++ /Users/goatman/Desktop/main.cpp -o Patternscanner
In file included from /Users/goatman/Desktop/main.cpp:22:
/Users/goatman/Desktop/Utils.cpp:16:5: warning: 'auto' type specifier is a
      C++11 extension [-Wc++11-extensions]
    auto re = vm_read(target, address, sizeof(type), &data, &sz);
    ^
/Users/goatman/Desktop/Utils.cpp:28:5: warning: 'auto' type specifier is a
      C++11 extension [-Wc++11-extensions]
    auto re = vm_write(target, address, (vm_offset_t)&data, sizeof(data));
    ^
/Users/goatman/Desktop/main.cpp:358:5: warning: 'auto' type specifier is a
      C++11 extension [-Wc++11-extensions]
    auto reAddress = Utils::ReadMemAndDeAllocate<uint64_t>(task, current...
    ^
/Users/goatman/Desktop/main.cpp:359:5: warning: 'auto' type specifier is a
      C++11 extension [-Wc++11-extensions]
    auto reCount = readRam<int>(task, imgbase + glowInfoOffset + glowObj...
    ^
4 warnings generated.
Undefined symbols for architecture x86_64:
  "_CFMachPortCreateRunLoopSource", referenced from:
      keyBoardListen() in main-8daa7d.o
  "_CFRunLoopAddSource", referenced from:
      keyBoardListen() in main-8daa7d.o
  "_CFRunLoopGetCurrent", referenced from:
      keyBoardListen() in main-8daa7d.o
  "_CFRunLoopRun", referenced from:
      keyBoardListen() in main-8daa7d.o
  "_CGEventGetFlags", referenced from:
      keyBoardCallback(__CGEventTapProxy*, unsigned int, __CGEvent*, void*) in main-8daa7d.o
  "_CGEventGetIntegerValueField", referenced from:
      keyBoardCallback(__CGEventTapProxy*, unsigned int, __CGEvent*, void*) in main-8daa7d.o
  "_CGEventSetFlags", referenced from:
      keyBoardCallback(__CGEventTapProxy*, unsigned int, __CGEvent*, void*) in main-8daa7d.o
  "_CGEventSetIntegerValueField", referenced from:
      keyBoardCallback(__CGEventTapProxy*, unsigned int, __CGEvent*, void*) in main-8daa7d.o
  "_CGEventTapCreate", referenced from:
      keyBoardListen() in main-8daa7d.o
  "_CGEventTapEnable", referenced from:
      keyBoardListen() in main-8daa7d.o
  "_kCFAllocatorDefault", referenced from:
      keyBoardListen() in main-8daa7d.o
  "_kCFRunLoopCommonModes", referenced from:
      keyBoardListen() in main-8daa7d.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Thanks

**Comment by sacredgeo** [comment]
The hack isn't working because offsets updated yesterday. How are you running the pattern scanner? Run it the same way as the hack. Open terminal, type "sudo -s", then drag the scanner into terminal.

**Comment by moistgoat** [comment]
The issue with the scanner is creating the scanner.

`goatmansMBP4:Desktop goat$ g++ /Users/goatman/Desktop/main.cpp -o Patternscanner
In file included from /Users/goatman/Desktop/main.cpp:22:
/Users/goatman/Desktop/Utils.cpp:16:5: warning: 'auto' type specifier is a
      C++11 extension [-Wc++11-extensions]
    auto re = vm_read(target, address, sizeof(type), &data, &sz);`

And that is where the rest of the error comes from

**Comment by aKalisch** [comment]
compile it with c++11 ... the message is clear.
