### ISSUE TITLE
Offsets, where to input?

### ISSUE THREAD

**Issue by AntonioStipic** [iseekwonderful/csgoGlow#158]
Hello, I downloaded and ran pattern scanner but I dont know where is which value going? 

client: 0x12c800000 19282992
LocalPlayer: 51dd828
EntityList : 515a128
Glow: 59ed160

what do I do with it

in hack, I only have this:

uint64_t glowInfoOffset     = 0x59ed160;
uint64_t LocalPlayerBase    = 0x51dd828;
uint64_t playerBase         = 0x5158f68;

uint64_t m_iGlowIndex       = 0xAC10;

**Comment by aKalisch** [comment]
You are trolling, don't you?
