### ISSUE TITLE
Glow effect.

### ISSUE THREAD

**Issue by nosjoncas** [iseekwonderful/csgoGlow#161]
Anyway to make the glow less thick? For visibility purposes. Ty!!

**Comment by aKalisch** [comment]
This is not possible.
You can just adjust the glow alpha.

**Comment by sacredgeo** [comment]
Not "less thick" but you can increase the transparency by changing 0.8f to something lower like 0.5f.

**Comment by nosjoncas** [comment]
Okay ty.
