### ISSUE TITLE
We need new offsets

### ISSUE THREAD

**Issue by swayamz** [iseekwonderful/csgoGlow#162]
update about 3 mins ago

**Comment by swayamz** [comment]
nevermind bois did it meself 
uint64_t glowInfoOffset = 0x59f14f0;
uint64_t LocalPlayerBase = 0x51e1bb8;
uint64_t playerBase = 0x515d4a8;

**Comment by gazababon123** [comment]
THANKS :D

**Comment by columbusblue34** [comment]
download the new cheat it self updates the offsets
