### ISSUE TITLE
Fov 

### ISSUE THREAD

**Issue by Noriaela** [iseekwonderful/csgoGlow#163]
Is it possible to change the fov kinda like if u were to use 
fov_cs_debug #

**Comment by sacredgeo** [comment]
@sonicrules11 

Can you explain more? Change the field of view for what?

**Comment by aKalisch** [comment]
As CS:GO has no real FOV the short answer is NO!

You can change the viewmodel in every way by console and cvars.

**Comment by Noriaela** [comment]
http://imgur.com/OVh8ynR

**Comment by sacredgeo** [comment]
Why would you want that? It's so awkward trying to play like that.

**Comment by Noriaela** [comment]
I dont know just looks better to me if it isnt possible then its fine I was just wondering

**Comment by aKalisch** [comment]
Okay. There is a way to change FOV. 
But not with external hacks. You need to go internal, as you need full control of the game.
