### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Noriaela** [iseekwonderful/csgoGlow#169]
I keep having a fucking crash issue and it's really starting to piss me off I've had mat_queue_mode 2 and mat_queue_mode 1 but I keep getting crash's and the crash only happens when I'm using it and I can't find some sorta crash log

**Comment by extrenebiibues** [comment]
Yeah you're running a cheat... You're running a program that is altering your game of course it will be heavy

**Comment by aKalisch** [comment]
It may something else than the hack. My own hack is based on this and had it working yesterday for ours without any problems.

Will test this soon and report back.

**Comment by bertrand2012** [comment]
I think it was better when I closed terminal after I'm in the game and have started the hack so give that a try.

**Comment by moistgoat** [comment]
@acer2245 What do you mean by closing terminal after in the game? Do you just completely close out terminal so its not running? Sorry if this is a silly question, but i'm facing the same issue. Thanks.

**Comment by bertrand2012** [comment]
@moistgoat When you close terminal completely the cheat will not stop. I can't completely confirm this but I did complete a whole game doing this.

**Comment by aKalisch** [comment]
@sonicrules11 @acer2245 @moistgoat please refer to issue #171 as this is a duplicate.
