### ISSUE TITLE
mouse Glitching out?

### ISSUE THREAD

**Issue by bromi5** [iseekwonderful/csgoGlow#171]
so I've used this hack for quite a while now and for some reason sometimes the mouse glitches out and you controls to you and your player start lagging and its not your ping or internet because when you spectate other players there fine
thank you for the help,

**Comment by moistgoat** [comment]
Yeah, I have the same issue where my game randomly starts becoming very laggy while using the hack. It makes the game unplayable. I tried restarting the game, steam, and my entire mac, no results.

**Comment by gabsens** [comment]
Revert to previous commits ...

**Comment by aKalisch** [comment]
@gabsens you think my refactoring causes this issue?

**Comment by gabsens** [comment]
@aKalisch either that or Sierra (it'd be useful to know which version of OSX affected users are running). 

I can't tell because I don't play anymore

**Comment by aKalisch** [comment]
@gabsens I use the same approach, memory class and pattern scanner on Sierra without any problems. This might be an issue of older versions of OS X... Will test later an report back then.

**Comment by aKalisch** [comment]
@bromi5 @moistgoat I've updated the files now to get a better performance.

Tested at macOS Sierra. Glow is running beautifully without any issues for more than an hour.

My System: MBP Mid 2015, Intel Graphics, 16GB Ram, i7, 256 GB SSD, macOS Sierra (latest), xcode 8.1 (8B62)

Please provide your system.

**Comment by aKalisch** [comment]
@bromi @moistgoat nothing? So this is fixed?

**Comment by moistgoat** [comment]
Yes, fully functional for me on Mid 2010 MBP. Thanks @aKalisch Sorry for the inactivity.
