### ISSUE TITLE
Would Fake Lag be possible with this?

### ISSUE THREAD

**Issue by rawrchad** [iseekwonderful/csgoGlow#175]
Or is it like a lag switch, if so does anyone know how i come upon this? haha

**Comment by aKalisch** [comment]
It's all possible if you have the expierence to develop those things.

**Comment by aKalisch** [comment]
But this is no issue. This a feature request. Ask this please elsewhere to keep this issuetracker clean.

**Comment by gabsens** [comment]
there's a boolean that says whether or not packets are sent... get the relevant offset and it's done
