### ISSUE TITLE
Failed to get the Client.dylib address

### ISSUE THREAD

**Issue by 123jacob** [iseekwonderful/csgoGlow#178]
Pls help, so i follow the everystep and when i drag the wall to the terminal this pops up. "Failed to get the Client.dylib address"

**Comment by aKalisch** [comment]
Did you run as root (sudo Wall)?

**Comment by 123jacob** [comment]
I said sudo -s then typed my password in then dragged wall into the terminal

**Comment by aKalisch** [comment]
Can you upload a screen of your terminal where all command are visible?

**Comment by aKalisch** [comment]
No verification = closed
