### ISSUE TITLE
Stupid question incoming

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#180]
Hello everyone, I don't know if this thread is still alive but I used to use this months ago and stopped playing for a couple months. I'd like to get back into this but is the hack still safe? Because I have like 3 friends on my steam profile that have band that I know used to use this hack. Just not tryna get banned :P

**Comment by ghost** [comment]
Bans*

**Comment by Noriaela** [comment]
Yes at least for me I haven't been banned at all I've used it for around 5 months and I've had no problems as long as you don't play like a dumbass and be blatant

**Comment by aKalisch** [comment]
VAC Ban = Not possible!
They got overwatched as they are looking at walls to determine where the enemy is... and thats fishy!
