### ISSUE TITLE
Client.dyLib 

### ISSUE THREAD

**Issue by oldpitr** [iseekwonderful/csgoGlow#182]
How can I get this fixed I can include images, also were can I see how to run this?

**Comment by sacredgeo** [comment]
Can you elaborate more please? I'll try to help.

**Comment by bertrand2012** [comment]
Can you include images?

**Comment by aKalisch** [comment]
What is the problem?

**Comment by aKalisch** [comment]
Still no answer and not provided any explanation about this "issue". Will close this for now.
