### ISSUE TITLE
ESEA

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#183]
Hi, I'm curious if anyone has tried this in esea. I'm thinking of getting esea. I obviously won't blatantly hack because I'll be banned, but I'll play as if I'm being overwatched, just like I do in mm and FaceIt. Just curious if anyone knows if it works in esea before I buy it

**Comment by aKalisch** [comment]
Don't cheat in leagues.
That's the most disgusting thing you can do. And if so you need to take the risk.
