### ISSUE TITLE
Potential multi hack?

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#185]
This guy made a multi hack with everything in it that other p2cs have. It is for linux so it's impossible to get detected. This is it https://github.com/McSwaggens/AimTux I feel like someone could port it to Mac OS X? Would be very appreciative if someone did :D

**Comment by Noriaela** [comment]
I agree it would be useful for mac users to have

**Comment by deezysleazy** [comment]
let me know when this is done!

**Comment by deezysleazy** [comment]
someone pls do this!!!'

**Comment by bertrand2012** [comment]
You guys have to stop beggin. If you want a multihack pls just learn how to code c++ and make one for yourselves.

**Comment by deezysleazy** [comment]
im willing to learn, where do i start?

**Comment by aKalisch** [comment]
@deezysleazy You are willing to learn? Really?
Then you wouldn't need to ask where to start. First you should read!
