### ISSUE TITLE
A lot of crashes

### ISSUE THREAD

**Issue by vukashinp** [iseekwonderful/csgoGlow#186]
First of all, wh is pretty good, i tried it a couple of times on DM. But, after 3-4 minutes it starts to crash and immediately exit the game. Also, when i press W button, its going sidewards, not forwards.

**Comment by zefixex** [comment]
@vukashinp limitation of a free project. I gave up on the lag this one gives me and instead started to pay a little for a premium one from mac game hacks. They have a CSGO one now. No crashes, no crazy CPU usage, no weird mouse & keyboard, and slightly more features.

**Comment by vukashinp** [comment]
@zefixex can you recommend me what to use?

**Comment by zefixex** [comment]
@vukashinp [csgomachacks.com](http://csgomachacks.com/?ref=159) - they're the same guys who did callofduty4machacks.com, and you get access to both.

**Comment by vukashinp** [comment]
@zefixex Is there some free hack, because my country dont support PayPal, so there is no way to pay them :(

**Comment by zefixex** [comment]
@vukashinp I would try emailing them, I asked them about the triggerbot once and they emailed back super quick.

**Comment by zefixex** [comment]
@vukashinp did try to look for other free ones, but this csgoGlow is the only one I found, and I don't like what it does to my machine. I can't even type anywhere with this one running. 

There were other sites I found through google, but 99% of them just had windows screenshots and exe files, even though they said mac too :(

**Comment by vukashinp** [comment]
ye, i saw that.. Have you check Cheats For Mac? They offer some free use for 2-4 days, i dont know if they are good..

**Comment by zefixex** [comment]
@vukashinp did try it once, but it didn't do anything for me. Don't know if I was doing it right or not, didn't seem easy to use. I don't think they're anything bad for your machine, you can always try it too and see if you like it. Its also premium though I think.

**Comment by vukashinp** [comment]
OK, i tried it again today. You can see there are no any updates, but, the game is not crashing anymore, have no idea how, but its going very smoothly!
