### ISSUE TITLE
Multi hack part 2

### ISSUE THREAD

**Issue by brendon11** [iseekwonderful/csgoGlow#187]
Don't really know why last one was closed, but I've ported almost everything over, just having a little trouble with GUI, should be done in a couple days or so or when I have time

**Comment by Noriaela** [comment]
Do you plan on making it Free or Pay?

**Comment by rawrchad** [comment]
Will we be able to use it?

**Comment by MyNameIsLebronJames** [comment]
^^

**Comment by vukashinp** [comment]
Any news soon?

**Comment by sembsa** [comment]
I join the questions :)

**Comment by MyNameIsLebronJames** [comment]
It's been way more than a couple days ;3

**Comment by aKalisch** [comment]
As you may noticed I closed this last times as I do now... This is an ISSUE tracker. Not any Support Forum.
Use unknowncheats.me instead!
