### ISSUE TITLE
New Valve Anti-Cheat?

### ISSUE THREAD

**Issue by MyNameIsLebronJames** [iseekwonderful/csgoGlow#190]
Just minutes ago, CSGO just got an update. Valve is working on a anti-cheat to detect and get ahead of spinbotters/cheaters. Does anyone know if this will effect mac cheaters?

**Comment by Noriaela** [comment]
Unless they make something for us mac and Linux users I'm pretty sure it won't effect us I could be wrong tho

**Comment by aKalisch** [comment]
This VAC Update is Server-side... so yes it can affect mac users.
But since there is no public hack with Anti-Aim or Spinbot we are still fine.

STILL NO VAC ON MAC!
