### ISSUE TITLE
Triggerbot

### ISSUE THREAD

**Issue by Kazzaowo** [iseekwonderful/csgoGlow#192]
Ive tried to write some code for triggerbot and it's worked mostly, but i have been searching for 3 hours straight and i cant find a way to simulate a left click when the code has detected someone in my crosshair. it works fine when it prints to terminal but i cant press mouse1. Please help?

**Comment by Galenika** [comment]
Take a look at this source it has triggerbot in it:
https://github.com/aKalisch/gosx-public-external

**Comment by Kazzaowo** [comment]
thank you so much, ill check it out.

**Comment by bumbojumbo** [comment]
Would you be willing to share, I have yet to find an actual good triggerbot.

**Comment by loco41211** [comment]
@bumbojumbo if you're looking for ready-to-use perfection, your best bet is to go premium

**Comment by bumbojumbo** [comment]
The premium cheats that I found weren't any better than the glow code with
a broken aimbot..

**Comment by loco41211** [comment]
@bumbojumbo guess you haven't tried them all! Advantage tool's working pretty well for me. Doesn't have an aimbot but I don't care for it

**Comment by bumbojumbo** [comment]
I'll check it out.
