### ISSUE TITLE
I cant build the product with xcode.

### ISSUE THREAD

**Issue by Arizonateaisthebest** [iseekwonderful/csgoGlow#193]
Hello I am using xcode 5.0.2 and my macbook's version is 10.10.5 OSX Yosemite. I cant build the product in xcode. Can someone help me with it? I followed the video's instructions but I am having problems with the files I downloaded. I am going to attach a screenshot of the errors.
![screen shot 2017-03-20 at 7 14 50 pm](https://cloud.githubusercontent.com/assets/26557811/24126044/3beccede-0da2-11e7-8c9e-c29e1f33d695.png)

**Comment by iseekwonderful** [comment]
i guess that your should try update xcode to latest version

**Comment by Arizonateaisthebest** [comment]
hey iseekwonderful, the problem is i dont know if the latest version of xcode could work for my mac version. my version is 10.10.5 Yosemite... I know the CSGOGlow works with my version for my mac because a website called cheatsformac.com . there wallhack/esp is the csgoglow made by you.. If you could help me find a version of xcode that can run this xcode project that would be great.

**Comment by aKalisch** [comment]
Just open the App Store and upgrade to the lastest version of Yosemite.
It should be even 7 or 8.
