### ISSUE TITLE
XCODE downloaded new components and now doesnt work PLZ Help

### ISSUE THREAD

**Issue by sulik12345** [iseekwonderful/csgoGlow#194]
https://gyazo.com/c51bdd68228ff47052999a1d106ce81d

**Comment by sulik12345** [comment]
Wall command that I drag into terminal doesn't work.

When I do 

sudo (drag wall from debug folder into terminal folder) and hit enter

**Comment by aKalisch** [comment]
Those are warnings. Can be ignored or easily been fixed.
