### ISSUE TITLE
只为找到你

### ISSUE THREAD

**Issue by up-up** [iseekwonderful/csgoGlow#196]
博主，浏览留你的blog有一些疑问。但是你的blog没有开通comment功能，在about上也没有留任何联系方式，希望你建立一个可以联系到你的方式，例如：邮箱、微博、twtter、微信、简书或者开通一下可以进行comment的博客。最后造成我只能通过在这个不相干的地方new issue。😅

**Comment by iseekwonderful** [comment]
可以通过邮箱联系 sss3barry@gmail.com 😀
