### ISSUE TITLE
glow

### ISSUE THREAD

**Issue by wanbotak** [iseekwonderful/csgoGlow#197]
this glow still can use ?
or offset outdate and need to update new offset?

**Comment by iseekwonderful** [comment]
use https://github.com/gabsens/Pattern-scanner-for-OSX to keep your offset updated

**Comment by wanbotak** [comment]
whether in the future you will add some functions like no recoil,triggerbot,etc maybe?

**Comment by Galenika** [comment]
@wanbotak  Dont think that will happen.. you can go here if u want more features: 
https://github.com/aKalisch/GO-SX-Internal-Lite

**Comment by aKalisch** [comment]
Offsets should be fine unless the signatures didn't change...
It is auto updating.
