### ISSUE TITLE
Glow stopped working. Any solutions?

### ISSUE THREAD

**Issue by CBilbao** [iseekwonderful/csgoGlow#200]
Hey, source code worked fine for a few days up until today. Also, checked offsets and glow offset check returned as segmentation fault? Pics provided:

**I understand the pattern scanning is already implemented but I just wanted to add this just incase:**

![](http://oi64.tinypic.com/21kjgn9.jpg)

**Wall executable results during match w/ bots:**

![](http://i66.tinypic.com/2s6oqw3.png)

**Pattern Scanner executable results during same match w/ bots:**

![](http://oi64.tinypic.com/znrnk4.jpg)

**Comment by AndrewWolfgramm** [comment]
Same thing happened to me just now. I think it had something to do with the new csgo update.

**Comment by desginerxd** [comment]
same for me :( crying

**Comment by aKalisch** [comment]
Please be patient. CS:GO Update brokes the Signature. Currently getting a new Signature for it.

**Comment by HelloMyDudes** [comment]
Can someone link the built file once it's fixed. I don't have Xcode and don't know how to use

**Comment by desginerxd** [comment]
HelloMyDudes i will upload it for you after its fixed

**Comment by Guters** [comment]
desginerxd can you help me too please ? More or less how long does it take? I'm cry :(

**Comment by loco41211** [comment]
doesn't look like the premium tools are affected, if you're desperate

**Comment by NetFelix** [comment]
Same here, please link the built file once it's fixed. I don't have Xcode and don't know how to use

**Comment by CsgoCheater** [comment]
Just like the person above said, Can someone link the built file once it's fixed. I don't have Xcode and don't know how to use

**Comment by CsgoCheater** [comment]
haha, played a game without wallhack, i have used it for over 3 months now when i've been playing with friends and now we played a game without and i got like 12 kills when i usually get around 30 hahaha...

**Just like the person above said, Can someone link the built file once it's fixed. I don't have Xcode and don't know how to use**

**Comment by aKalisch** [comment]
http://www.gosx.one this hack is working by now

**Comment by Guters** [comment]
aKalisch Can you explain how this works?

**Comment by BlankRR** [comment]
aKalisch do you know when or how long it this would take or is it a simple fix please respond if you know. Thank you.

**Comment by deanweston** [comment]
I have also noticed the hack not working on my OSX system after the update yesterday. Can someone upload the new download after its fixed? thx

**Comment by Vyriz** [comment]
How exactly do you get a signature? I'm great with Xcode but have no experience whatsoever with hacking lol

**Comment by CsgoCheater** [comment]
any updates? :/

**Comment by p0hjan** [comment]
there is alot of other cheats u could use meanwhile. :)

**Comment by deanweston** [comment]
Like what? I can't find any free cheats for Mac OSX working except this one

**Comment by p0hjan** [comment]
gosx.one

**Comment by deanweston** [comment]
Its cheats for mac, and we need to buy a license for it

**Comment by p0hjan** [comment]
its free :)

**Comment by p0hjan** [comment]
Gosx.one is free ^

**Comment by deanweston** [comment]
Ok ive downloaded it so how do i apply it to csgo?

**Comment by p0hjan** [comment]
Join the discord its on the site. i'll help you.

**Comment by deanweston** [comment]
can u just tell me here since i have just went out

**Comment by p0hjan** [comment]
`cd downloads
cd gosx_release_1.1.5
sudo ./gosx`

**Comment by deanweston** [comment]
so i type them in line by line?

**Comment by deanweston** [comment]
terminal too right?

**Comment by p0hjan** [comment]
yeah, 1 after 1 in terminal :)

**Comment by deanweston** [comment]
then i will activate the hack in csgo

**Comment by deanweston** [comment]
do i need to type it in every time i open csgo?

**Comment by p0hjan** [comment]
yes.

**Comment by CsgoCheater** [comment]
I can't get GOSX to work can someone help me..? or just upload the part i put in the console

im a noob at this hehe.

**Comment by CsgoCheater** [comment]
Can somone explain more in detail? i didnt undertand.

**Comment by CBilbao** [comment]
Instructions are in one of aKalisch's repos. If you're using GO:SX Lite, open up Terminal:


**Type:**

![](http://oi67.tinypic.com/2wg9f6c.jpg)

**Open CS:GO then return to terminal and type:**

![](http://oi67.tinypic.com/2lctjrb.jpg)

**Enter system user password and message will pop-up that it is injected**

**Comment by CsgoCheater** [comment]
Thank you so much

**Comment by CsgoCheater** [comment]
Im not getting a message pop-up..

**Comment by xTempoh** [comment]
Sry guys, GO:SX is 100% undetectable by vacban?

**Comment by dubide** [comment]
guys wtf "You cannot play on secure servers", i only used chams

**Comment by dubide** [comment]
what do I do now?

**Comment by p0hjan** [comment]
It works, ur just doing something wrong.

**Comment by dubide** [comment]
the fn backspace worked, but now I cant connect to anything, wtf do I do??

**Comment by dubide** [comment]
help? @p0hjan wtf do i do??

**Comment by AndrewWolfgramm** [comment]
It works fine. Do exactly as CBilbao instructed (if you stored the file in a different folder then obviously use the name of the folder you stored the files in). 

Double check your spelling in terminal as well as I have been caught off guard a couple times with slight misspellings. If you still have trouble here is a link that explains it in a bit more detail. 

https://github.com/aKalisch/GO-SX-Internal-Lite

**Comment by Vyriz** [comment]
So this hack still doesn't work? I don't care about other hacks lol

**Comment by dubide** [comment]
@AndrewWolfgramm it injected fine, I saw the alert and see GO:SX lite on the top left, but it won't let me join anything anymore. I can't play :( please don't tell me I can't use my account anymore :(

**Comment by dubide** [comment]
<img width="551" alt="screen shot 2017-04-27 at 21 24 04" src="https://cloud.githubusercontent.com/assets/28115595/25502763/f0e7a5ec-2b8f-11e7-8f20-bc74245cca29.png">
what do I do???

**Comment by Vyriz** [comment]
Weren't you VAC banned??

**Comment by dubide** [comment]
i hope not :((

**Comment by dubide** [comment]
ill try to reinstall :(( please hope this'll fix it :(

**Comment by Vyriz** [comment]
1) verify game cache and on your profile that you weren't VAC banned,
2) restart computer
3) check the date and time is set properly on your computer

Come back and tell us

**Comment by dubide** [comment]
thanks for trying to help @Vyriz :( I deleted csgo and am reinstalling, will let you know :(

**Comment by slon420** [comment]
If it Fixed wehre can I found it ?  Can someone upload it on GITHUB again maybe?
Or explain me on discord how to run GO-SX...im to stupid :/

**Comment by dakedake123** [comment]
@dudibe this doesn't mean that you're vac banned, don't worry. It just means that you can't join any VAC-secured server because it seems like something in your game files is blocking the VAC system.

**Comment by slon420** [comment]
@p0hjan can u help me on discord pls ? Or someone else?
sLon#5035

**Comment by AndrewWolfgramm** [comment]
@dubide that's unfortunate. Mine worked without issue. Hopefully someone here can find a fix for you.

**Comment by MacHacks** [comment]
There you go party people, fixed the offsets, since this repo seems dead and unmaintained: https://github.com/MacHacks/CSGOGlowMac @slon420  @dubide @Vyriz @xTempoh @CsgoCheater @BlankRR @Guters @desginerxd @HelloMyDudes @CBilbao

**Comment by Vyriz** [comment]
@MacHacks I would love it if you could explain to me how you did it/ what the process was

**Comment by dakedake123** [comment]
https://github.com/MacHacks/CSGOGlowMac  is this safe to use? can anyone answer please ?

**Comment by Vyriz** [comment]
@dakedake123 it's the same thing as this one. 

I've played with it for the past 2 hours. Exactly the same, undetected

**Comment by klimikus2003** [comment]
@Vyriz Hi, where can i download Xcode, without app store?

**Comment by dakedake123** [comment]
why without appstore? just download it from the fking appstore its for free

**Comment by klimikus2003** [comment]
@dakedake123 i know, but i don't have credit card

**Comment by klimikus2003** [comment]
@dakedake123 I know its free, but i need put info about credit card

**Comment by loco41211** [comment]
@klimikus2003 try a fake credit card number, or this: http://stackoverflow.com/a/10335943/880837

**Comment by slon420** [comment]
THANK U GUYS !! U R THE BEST !!! LOVE YOU :*:*:*

**Comment by dakedake123** [comment]
dont use this : https://github.com/MacHacks/CSGOGlowMac , your game will crash every 2 minutes and the hack also stops working randomly during the game..

**Comment by loco41211** [comment]
@dakedake123 it's the exact same as this, the only difference is lines 116-138 in main.cpp. Maybe more changed in-game, offsets aren't enough? @MacHacks

**Comment by Vyriz** [comment]
No, the new hack is fine. I've played with it for more than 2 hours. It's just you

**Comment by MacHacks** [comment]
@loco41211 correct, disabled the pattern scanner since the old patterns aren't valid/fixable anymore. Will try to find new patterns, but in the meantime I've hardcoded the current offsets in main.cpp. It'll break again with the next update, but shouldn't take too long to fix.

@dakedake123 if you can't get past it and want me to look into it, log an issue in the new repo: https://github.com/MacHacks/CSGOGlowMac/issues

Include anything you think might be related, or try to see if anything affects whether or not this happens. I'm talking about whether it's specific to game-mode, whether it only happens in certain scenarios but not others (e.g. between rounds, or connecting to a new server).

**Comment by CsgoCheater** [comment]
Can someone please upload the "main file" that i can just 
sudo -s
Drop in the console file and press enter?

i don't know how to use xcode sadly... 
thanks in advanced.

**Comment by klimikus2003** [comment]
@CsgoCheater Yes, I'm too want it

**Comment by klimikus2003** [comment]
@loco41211 thanks

**Comment by p0hjan** [comment]
https://discord.gg/WvCkvpW Join this discord if u need help with GOSX And i'll try my best. Btw GOSX is el captain and newer. Yosemite will **NOT** work.

**Comment by crazyexplosive** [comment]
So... anyone posted the main file that I can just drag and drop into terminal yet? Need it please.. xcode taking forever to download

**Comment by dubide** [comment]
fucking gosx! reinstalled the whole game, deleted the shitty gosx and still VAC. I can't play anymore!! wish I never fucking tried it :( dont trust that shit

**Comment by Vyriz** [comment]
Here it is, I would have sent it sooner but I wasn't home. 
[Wall.zip](https://github.com/iseekwonderful/csgoGlow/files/965454/Wall.zip)

**Comment by p0hjan** [comment]
@dubide  ur just a retard. You cant get vacced on mac.

**Comment by BlankRR** [comment]
p0hjan what do you mean you can't get vac banned on mac? like do you mean you won't be able to get banned of cs or do you mean you can't get vacced while using the hack?

**Comment by nepeconda** [comment]
If you dont understand the terms used here or in the hack itself, dont use it. Simple. Also, dont spread bullshit if you fucked up by being a retarded cunt. This cheat WORKS and you can figure it out by yourself if you have a functioning brain and common sense.

**Comment by p0hjan** [comment]
What im saying is, You cant get vacced on mac unless ur using cheatengine or something else like that.

**Comment by AndrewWolfgramm** [comment]
@dubide theoretically you cannot get VAC banned on Mac OSX. Because the way VAC works. You can still get Overwatch banned if you make it super obvious that you're cheating. I would say your ban came from you making it super easy for overwatch to tell that you were cheating.

**Comment by AndrewWolfgramm** [comment]
Have run the latest update of this hack. It does work. However it does cause the game to crash from time to time. But so did the last version after a few games I found it doesn't it crash as often. Gosx doesn't cause the game to crash at all. But the aimbot on that makes glaringly obvious you are cheating if you are below DMG rank lol.

**Comment by aKalisch** [comment]
@dubide you are such stupid. I'm the developer of gosx and just have been banned for playing blatantly. When playing legit I've never been banned. 
So stop spreading Bullshit around. GO:SX isn't detected at all.

Also I already have the new signature for the Glow Struct. But I was to lazy to get the new ones for Localplayer and EntityList.

**Comment by aKalisch** [comment]
![20170429112709_1](https://cloud.githubusercontent.com/assets/3403599/25554487/e39a5a3e-2cce-11e7-98a9-ad25f8f62b74.jpg)

It's alive! :D

**Comment by aKalisch** [comment]
8e7818e4785b7f7f6708d22a1a96281a2c538367

There you go my friends...

**Comment by aKalisch** [comment]
@Andrew then don't use aimbot. I use Aimbot even on GN2 and never got banned for legit cheating.

**Comment by cadeseagle** [comment]
It says sudo ./gosx is command not found. what do I do?

**Comment by GAMESTAND** [comment]
You need code to download all of the sudo files
