### ISSUE TITLE
CSGO GLOW STOPPED WORKING

### ISSUE THREAD

**Issue by angryafrikaan** [iseekwonderful/csgoGlow#202]
It stopped working after the new update plz fix

**Comment by edwardy0ng** [comment]
Works for me.

**Comment by aKalisch** [comment]
All is fine after update.

**Comment by Dake07** [comment]
youre using MacHacks version, update to the new one

**Comment by GAMESTAND** [comment]
Alright I know how to Solve the Problem Watch The Video, Follow the step
very carefully
https://www.youtube.com/watch?v=hdEMe7Pa688
