### ISSUE TITLE
Stopped working again

### ISSUE THREAD

**Issue by CsgoCheater** [iseekwonderful/csgoGlow#204]
It has stopped working again after the new update.. 👎  :(

**Comment by slon420** [comment]
yeah FUCK steam -.- 
maybe they know from this DEBUG?

**Comment by CsgoCheater** [comment]
Yea i have no idea tbh...

**Comment by Dake07** [comment]
try to download the newest wall, from akalisch, if youre using the one from MacHacks then this might be the problem

**Comment by CsgoCheater** [comment]
> try to download the newest wall, from akalisch, if youre using the one from MacHacks then this might be the problem

Can you give me the link?

**Comment by Dake07** [comment]
link ? it's literally around the corner if you know what i mean lol

**Comment by Dake07** [comment]
just press on code next to issues

**Comment by angryafrikaan** [comment]
Have they updated the hack yet?

**Comment by GAMESTAND** [comment]
instead of updating do it yourself...... Watch this video Tutorial: using
the pattern scanner on OSX - YouTube
<https://www.youtube.com/watch?v=aP99mdDzwQk>

**Comment by angryafrikaan** [comment]
I found some of the new code I found everything besides the glow
If someone can find that we can combine and recode it
LocalPlayer: 10f19c8
EntityList : 10fdb18

**Comment by slon420** [comment]
LocalPlayer: 10f19c8
EntityList : 10fdb18
Segmentation fault: 11
bash-3.2# 


Why I don't geht the GLOW Number ? can someone help me?

**Comment by sacredgeo** [comment]
Watch the tutorial for the glow offset. It takes 5 minutes once you know how.

https://www.youtube.com/watch?v=3HhD7WNzSno

**Comment by slon420** [comment]
@sacredgeo Thanks for your help man but I understand nothing from this tutorial :/ 
I watch his last Tutorial for the with the Patternscanner and it works cause is very simple but I don't got the Glow-Nummer like in the tutorial :/ 
 PLS help me Someone If someone got time Or the new Glow number.

Thanks.

**Comment by Dake07** [comment]
What is the problem? The hack is working perfectly fine wtf..

**Comment by slon420** [comment]
@Dake07 How ? without update ?

**Comment by sacredgeo** [comment]
slon420, he explains it very well in the video. Have you tried to follow along? What part are you having trouble with?

**Comment by slon420** [comment]
@Dake07 yeah I download it again and it works again ... but I got DC after 2 or 3 Rounds.. don't know why :/

**Comment by slon420** [comment]
LocalPlayer: 10f19c8
EntityList : 10fdb18
Segmentation fault: 11
bash-3.2#


im just need the Glow number :/ but that is to heavy for me or im to stupid

**Comment by gabrielABCDE** [comment]
Guys, can someone link the updated hack?Because I have troube w/ xCode, for some reason, I cant download it, so pls, give me the link

**Comment by angryafrikaan** [comment]
Link me?

**Comment by gabrielABCDE** [comment]
@Dake07 link me pls bro

**Comment by gabrielABCDE** [comment]
@sacredgeo dude, can u upload the Wall file?Because I cant dl xCode to build the file, so pls upload the updated file plsss

**Comment by XxGODSPEEDxX** [comment]
https://www.youtube.com/watch?v=hdEMe7Pa688 Watch this video you do not need the glow or anything... 
Follow it really carefully

**Comment by Dake07** [comment]
If you can't download xCode then pleeasseee stay away from hacking lol

**Comment by gabrielABCDE** [comment]
@Dake07 that means nothing LOL, I can hack without xCode, but if someone send me the wall exec dl link...;(

**Comment by GAMESTAND** [comment]
If you can't download code get the fuck out. Nobody is going to download
some extra shit for you

**Comment by gabrielABCDE** [comment]
@GAMESTAND Im not talking to you, fucking nigger I will go and fuck your mom's pussy

**Comment by GAMESTAND** [comment]
But you're mother chopped off your dick you fuck

On May 6, 2017 1:17 PM, "gabrielABCDE" <notifications@github.com> wrote:

@GAMESTAND <https://github.com/GAMESTAND> Im not talking to you, fucking
nigger I will go and fuck your mom's pussy

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/iseekwonderful/csgoGlow/issues/204#issuecomment-299653768>,
or mute the thread

**Comment by gabrielABCDE** [comment]
@GAMESTAND stfu you fucking fat HAHAHAHA omfg go kys fucking bitch

**Comment by GAMESTAND** [comment]
Thank you you faggot
