### ISSUE TITLE
Fixed it 

### ISSUE THREAD

**Issue by XxGODSPEEDxX** [iseekwonderful/csgoGlow#205]
https://www.youtube.com/watch?v=hdEMe7Pa688 watch the video

**Comment by gabrielABCDE** [comment]
NO ONE IS GOING TO FUCKING BUY IT HAHAHAHA OMFG

**Comment by XxGODSPEEDxX** [comment]
did you fucking try it

**Comment by gabrielABCDE** [comment]
I dont have xCode dude...I just need to dl the fixed wall exec...

**Comment by GAMESTAND** [comment]
well sucks for U
