### ISSUE TITLE
I fixed it I'm linking the file

### ISSUE THREAD

**Issue by angryafrikaan** [iseekwonderful/csgoGlow#206]

**Comment by angryafrikaan** [comment]
Everyone come and get it

**Comment by angryafrikaan** [comment]
It's not letting me put the exec file in guys

**Comment by angryafrikaan** [comment]
If someone can tell me hwo I can get the zip of the exec I will link it right away

**Comment by angryafrikaan** [comment]
Or if you tell me your discord I'll guive the file

**Comment by gabrielABCDE** [comment]
upload it on media fire

**Comment by gabrielABCDE** [comment]
or 4shared, dropbox

**Comment by angryafrikaan** [comment]
I tried mediafire and I downloaded it to test and it says can't open file from unidentified dev so Imma try the other ones you suggested

**Comment by angryafrikaan** [comment]
If you think you can figure out the mediafire thing heres the link

**Comment by angryafrikaan** [comment]
http://www.mediafire.com/file/n65bpoc4r1370g7/Wall
