### ISSUE TITLE
New csgo signatures

### ISSUE THREAD

**Issue by kingcobraa** [iseekwonderful/csgoGlow#208]
After the May 2nd update this no longer works

**Comment by sacredgeo** [comment]
You need to find the addresses. Use bit slicer and watch the tutorial. You can do it in less than 15 minutes.

**Comment by HugoCunhaCV** [comment]
how? fix it then please

**Comment by aKalisch** [comment]
https://github.com/iseekwonderful/csgoGlow/pull/228
