### ISSUE TITLE
Can someone make an updated version? or make a good guide  on how to do it ourselves?

### ISSUE THREAD

**Issue by gabebs1** [iseekwonderful/csgoGlow#209]
Title says it all, please dont be vague if you decide to make a guide/tut.  And also asking if anyone knows of a good triggerbot/aimbot for mac

**Comment by angryafrikaan** [comment]
The hack works completely fine..

**Comment by aKalisch** [comment]
https://github.com/iseekwonderful/csgoGlow/pull/228
