### ISSUE TITLE
Says No root Permission

### ISSUE THREAD

**Issue by kschultee** [iseekwonderful/csgoGlow#21]
Even after setting to run through root, and signing in through root, I receive error saying The pid is 1534
Version: 14, 290 images at offset 0x8fea2a9401803c00
get lists failed 
No root permission
Please run it with root
Program ended with exit code: 0

Xcode 7.3 BTW

**Comment by iseekwonderful** [comment]
hmm, do u open csgo while running this?

**Comment by kschultee** [comment]
Yes. I actually figured it out about 2 hours after posting it. I just needed to reset the code and re-run the program. Thanks much!
