### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by psunco** [iseekwonderful/csgoGlow#211]
ran it in terminal with root and without and did not work. i ran it with root then i drragged the wall like instructed but not working please help

**Comment by angryafrikaan** [comment]
It's working perfectly fine for me

**Comment by psunco** [comment]
please help

**Comment by Vyriz** [comment]
Doesn't work, probably because of update

**Comment by aKalisch** [comment]
https://github.com/iseekwonderful/csgoGlow/pull/228
