### ISSUE TITLE
How to add toggle for wallhack?

### ISSUE THREAD

**Issue by edwardy0ng** [iseekwonderful/csgoGlow#212]
How do add a toggle key for glow?

**Comment by Galenika** [comment]
CTRL + ALT + V toggles glow

**Comment by Galenika** [comment]
look in keyboard.h

**Comment by LemonGoo** [comment]
Which part of keyboard.h should i change to implement the toggle key?

**Comment by manigamer22** [comment]
How to change it only one key i want it H how to do it? plz help
