### ISSUE TITLE
Toggle key

### ISSUE THREAD

**Issue by LemonGoo** [iseekwonderful/csgoGlow#214]
Sorry, amateur coder here.

I posted on another active thread but still no resolution so i started my own thread.

Wanted to ask which part of keyboard.h should i edit to implement a toggle key, thank you

**Comment by Deadly78** [comment]
Edit keyboard.h ... jk just go into keyboard.h and near the bottom of the lines, find the lines 
     if (keycode == keyCodeForKeyString("ctrl + alt + v")) {
Then just edit the "ctrl + alt + v" into whatever you want. For example, I changed mine into 
        if (keycode == keyCodeForKeyString("v")) {
Don't forget to do CMD + S to save the edits and then just recompile.

**Comment by klimikus2003** [comment]
Guys, help me not working sound in csgo (music, shooting, explosives, all) I tried to check cache and reinstall game
