### ISSUE TITLE
Mouse Movement

### ISSUE THREAD

**Issue by Redmang0** [iseekwonderful/csgoGlow#216]
Is it normal to have lots of lag and weird, jerky mouse movement when using this cheat? It makes the game hard to play.

**Comment by klimikus2003** [comment]
Guys, help me not working sound in csgo (music, shooting, explosives, all) I tried to check cache and reinstall game

**Comment by slon420** [comment]
SAME HERE!!! MOUSE HARD LAGS!!

**Comment by drauf** [comment]
Your Mac might be too slow. Increase the sleep time in the main function, the cheat will be using fewer resources but also be less reliable.
