### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by gabrielABCDE** [iseekwonderful/csgoGlow#217]
I just want to know why my game is crashing every time I use the hack?

**Comment by sonicrules11** [comment]
Outdated

**Comment by sonicrules11** [comment]
If you wanna use a cheat for OSX 
Currently there are 2 public that are up
http://vlone.cc/
and 
https://www.gosx.one/

**Comment by danielr-kainos** [comment]
As sonicrules11 said. Basically, some offsets changes slightly (+/- 10 bytes), you can update them and it'll work or use other public cheats.

**Comment by vukashinp** [comment]
I downloaded GOSX, but it has a lot of issues, and it says that i am not in cs:go match

**Comment by sonicrules11** [comment]
https://discord.gg/rvKy53F

**Comment by gabrielABCDE** [comment]
@sonicrules11 how can I change the skins of vlone?

**Comment by sonicrules11** [comment]
@gabrielABCDE https://discord.gg/d2AcFQr vlone discord

**Comment by aKalisch** [comment]
https://github.com/iseekwonderful/csgoGlow/pull/228
