### ISSUE TITLE
It crashes!!!!

### ISSUE THREAD

**Issue by arehman26** [iseekwonderful/csgoGlow#230]
Any suggestions??

**Comment by inormalize** [comment]
I use to play one round of deathmatch 10m, then enable and wouldn't see crashes. I only saw crashes enabling quickly after starting play. So you can do that as a workaround. What i'm doing now is using a dated version of the app with updated offsets.

**Comment by ghost** [comment]
Yes please fix this issue, sometimes it works fine, sometimes it crashes after 3 rounds and restarting terminal doesnt help,  i have to restart steam then it will work. But even then it crashes after 3
