### ISSUE TITLE
Not an issue, but how could I change the toggle key to the mouse button?

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#232]

**Comment by drauf** [comment]
Look at the `utils/keyboard.h` file, namely lines 163-168.

**Comment by ghost** [comment]
What would the key code for a middle mouse button be, its not listed on the that file.

On 6 Nov 2017, at 08:01, Daniel Rauf <notifications@github.com<mailto:notifications@github.com>> wrote:


Look at the utils/keyboard.h file, namely lines 163-168.

**Comment by drauf** [comment]
Actually, since it's not a keyboard event but a mouse event, you can remove everything but the first and last line in the function, filter by the [otherMouseDown](https://developer.apple.com/documentation/coregraphics/cgeventtype) event on line 155 and toggle the states flag after that.
