### ISSUE TITLE
how do we add features to this

### ISSUE THREAD

**Issue by manigamer22** [iseekwonderful/csgoGlow#235]
I want to add aimbot and triggerbot to this but i cant please help me!

**Comment by bddvlpr** [comment]
Just use xOracle or something else. As the project name says, "csgoGLOW", it isn't more than a wallhack.

**Comment by manigamer22** [comment]
but xoracle has its name on top of the screen. But I only want glow hack, trigger, RCS,  and no game crashing

**Comment by manigamer22** [comment]
but xoracle has its name on top of the screen. But I only want glow hack, trigger, RCS,  and no game crashing. It crashes every second game

**Comment by drauf** [comment]
Then learn to code, read some open source cheat's code for Windows/Linux and port it to Mac. :)
