### ISSUE TITLE
Possible for Windows

### ISSUE THREAD

**Issue by wo0ben** [iseekwonderful/csgoGlow#236]
Probably not this exact code but is there a way to get the outline and health outline for windows to work on every model, there is an ahk file, but that only works on certain models. 

A reply would be great thanks :)

**Comment by drauf** [comment]
The logic is exactly the same, the main difference between platforms is that Linux and Mac use 64 bit clients and Windows uses 32 bit, so some structs have different sizes.

**Comment by wo0ben** [comment]
So how could we get it on Windows?

**Comment by drauf** [comment]
If you know nothing about coding, your only bet is to use some public cheat. As a warning, VAC is mostly targetting Windows users, since they make up the majority (possibly more than 99%?) of the cheaters. At least a few months ago, VAC for Mac did absolutely nothing.

**Comment by aKalisch** [comment]
And it is still doing nothing than sending your authentication to VAC Secured servers. But it's not checking for any cheats.
And since so much time has past I think Valve will never release any decent Anti-Cheat system for *nix based systems.
