### ISSUE TITLE
Not working!!!!!!!! 

### ISSUE THREAD

**Issue by arehman26** [iseekwonderful/csgoGlow#237]

**Comment by ningwang747** [comment]
Not working after CS:GO UI Panorama Update

**Comment by rpranshu** [comment]
@iseekwonderful Please update the code to work with the latest version!

**Comment by ghost** [comment]
Did they update Mac to Panorama? I thought it was just the 7/6/2018 update.

From what I heard, the m_iGlowIndex was changed. I considered outdated pointers/offsets, but I don't really know much about it so I'm not sure.
Maybe the update/panorama thing just completely broke how the glow is written to memory?

I'm clutching at straws here because I have no idea what broke.

Pls fix!

Edit: The 7/6/2018 update has broken (as far as I know) all mac cheats. Probably because of some change to the offsets.

**Comment by loco41211** [comment]
Probably either the glow offset or the pointers to structs. Looks like both CFM and MGH are back up and running though.

**Comment by ghost** [comment]
Yeah probably. I'm not sure how to get them though; I guess there's hazedumper for the GlowIndex (same as glow offset? Idk) but I dunno about the pointers.

Edit: I wonder if when Panorama comes to mac I'll mess cheats up again as well (It messed up internals for windows a bit, but mostly just the UI of the internals and not any of the important stuff).

**Comment by mattyj5934** [comment]
The glow doesn't work, but for some reason there's glows on dropped weapons for me

**Comment by KaboomXD** [comment]
The glow isn't working completely, the recent update messed something up. It sometimes enables glow onto weapons but when I changed the value of "usleep" from 3000 to 15000 it enables glow onto stationary objects, like a ladder or sometimes even a moving object like a fan. Please someone if you can update this code because its honestly amazing.
Thank you,
Allen

**Comment by KaboomXD** [comment]
Guys I fixed the code, all you have to do is build a new Wall executable through Xcode and before doing that change the value for "....
<img width="364" alt="screen shot 2018-07-08 at 6 41 10 pm" src="https://user-images.githubusercontent.com/40949856/42419863-c386336e-82de-11e8-8cd0-45c742acbb2a.png">
iGlowIndex"

**Comment by mattyj5934** [comment]
Can you make a video about it? I don't have a clue on how to code. THANKS

**Comment by ghost** [comment]
@mattyj5934 @KaboomXD That doesn't work, at least for me. Thats just the updated iGlowIndex, but I think we also need new pointers for the other offsets.

@mattyj5934 I can make a video or show you how to do it once we figure this out. @KaboomXD did updating the iGlowIndex work for you?

**Comment by ghost** [comment]
@aKalisch SAVE US

**Comment by mattyj5934** [comment]
@Shadesprite Thanks dude that would be awesome

**Comment by diogosilva212** [comment]
Can someone save us please?! :(

**Comment by macacodobem** [comment]
update the code pls. @iseekwonderful

**Comment by ghost** [comment]
We may also have to update the m_iHealth and m_iPlayerTeamNum offsets? All the offsets? All pointers and offsets? I've tried everything I can think of. Might even be my CS:GO acting up, I don't know.

That's all I've really been able to figure out, I'm rather unfamiliar with the code of csgoGlow and honestly Source in general.

I tried. :b

**Comment by diogosilva212** [comment]
But where can I find those offsets/pointers? In which file can I edit that? (sorry if it's a noob question)

**Comment by ghost** [comment]
That's the problem: I don't know. If I did I would have uploaded a fix :P

**Comment by diogosilva212** [comment]
I've found it. It's on the main.cpp. But the offsets on "hazedumper" are for "Int32"...

**Comment by diogosilva212** [comment]
@Shadesprite it's this part:

` int glowIndex           = mem->read<int>(memoryAddress + m_iGlowIndex);
        int health              = mem->read<int>(memoryAddress + 0x134);
        int playerTeamNum       = mem->read<int>(memoryAddress + 0x128);

        if (playerTeamNum == iTeamNum || playerTeamNum == 0) {
            continue;
        }
        
        if (playerTeamNum == 0) {
            continue;
        }

        if (health == 0) {
            health = 100;`

**Comment by ghost** [comment]
No, I mean I don't know how to get the correct structs. I've been searching Github and the web, and the people who know how to update the structs for mac are @gabsens and @aKalisch . @gabsens 's pattern scanner is outdated due to the update, and I couldn't find any explanation of how @aKalisch updated the structs in csgoGlow before. (I wonder if I @ spam them more we will get rescued?)

Is @p0hjan still alive? All discord links expired :(


GO:SX Lite is dead, Thor and pHook are a paid mess, vange.me and Patanjali-Hax broke with the update. Open source hacks seem to be dying :(

inb4 someone public ports indigo and volvo add VAC module to osx

**Comment by ghost** [comment]
I tried replacing all outdated offsets I could find with offsets from hazedump, didn't work for me.

If replacing GlowIndex, Health, and TeamNum work for you, please let me know. But I think the broken signatures are a problem as well.

I mean this part in main.cpp: 

<img width="725" alt="plsfix" src="https://user-images.githubusercontent.com/40918689/42429418-d7855c56-8373-11e8-9380-fd77d29283bc.png">

**Comment by diogosilva212** [comment]
Nop, bro. It didn't work for me.

**Comment by diogosilva212** [comment]
hazedump doesn't have those signatures?

**Comment by ghost** [comment]
I tried the sigs on hazedump, but I either used the wrong ones or it doesn't work. Try it yourself, tell us if it does work :D

My thought is that it's the LocalPlayerBase, playerBase, and glowInfoOffset. @aKalisch updated it before: 8e7818e but didn't say how.

**Comment by diogosilva212** [comment]
So... What can we do?

In which file are the sigs?

**Comment by ghost** [comment]
I tried to find how he did it, but I couldn't. I'm just waiting for him now, but if you can find it and send it to me or update the hack yourself, it would be amazing! But I'm not an expert on c++, so honestly, it's really down to whether an expert wants to update it or not.

**Comment by diogosilva212** [comment]
What I know about this is what I'm learning from searching since the hack stopped working ahah Don't know what I can do... :(

**Comment by diogosilva212** [comment]
@aKalisch @gabsens be our superheroes, please!

**Comment by ghost** [comment]
Ok, apparently there is a tutorial out there. I know that gabsens uploaded tutorials where you find the offsets using bitslicer, but not the sigs. (_90% sure he has a yt channel called h4ck314 btw_)

**Comment by diogosilva212** [comment]
Yes, I saw the video of pattern scanner, but you said it doesn't work now. And what he does in the video doesn't come on the main.cpp. `uint64_t glowInfoOffset;
uint64_t LocalPlayerBase;
uint64_t playerBase;`

I don't have values on that. You have?

Where's the tutorial?

**Comment by ghost** [comment]
I don't have the values, I don't know where the tutorial is. If I did I would have fixed it :P

Outdated tutorial on how to update offsets just fyi: https://github.com/iseekwonderful/csgoGlow/issues/43

iseekwonderful posted his email: https://github.com/iseekwonderful/csgoGlow/issues/196?

Here's a thread I don't even understand with his skype at the end: https://github.com/iseekwonderful/csgoGlow/issues/166


Apparently there's a Wiki I can't find: https://github.com/iseekwonderful/csgoGlow/issues/146

Edit: found the wiki, it's not very useful: https://github.com/iseekwonderful/csgoGlow/wiki/macOS-Memory-Patterns-for-CS:GO

I'll delete this contact stuff as soon as we get something done (or admin may just delete it for me ;), I just want to figure out how to fix this app.

**Comment by ghost** [comment]
Still nothing on how to update sigs or even what's wrong. I officially have no idea what I'm doing :)

**Comment by diogosilva212** [comment]
The thing about those values is: I'm using this cheat for an year, and I didn't had any values on `uint64_t glowInfoOffset; uint64_t LocalPlayerBase; uint64_t playerBase;`. It was just like that. So I think we don't need to have values on that. We just need to update sigs...

**Comment by ghost** [comment]
Yeah, there's a pattern scanner that updates them after each CS:GO update.

But the sigs are broken, and I don't know how to fix them. Any ideas?

**Comment by diogosilva212** [comment]
I really don't know. I sent an e-mail to @iseekwonderful...

**Comment by ghost** [comment]
Thanks :) I'll keep searching and posting in this issue, then.

**Comment by diogosilva212** [comment]
I'm so sad. This hack was so flawless :(

**Comment by ghost** [comment]
Yeah, it was really nice. I really hope it gets updated.

**Comment by gabsens** [comment]
I don't have the game anymore on my machine, but OSX structs used to be identical to Linux structs, so if they changed you should be able to find the new ones by looking [here](https://www.unknowncheats.me/forum/counterstrike-global-offensive/103220-global-offensive-structs-offsets.html)

Once you have them, you can use the methods developed in my videos to grab the newest offsets. Finding patterns is not easy though

**Comment by ghost** [comment]
YES SOMEONE WHO KNOWS WHAT THEY'RE DOING THANK YOU

I tried using as many structs as I could from the UC forum, didn't work for me :(

I've got a boatload of stupid questions because I've tried learning this purely from UC and closed issues:

Can we use hazedumper offsets?
How do we check which offsets are outdated?
Is there any way/tutorial/ to update the pattern scanner itself instead of the offsets?

pls help v2

**Comment by ghost** [comment]
Shit, no wonder I'm so confused. Valve hit us with a 5mb update. Before that it was only GlowIndex that was changed, so no fix to the patterns. But no clue what happened after the update it seems :(

Screw it, maybe @rpranshu will fix it.

**Comment by aKalisch** [comment]
How can you guys say that the sigs are broken when you don't even have a clue how to get the pointers yourself.

**Comment by ghost** [comment]
Because we don't know much about coding source, but we want to learn so we can help update this cheat faster, and broken sigs was my best guess :D

edit: I am a literal idiot

**Comment by aKalisch** [comment]
@gabsens got Tutorials on Youtube that are working fine.

**Comment by diogosilva212** [comment]
It's working!!!

**Comment by mattyj5934** [comment]
Do i just start up like i always do or do i download it again? how did it
work

**Comment by diogosilva212** [comment]
I downloaded it again.

**Comment by rpranshu** [comment]
Any updates, is it working now?

**Comment by mattyj5934** [comment]
Yes just redownload it and it will work

**Comment by ningwang747** [comment]
#240 fixed

**Comment by aKalisch** [comment]
7250f778721582bd2680d4009161e61df5f8abf7
Fixed!
