### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by manigamer22** [iseekwonderful/csgoGlow#239]
Well i downloaded the new one and build it and when i inject it its still not working like the enemies dont even glow plz fix.

**Comment by KaboomXD** [comment]
@manigamer22 There has been a new update. Therefore new GlowOffsets and GlowInfoIndex need to be input. Hopefully someone fixes it soon.

**Comment by manigamer22** [comment]
ok when will it be fixed because phook is getting fixed when pwned comes back from japan.

**Comment by ghost** [comment]
We don't know. If you want to use phook then do it, nobody is forcing you to use this hack. Also, there is already an issue opened about this.

@KaboomXD According to hazedumper new iGlowIndex is 0xA320, we just need the new pointers. If you can get them then please post so we can update.

lmao I'm stupid

**Comment by KaboomXD** [comment]
@Shadesprite Will try my best in finding them. Found the iGlowIndex at haze bumper swell and we showed the change. You can view it in the Pull Request tab. Not sure where to find the pointers but I will search the internet and the game files.

**Comment by ghost** [comment]
@KaboomXD Check the thread before this one, we are trying our best :b

**Comment by aKalisch** [comment]
Hazedumper is a Windows dumper. The Offsets will differ from mac.
GlowIndex is now 0xAC00 (m_flFlashDuration + 0x18)

**Comment by ghost** [comment]
YOU ARE LITERAL GOD

**Comment by aKalisch** [comment]
Maybe I am. Maybe not. But I just learned my knowledge from UC. Everyone can if you put some effort into that stuff.

I can't say when I find time to update csgoGlow.
One hack currently working on mac is [GO:SX](https://www.gosx.one)

**Comment by ningwang747** [comment]
@aKalisch thank you :)

**Comment by manigamer22** [comment]
well mac pub, gosx and thor are working

**Comment by KaboomXD** [comment]
@aKalisch Bro legit bless up, I went to my local Technical University to try finding the iGlowIndex hahahah

**Comment by rpranshu** [comment]
@manigamer22 can u share the said resources?

**Comment by manigamer22** [comment]
gosx is paid cheat, mac pub is paid rage, thor is paid rage so

**Comment by rpranshu** [comment]
Any updates? Is this working now?

**Comment by manigamer22** [comment]
well no mate pwned is updating it today

**Comment by ningwang747** [comment]
#240 fixed I guess @manigamer22

**Comment by aKalisch** [comment]
7250f778721582bd2680d4009161e61df5f8abf7
Fixed!
