### ISSUE TITLE
Panorama for everyone

### ISSUE THREAD

**Issue by diogosilva212** [iseekwonderful/csgoGlow#241]
Hello, with the Panorama available for everyone, it stopped working again (at least for me). Anyone?

**Comment by MKBlazeV** [comment]
Yep for me too :/

**Comment by diogosilva212** [comment]
@aKalisch please, our savior.

**Comment by aKalisch** [comment]
put `-scaleform` in your csgo launch options

**Comment by rpranshu** [comment]
```-scaleform``` is a temporary transition, it will be discontinued after some time! @aKalisch and @everyone!

**Comment by aKalisch** [comment]
@rpranshu I know this. csgoGlow needs to be updated to new panorama implementation (`client_panorama.dylib`).
Everything else should just work fine.

**Comment by davidson4561** [comment]
@aKalisch will you please update the hack sooner or later?

**Comment by aKalisch** [comment]
@davidson4561 That can be done by everyone. Just replace "`client.dylib`" with "`client_panorama.dylib`"

**Comment by aKalisch** [comment]
Another option is to opt out the scaleform ui. Add `-scaleform` to your csgo launch options

**Comment by aKalisch** [comment]
7250f778721582bd2680d4009161e61df5f8abf7
Fixed!
