### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by diogosilva212** [iseekwonderful/csgoGlow#244]
CS got updated today, not working with panorama and with the old version (using -scaleform). Fix, @aKalisch? Please <3

**Comment by nameispanduh-zz** [comment]
walls r broken plz fix

**Comment by josephhajjar98** [comment]
up

**Comment by josephhajjar98** [comment]
CS got updated today

**Comment by diogosilva212** [comment]
New offset probably, @aKalisch?

**Comment by diogosilva212** [comment]
New glowindex, @aKalisch?

**Comment by aKalisch** [comment]
Done d6d77cedd44173804802b761286936d3f320efa4
