### ISSUE TITLE
New Update which Includes MP5-SD

### ISSUE THREAD

**Issue by KaboomXD** [iseekwonderful/csgoGlow#245]
Im not sure what is wrong but the code doesn't work when is inputted in the terminal. May someone assist me?

**Comment by diogosilva212** [comment]
It's already working. Download again and build.

**Comment by manigamer22** [comment]
If this hack doesn't work sometimes try using the microwave free esp cheat - https://www.youtube.com/watch?v=hFfRWN8xaIk
