### ISSUE TITLE
Using Scaleform in Newest Update (With New MP5-S)

### ISSUE THREAD

**Issue by useking** [iseekwonderful/csgoGlow#247]
I tried with the panorama that the hack works, but I don't like the panorama ui and I want to use the scaleform mode using -legacyscaleformui.

Unfortunately the hack doesn't work using the scaleform ui.

**Comment by manigamer22** [comment]
mate you have to change the /client_panorama.dylib to /client.dylib then it will work for -legacyscaleformui.

**Comment by aKalisch** [comment]
scaleform has been removed completly. There is no way to force it.
