### ISSUE TITLE
CS:GO Update Killled csgoGlow

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#25]
Counter-Strike: Global Offensive update for 5/19/16 (5/20/16 UTC, 1.35.3.4) has rendered this mod useless. The console says there is an issue with the memory addresses, which I believe the update changed. I'm sure this is a simple fix,but I have no idea how to fix this however. If this gets working again, it would be awesome!

**Comment by iseekwonderful** [comment]
i will fix this when I arrived home tonight

**Comment by ghost** [comment]
iseek your work is incredible. The hack worked flawlessly for three weeks on several of my accounts. I genuinely appreciate the time you have spent developing this. Thank you.

**Comment by iseekwonderful** [comment]
fixed
