### ISSUE TITLE
Not working after today October 9 update

### ISSUE THREAD

**Issue by xcpz** [iseekwonderful/csgoGlow#255]

**Comment by D3k3k** [comment]
Yes! waiting for a new update

**Comment by useking** [comment]
yeah

**Comment by diogosilva1910** [comment]
@aKalisch help a brother out

**Comment by p4ulinely** [comment]
guys, just changed _m_iGlowIndex_ variable to **0xAC20**

**Comment by randomuser123123** [comment]
@paulinelymorgan care to explain in more detail?

**Comment by useking** [comment]
still not working

**Comment by p4ulinely** [comment]
open the file Wall.xcodeproj. select main.cpp file. search for variable _uint64_t m_iGlowIndex_ then assign 0xAC20 to it. u will need to rebuild...

**Comment by useking** [comment]
that works, thank you
how did you know what to change?

**Comment by p4ulinely** [comment]
@useking in fact, I saw the last 3 changes. realized the variable was being incremented by 16 (in hexadecimal)... then I gave a shot =P
