### ISSUE TITLE
Not working for me in mac os high sierra

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#259]
Found CSGO PID: 2274
Found the Client.dylib address: 0x12034c000 
Module should end at 0x1217ae924

anybody know what i have to do to fix it

**Comment by itsfrank115** [comment]
fam i got it change line 42 to 0xAC34 if u on mac

**Comment by mesutoz** [comment]
https://github.com/iseekwonderful/csgoGlow/issues/258#issuecomment-433750977
I did them and tried to update the mojave
