### ISSUE TITLE
CS:GO Update Killled csgoGlow

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#26]
New update has made csgo 64 bit. Does this kill the hack entirely, as in, does the code need to be complete rewritten? Or is there a simple fix?

**Comment by Freek3** [comment]
csgoglow: The pid is 24475
faildNo root permission
Please run it with root
Program ended with exit code: 0

help??

**Comment by iseekwonderful** [comment]
this should take some time to go to 64bit, also amazing! valve finally make it to 64 bit!

**Comment by iseekwonderful** [comment]
could anyone tell me that if windows now 64bit or already in 64bit?

**Comment by ThaddyBear** [comment]
it says csgo_osx64

**Comment by Yakultie** [comment]
I read on reddit there's a launch option to set CS:GO to 32 bit (but probably for Windows only), it's:
`-32bit`
You can enter it in "Launch Options" after right clicking the game in Steam Library and selecting "Properties".
But still: same error appears.

**Comment by Yakultie** [comment]
Very well played, Steam and Valve. _clap clap_

**Comment by iseekwonderful** [comment]
by entering -32bit I still launch csgo_osx64

**Comment by ghost** [comment]
Is there any way to revert to an older version of cs:go?

**Comment by ghost** [comment]
so is the hack not working at this time? will there ever be a fix?

**Comment by Freek3** [comment]
will there be a fix? and if so, when?

**Comment by iseekwonderful** [comment]
there will be but i dont know when it will come...

**Comment by Freek3** [comment]
thanks, ily and good luck with the fix <3

**Comment by ghost** [comment]
Someone should try to find a way to run 32 bit csgo.

**Comment by ghost** [comment]
Do u have a set date of when it will be fixed?

**Comment by ghost** [comment]
Just got the hack to work, and now this is happening :/

**Comment by e-retailer** [comment]
Can i be the one that makes you sad people smile again?

Here is the solution:
1. Download older version: Library->CSGO Properties->BETA tab->Choose: 13532
2. Copy the 32bit executable to a temp folder
3. Revert the 1st step: Library->CSGO Properties->BETA tab->Choose: NONE
4. Copy the 32bit executable to the game dir
5. Open csgo.sh in the game dir
6. Change csgo_mac64 to csgo_mac
7. Launch the game

Cheers!

**Comment by ghost** [comment]
Ily <3

**Comment by ThaddyBear** [comment]
what is the 32 bit executable

**Comment by e-retailer** [comment]
csgo_mac

**Comment by ThaddyBear** [comment]
i don't see cogs_mac

**Comment by ThaddyBear** [comment]
is it csgo_osx?

**Comment by e-retailer** [comment]
yes, sorry

**Comment by e-retailer** [comment]
I've updated my comment

**Comment by ThaddyBear** [comment]
dude ur a genius fucker

**Comment by brendon111** [comment]
where do i find the 32bit executable and also where do i find the game dir?

**Comment by brendon111** [comment]
i found 32bit executable and is that the game dir? with bin, chrome.pak,
csgo, ect. i tried opening csgo.sh and all i get is a bunch of scripts.
please help, im desperate,

**Comment by brendon111** [comment]
I'm stuck on 4./5. Where Tf do I find game dir.

**Comment by ghost** [comment]
please if you could just make a video tutorial and send it to my email,
brendonmillington11@gmail.com

**Comment by e-retailer** [comment]
Add me on steam, then we'll talk: [http://steamcommunity.com/id/hardfacenl/](url)

**Comment by ghost** [comment]
Added you

**Comment by ghost** [comment]
I'm Yung Mac God

**Comment by ghost** [comment]
Still haven't added me.

**Comment by Freek3** [comment]
e-retailer you fucking legend, thank you so much mate!

**Comment by ghost** [comment]
I still don't have it working :(

**Comment by ThaddyBear** [comment]
i cannot connect to any game if i change to the 32 bit, it was working initially but after the recent update i cannot connect anymore.

**Comment by ThaddyBear** [comment]
it says server uses different class tables :/

**Comment by Freek3** [comment]
Same :(

**Comment by ghost** [comment]
@e-retailer I did everything in your instructions and when I run it in game I get 
The pid is 2107
Ect ect

**Comment by ghost** [comment]
Someon who got it to work, please help me

**Comment by ghost** [comment]
And when I try to play a online game, I get Disconnected, Server uses different class tables. Before I was just playing  bots and the glow would even work to begin within

**Comment by ghost** [comment]
Anybody have this currently working?

**Comment by jananne** [comment]
There is NO fix. Just wait until the next update.

**Comment by ghost** [comment]
Is @iseekwonderful even there anymore? I haven't seen him comment in awhile.

**Comment by jananne** [comment]
If there is no info to update you with, why should he bother commenting. Have patience.

**Comment by iseekwonderful** [comment]
so sorry for 2 busy
so finally~ hello world 64bit csgo!
