### ISSUE TITLE
not working mac os sierra

### ISSUE THREAD

**Issue by ph1losof** [iseekwonderful/csgoGlow#261]
not working mac os sierra cant see throw walls

**Comment by etan8225** [comment]
change the 42nd line in main.cpp from "uint64_t m_iGlowIndex       = 0xAC10;" to "uint64_t m_iGlowIndex       = 0xAC34". That should be it.

**Comment by ethano8225** [comment]
change the 42nd line in main.cpp from `uint64_t m_iGlowIndex = 0xAC10` to `uint64_t m_iGlowIndex = 0xAC34` That should be it.

**Comment by ph1losof** [comment]
thak you very much
