### ISSUE TITLE
GlowEsp show team 

### ISSUE THREAD

**Issue by jefcostaa** [iseekwonderful/csgoGlow#265]
if (playerTeamNum == iTeamNum) {
        Color color {(0 / 255), (255 / 255), (255 / 255), 0.5f};
        applyGlowEffect(task, startAddress, glowIndex, color);
        continue;
    }
    if (playerTeamNum == 0) {
        continue;
    }

this was the code used for the hack to work with the team itself, but now it is not working anymore, could someone tell me a new code to use?

**Comment by diogosilva212** [comment]
Where did u get the m_iglowindex?

**Comment by jefcostaa** [comment]
https://github.com/iseekwonderful/csgoGlow/issues/147

**Comment by diogosilva212** [comment]
Not talking about that. You said that the new m_iglowindex was "0xAC38", where did u find that?

**Comment by jefcostaa** [comment]
because of the last update, the guy I used on the PC used 0xA3F4, and on Mac is a 0xAC34, so I posted that the new one could probably be 0xAC38 because the friend said that on the PC it is 0xA3F8

**Comment by diogosilva212** [comment]
It's not working bro

**Comment by ghost** [comment]
0xAC38 isn't working for me tho. any idea of what i should do?
