### ISSUE TITLE
How do i run them?

### ISSUE THREAD

**Issue by extrenebiibues** [iseekwonderful/csgoGlow#27]
i run them and it says it was successful or something but no walls? is this cuz of 64bit update? Can you give us a tutorial

**Comment by ghost** [comment]
Ill make a tutorial on youtube if @iseekwonderful doesn't mind. There are a few loopholes you have to get through now. The 64 update makes the walls not work, but you can revert to 32 bit easily.

**Comment by ghost** [comment]
@tr1kyyy do you mind if you put the video unlisted and then post the link of the video on this issue, so not many other people see it, because if it's public it could go viral.

**Comment by extrenebiibues** [comment]
just do whatever please i need this asap and so many people will benefit

**Comment by extrenebiibues** [comment]
just post it asap loads of people want it
