### ISSUE TITLE
ESP Not Being Applied To Propper Entities

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#273]
[Screenshot Collection Link](https://imgur.com/a/Sem9xcL)

**Comment by ethano8225** [comment]
Ok 1. Try to use my “forked” version of the csgoGlow thing (same process I just edited the files to make it work [i think I mayve messed something up] THIS ONE SHOULD WORK FOR MATCHMAKING NOT BLACKOUT) just click on my profile it there, and it you are trying to get onto Blackout with the cheat use this: https://github.com/jefcostaa/csgoGlow

**Comment by ghost** [comment]
> Ok 1. Try to use my “forked” version of the csgoGlow thing (same process I just edited the files to make it work [i think I mayve messed something up] THIS ONE SHOULD WORK FOR MATCHMAKING NOT BLACKOUT) just click on my profile it there, and it you are trying to get onto Blackout with the cheat use this: https://github.com/jefcostaa/csgoGlow

I tried using it in MM and i did `sudo -s` and all that jazz but now instead of glowing random masses it dosent do anything, I dont know what to do anymore...

**Comment by ethano8225** [comment]
alright idk, I’ll link you (tommorow) to 2 working versions of the match making and the blackout versions, as I know mine works. Could you be on Mojave? You have to fix some settings if you are. (Also as an easier way to inject all you have to do is type `sudo (insert file)` and hit enter and type in your password. It’s only 1 step and not 2 (easier lol)

**Comment by ghost** [comment]
> alright idk, I’ll link you (tommorow) to 2 working versions of the match making and the blackout versions, as I know mine works. Could you be on Mojave? You have to fix some settings if you are. (Also as an easier way to inject all you have to do is type `sudo (insert file)` and hit enter and type in your password. It’s only 1 step and not 2 (easier lol)

Yeah, I am on Mojave, is there a known compatibility issue?

**Comment by ethano8225** [comment]
yes   you have to enable terminal/ the csgoGlow program to control ur computer-- go into preferences, and security and privacy. under privacy (in accessibility). you have to hit the add button and add csgoGlow as one of the things that can do it (that's at least what I see in non-Mojave, you may have to look at some archived threads back in like June talking about this problem if that doesn't work.)

if its the actual file that is bad, here (working MM and Battle royale files;

https://drive.google.com/drive/u/0/folders/1UHLmxLMypL3xdtY5b7kuQU7CDmfyHK5-

**Comment by ethano8225** [comment]
@AlexanderAryaAlikhani it did work right?

**Comment by 7475** [comment]
I got vacced!!!!! DO NOT USE THIS!!




Just kidding :D  I had it sorted before the first reply :D   Fuck Mojave :D .  Happy games everyone!

**Comment by ghost** [comment]
> @AlexanderAryaAlikhani it did work right?

Sorry for the late response, yeah after a bit of `chmod` magic I got it to work, Im now wondering why the precompiled version works and not the versions I compiled on mojave

**Comment by KaboomXD** [comment]
Happy New Year everyone!! 
@AlexanderAryaAlikhani how did you get it to work? Can you send me the working code? Cant really understand what's going on.

**Comment by shaikhabrez** [comment]
yeah it's working on Mojave after you need to add csglow in the accessibility under privacy at system preferences

**Comment by KaboomXD** [comment]
@shaikhabrez aight bro, thanks a lot.
