### ISSUE TITLE
Not working anymore 

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#29]
Not working for me anymore at the time of this post. Anyone else having a problem?

**Comment by ghost** [comment]
Anyone?

**Comment by Freek3** [comment]
yeah

**Comment by ghost** [comment]
I think it's outdate offsets and needs an update.

**Comment by Galenika** [comment]
yes doesnt work .. damn :(

**Comment by ghost** [comment]
Pull the changes from the master branch. Everything is working once again thanks to @gabsens :)
