### ISSUE TITLE
If you want an amazing mac hack with not only walls but amazing HvH capabilities as well as legit aimbot check out this project https://github.com/recoiil/csgo-mac-hack

### ISSUE THREAD

**Issue by recoiil** [iseekwonderful/csgoGlow#293]
https://github.com/recoiil/csgo-mac-hack

**Comment by amcgregor** [comment]
In case anyone can possibly be this gullible (and I'm very sorry if you are), but a repository that is just a ZIP file can not possibly be trusted.  Expect malware; virus or trojan.

**Comment by recoiil** [comment]
> In case anyone can possibly be this gullible (and I'm very sorry if you are), but a repository that is just a ZIP file can not possibly be trusted. Expect malware; virus or trojan. (Beyond this being blatantly obvious spam.)

bro check it out first do you want source code? its not malware

**Comment by recoiil** [comment]
> In case anyone can possibly be this gullible (and I'm very sorry if you are), but a repository that is just a ZIP file can not possibly be trusted. Expect malware; virus or trojan. (Beyond this being blatantly obvious spam.)

there retard go check it out i added source its not a virus

**Comment by amcgregor** [comment]
I've done a partial decompile.  It's yet another "private fork" of `gosx`.  Built on a machine by a user running with the username `timothydillan`.  Literally a path from the un-stripped symbol metadata:

```
/Users/timothydillan/Downloads/GO-SX-Internal-Lite-master/osxinj/
```

Didn't even move it out of your Downloads folder.  Yeesh.  If you're going to steal, have some pride, man.  Also includes several copyrighted fonts.  (Smallest Pixel: free for personal use—**not redistribution**.  Segoe UI—proprietary Microsoft font, not distributed independent of Microsoft products.  Consolas, similar Microsoft property.)

I mean, given GitHub is now a Microsoft property, too, this is pretty ballsy.

**Comment by recoiil** [comment]
> I've done a partial decompile. It's yet another "private fork" of `gosx`. Built on a machine by a user running with the username `timothydillan`. Literally a path from the un-stripped symbol metadata:
> 
> ```
> /Users/timothydillan/Downloads/GO-SX-Internal-Lite-master/osxinj/
> ```
> 
> Didn't even move it out of your Downloads folder. Yeesh. If you're going to steal, have some pride, man. Also includes several copyrighted fonts. (Smallest Pixel: free for personal use—**not redistribution**. Segoe UI—proprietary Microsoft font, not distributed independent of Microsoft products. Consolas, similar Microsoft property.)
> 
> I mean, given GitHub is now a Microsoft property, too, this is pretty ballsy.

at least its not a virus lol its a real amazing hack

**Comment by recoiil** [comment]
> I've done a partial decompile. It's yet another "private fork" of `gosx`. Built on a machine by a user running with the username `timothydillan`. Literally a path from the un-stripped symbol metadata:
> 
> ```
> /Users/timothydillan/Downloads/GO-SX-Internal-Lite-master/osxinj/
> ```
> 
> Didn't even move it out of your Downloads folder. Yeesh. If you're going to steal, have some pride, man. Also includes several copyrighted fonts. (Smallest Pixel: free for personal use—**not redistribution**. Segoe UI—proprietary Microsoft font, not distributed independent of Microsoft products. Consolas, similar Microsoft property.)
> 
> I mean, given GitHub is now a Microsoft property, too, this is pretty ballsy.
> 
> [Edited to add: ah, and even more shady, the original upload was a password-protected DMG disk image.]

i made the password protected disk image pass is: delirious2539

**Comment by recoiil** [comment]
> I've done a partial decompile. It's yet another "private fork" of `gosx`. Built on a machine by a user running with the username `timothydillan`. Literally a path from the un-stripped symbol metadata:
> 
> ```
> /Users/timothydillan/Downloads/GO-SX-Internal-Lite-master/osxinj/
> ```
> 
> Didn't even move it out of your Downloads folder. Yeesh. If you're going to steal, have some pride, man. Also includes several copyrighted fonts. (Smallest Pixel: free for personal use—**not redistribution**. Segoe UI—proprietary Microsoft font, not distributed independent of Microsoft products. Consolas, similar Microsoft property.)
> 
> I mean, given GitHub is now a Microsoft property, too, this is pretty ballsy.
> 
> [Edited to add: ah, and even more shady, the original upload was a password-protected DMG disk image.]

i was originally going to give out my cyanide config as well but figured its not worth it since killers is way better in every way

**Comment by amcgregor** [comment]
> at least its not a virus lol its a real amazing hack

You mistake not mentioning something for confirmation of its lack of existence.  I didn't mention God.  QED, God doesn't exist.  Welp, made that existential question easy.

Casually browsing the easily decoded strings identifying your laziness and lack of self-preservation skills re: potentially revealing personal information does not mean I have vetted it extensively for malicious code.  I have not.  You couldn't pay me to do so when it's so trivial to look up a real, honest fork of gosx instead.  Do you even x64 assembly, bro?

But yeah, I'm done here.  Best o' luck t'ya.

**Comment by recoiil** [comment]
> > at least its not a virus lol its a real amazing hack
> 
> You mistake not mentioning something for confirmation of its lack of existence. I didn't mention God. QED, God doesn't exist. Welp, made that existential question easy.
> 
> Casually browsing the easily decoded strings identifying your laziness and lack of self-preservation skills re: potentially revealing personal information does not mean I have vetted it extensively for malicious code. I have not. You couldn't pay me to do so when it's so trivial to look up a real, honest fork of gosx instead. Do you even x64 assembly, bro?
> 
> But yeah, I'm done here. Best o' luck t'ya.

first off wtf does any of that mean lol anyways heres a great hack that even this fucking super geek nerd agrees is in fact an amazing hack so go use it

**Comment by amcgregor** [comment]
Well, then.  I literally couldn't hit "unsubscribe" fast enough.

[You call this “source code”?](https://github.com/recoiil/csgo-mac-hack/commit/76470d178b334e05a28aca974bb2c9c011782007)

That's just touching the files and running `git commit -a -m 'source code'`.  This unfolding chain of events is so stupid I'm adding it to the pile with [Manos: The Hands of Fate](https://www.imdb.com/title/tt0060666/) and [Garth Marenghi's Darkplace](https://www.imdb.com/title/tt0397150/?ref_=nv_sr_srsg_0).  Just not as charmingly quirky as the former, or as intentional as the latter.

If you're somehow at all serious about this, I feel great sympathy for your legal guardian.  But you must be trolling.  Thank you for a highlight to my evening's entertainment.

**Comment by recoiil** [comment]
> Well, then. I literally couldn't hit "unsubscribe" fast enough.
> 
> [You call this “source code”?](https://github.com/recoiil/csgo-mac-hack/commit/76470d178b334e05a28aca974bb2c9c011782007)
> 
> That's just touching the files and running `git commit -a -m 'source code'`. This unfolding chain of events is so stupid I'm adding it to the pile with [Manos: The Hands of Fate](https://www.imdb.com/title/tt0060666/) and [Garth Marenghi's Darkplace](https://www.imdb.com/title/tt0397150/?ref_=nv_sr_srsg_0). Just not as charmingly quirky as the former, or as intentional as the latter.
> 
> If you're somehow at all serious about this, I feel great sympathy for your legal guardian. But you must be trolling. Thank you for a highlight to my evening's entertainment.

bet nigga

**Comment by recoiil** [comment]
> > at least its not a virus lol its a real amazing hack
> 
> You mistake not mentioning something for confirmation of its lack of existence. I didn't mention God. QED, God doesn't exist. Welp, made that existential question easy.
> 
> Casually browsing the easily decoded strings identifying your laziness and lack of self-preservation skills re: potentially revealing personal information does not mean I have vetted it extensively for malicious code. I have not. You couldn't pay me to do so when it's so trivial to look up a real, honest fork of gosx instead. Do you even x64 assembly, bro?
> 
> But yeah, I'm done here. Best o' luck t'ya.

add me on discord: ✥アレックス✥#3272
