### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by jakobe15** [iseekwonderful/csgoGlow#298]
All it writes in terminal is:
Found the client_panorama.dylib address: 0x0
Module should end at 0x0 and the glow doesnt pop up ingame

**Comment by Fricker95** [comment]
change line: 105
`g_cProc->getModule(mainTask, &moduleStartAddress, &moduleLength, "/client_panorama.dylib");`
to
`g_cProc->getModule(mainTask, &moduleStartAddress, &moduleLength, "/client.dylib");`

**Comment by Fricker95** [comment]
also still need to change:
line 62:
`int health              = mem->read<int>(memoryAddress + 0x134);`
to
`int health              = mem->read<int>(memoryAddress + 0x138);`

and 

line 63:
`int playerTeamNum       = mem->read<int>(memoryAddress + 0x128);`
to
`int playerTeamNum       = mem->read<int>(memoryAddress + 0x12C);`

and 

line 42:
`uint64_t m_iGlowIndex       = 0xAC10;`
to
`uint64_t m_iGlowIndex       = 0xAD48;`

**Comment by jakobe15** [comment]
I changed these but it still says the same thing in terminal and doesn’t work

**Comment by jakobe15** [comment]
@Fricker95 it also used to work but it stopped working today

**Comment by Fricker95** [comment]
« grant the application being run the correct permissions under System Preferences → Security & Privacy → Automation. Not Terminal.app and everything ever run within, add just the Wall binary. This particular grant covers the need for one program to read or write to another program's memory. See my previous comment pointing all this out. (Easily found back by searching the issues for "security & privacy".) Also mentioned in other threads. Though I will admit, a depressing number of those threads give up on any from of system security by granting, pretty much, everything and the kitchen sink complete access to the system. (Don't drag in Terminal into that! Only the Wall binary!)« 

From thread #291

**Comment by Fricker95** [comment]
0x0 mean nullptr (NULL in C), this could mean your not using 
`sudo -s;
./Wall`
in terminal

**Comment by Fricker95** [comment]
Also line 145:
`int i_teamNum = mem->read<int>(playerAddress + 0x128);`
to
`int i_teamNum = mem->read<int>(playerAddress + 0x12C);`

**Comment by Fricker95** [comment]
I forked this project with my edited version of it:

[https://github.com/Fricker95/csgoGlow.git](url)

**Comment by jakobe15** [comment]
> I forked this project with my edited version of it:
> 
> [https://github.com/Fricker95/csgoGlow.git](url)

Thank you! It works perfectly now and feels much smoother with ur version.

**Comment by xcpz** [comment]
were the offset changed again?

**Comment by Fmostkill** [comment]
@Fricker95 Any idea about the new update changes?
