### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by sergey-zero** [iseekwonderful/csgoGlow#3]
WOW! Super, but not working for me :(
How i can help you to fix this?

> The pid is 1198
> [Gaben:WTF]
> glow loop address is 0xbffff8e8----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------
> ----------updated----------

**Comment by iseekwonderful** [comment]
run with root
$ sudo -s

# ./External

**Comment by sergey-zero** [comment]
ty working perfect
