### ISSUE TITLE
Tutorial: updating offsets

### ISSUE THREAD

**Issue by gabsens** [iseekwonderful/csgoGlow#33]
Here you go:

Finding LocalPlayer offset https://www.youtube.com/watch?v=Uv5tJXA04zU
This is the offset referenced as `LocalPlayerBase` in the source 

Finding Glow offset https://www.youtube.com/watch?v=3HhD7WNzSno

Please Label this issue with **Enhancement** or **Help Wanted**

**Comment by Freek3** [comment]
Thanks babe

**Comment by ghost** [comment]
@gabsens so does this mean you will no longer updating offsets on github?

**Comment by gabsens** [comment]
@brendon111 the method to update offsets is now public knowledge, so why should I bother ?

**Comment by ThaddyBear** [comment]
pls help us also :DD

**Comment by ThaddyBear** [comment]
@gabsens

**Comment by ghost** [comment]
@gabsens well this might sound embarrassing, but I can't really update the offsets. I play on a family i Mac and my mom has restrictions on it. Basically when I try to download bit slycer it asks for administrator username and password. I don't know this and my mom won't tell me and I already tried to convince her to download it for me but she won't. The only reason I have steam and xCode downloaded is because I knew what the username and password was before but she changed it

**Comment by flipembois** [comment]
@brendon111 @ThaddyBear 
These are the updated offsets, just copy it into your main.cpp code
Glow Offset = 0x59472C0;
Local Player Offset = 0x51379F8;

**Comment by ghost** [comment]
Yeah ik, these are the current ones.. @flipmebois

**Comment by ghost** [comment]
There has been a new update, please someone come in clutch. I'm begging you @flipembois @gabsens

**Comment by ghost** [comment]
i'm hopeless

**Comment by ThaddyBear** [comment]
@gabsens

**Comment by ghost** [comment]
@flipembois I havent had a chance to see if I can get the offsets, have you managed to get tonights updates?

**Comment by Freek3** [comment]
When is this update coming :)

**Comment by gabsens** [comment]
LocalPlayerBase 0x5138BA8

Glow 0x5948470

I won't be posting offsets in the future as it completely defeats the purpose of the tutorials I spent time working on.

**Comment by ghost** [comment]
@gabsens Thats completely understandable! Thanks again for doing this. Also, great job on those tutorials.

**Comment by ghost** [comment]
Thanks @gabsens and like @buzzel said it's completely understandable.

**Comment by Freek3** [comment]
@gabsens Thanks mate, all good 👍

**Comment by Freek3** [comment]
Will there be a file update? I'm having problems inserting the offsets :(

**Comment by carsonoreilly** [comment]
anyone get the new offsets yet, a new update just game out and i tried to follow the youtube vid but it didnt work for me.
