### ISSUE TITLE
Debugger keeps coming up

### ISSUE THREAD

**Issue by K2QGIT** [iseekwonderful/csgoGlow#36]
I Dont know if this is happening for everyone, but X-code will run fine for about 30 seconds then it will come up with the debugger and 10-20 lines needed to be fixed. Thanks to everyone on this discussion for previous help aswell.

**Comment by gabsens** [comment]
Screenshots of the debugger output ?

**Comment by K2QGIT** [comment]
<img width="1024" alt="screen shot 2016-06-28 at 10 24 23 am" src="https://cloud.githubusercontent.com/assets/20144499/16423789/b2714282-3d1a-11e6-84ca-28ccad5d1116.png">

Comes up any time a key is pressed in game, this is beyond me.

**Comment by gabsens** [comment]
It looks like you set a breakpoint on the green line, try to remove it.

Besides, you're not supposed to run the program within Xcode. You're adding overhead from Xcode debugger when doing that. Just sudo the executable from a Terminal window.

**Comment by K2QGIT** [comment]
doesnt running it in root do the same thing? also, I never touched the code so I dont know what was changed haha

**Comment by gabsens** [comment]
Xcode takes up 600MB of RAM on my device, and the debugger is burning some CPU time.

If you have a powerful iMac, then fine. But on a MacBook like I have you can't afford that.

**Comment by ghost** [comment]
@Wolf-88 You have a breakpoint set. The little blue arrow pointing to `bool cmd = false`, right click on it and choose remove.

**Comment by flipembois** [comment]
@gabsens I play on the MacBook as well, can you tell me how to sudo the executable from a terminal window?

**Comment by ghost** [comment]
@flipembois type `sudo` then drag the compiled executable into terminal and hit enter

**Comment by flipembois** [comment]
@buzzel  what is the compiled excecutable? Sorry but I'm kind of computer stupid

**Comment by Wolf-88** [comment]
also, there was an update and the offsets need to be updated, stupid valve.
