### ISSUE TITLE
*Noob Question Beware* How to run the hack with terminal

### ISSUE THREAD

**Issue by asiano** [iseekwonderful/csgoGlow#37]
Hey guys im quite a noob to coding and hacking and i was wondering how i "create an executable and run with sudo" since xcode will degrade my fps. Is there a step by step on what to put in the command line and how to do it? Im sorry for such a basic question.

**Comment by ghost** [comment]
Build the executable in Xcode, once you do that under the products tab you'll see something called `Wall`. Right click and choose show in finder. After that, open terminal and type `sudo` then drag the executable into the terminal window. It will then look something like this: `sudo /path/to/executable/Wall` then hit return, enter your password and you're good to go. 

NOTE: I found it more effective to start this after you've joined a game and picked a team.

**Comment by asiano** [comment]
How do i build an executable?

**Comment by ghost** [comment]
Open the project in Xcode and hit Command + B

**Comment by asiano** [comment]
How do i go about building after that?

**Comment by ghost** [comment]
you would be better off running it in xCode, if you are having help still add me, https://steamcommunity.com/id/Brendxn

**Comment by asiano** [comment]
can anyone help with the terminal issue?

**Comment by ghost** [comment]
@asiano Thats it. Command + B builds the project. There isn't anything else

**Comment by asiano** [comment]
Thanks! Ive got it to work but how about using it on terminal? Do you think you can try and test it out yourself?

**Comment by ghost** [comment]
@asiano Look at my first comment above.

**Comment by asiano** [comment]
If you see my other post i cant get it to work even after the steps

**Comment by ghost** [comment]
@asiano I have used it in the past the way you are trying to. You're probably missing a step. Make sure you have CSGO running first

**Comment by asiano** [comment]
I did exactly what u said and atill no work.

**Comment by ghost** [comment]
You are doing something wrong.

**Comment by asiano** [comment]
still having trouble

**Comment by asiano** [comment]
can anyone help please. when i input "sudo/Users/asiano6996/Desktop/csglow/Wall/main.cpp" i get "-bash: sudo/Users/asiano6996/Desktop/csglow/Wall/main.cpp: No such file or directory". please help i don't know what I'm doing wrong

**Comment by ghost** [comment]
@asiano I can't tell if you're trolling or serious...

**Comment by asiano** [comment]
Im so serious i still cant get terminal to work

**Comment by ghost** [comment]
You can't run the cpp directly. Sudo needs a space after it. You need to find Wall executable in the Developer folder of xCode and run it with sudo.
