### ISSUE TITLE
Four issues? Yellow triangles?

### ISSUE THREAD

**Issue by asiano** [iseekwonderful/csgoGlow#39]
Hi i have four issues that pop up when playing the script. One says to replace "%u" with "%lu". The other one is on line 275 and says to replace %x with %llx and it doesnt even say %x. And the last two both have messages saying unsed variable. One on line 177  saying unised variable kr3 and the other one on line 321 saying unused variable g. If anyome knows how to help please do!!

**Comment by asiano** [comment]
Okay figured out the %xl stuff but i still cant seem to get the hack to work or the unused variables to be fixed. It seems that when i try to play it the map on the top right corner disappears but no glow? Any help?

**Comment by ghost** [comment]
@asiano I'll me submitting a PR in another day or two which will fix these warnings and hopefully fix the issues where the entire team would be glowed. 

Note: Warnings aren't always an issue, generally it doesnt prevent the executable from working correctly.

**Comment by ghost** [comment]
close this
