### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by coolkav2012** [iseekwonderful/csgoGlow#4]
我在“terminal”里面写了你所说的，但好像有些问题。大哥请教！
I wrote everything in terminal but i think there's a problem. pls teach !

sudo -s

cd /Users/abc/Library/Developer/Xcode/DerivedData/External-abc/Build/Products/Debug

./External

The pid is -1
[Gaben:WTF]
No root permission
Please run it with root

**Comment by iseekwonderful** [comment]
你有没有开csgo啊？

**Comment by sergey-zero** [comment]
Run cs:go first after run hack. try this command

> sudo ./External
