### ISSUE TITLE
New Offsets And It Shows Both Teams Not Just Enemy Team

### ISSUE THREAD

**Issue by carsonoreilly** [iseekwonderful/csgoGlow#40]
CSGO just had a small update and the hack isn't working for me anymore. I think there needs to be new offsets and I tried the video tutorial like 5 times and it wasnt working

**Comment by ghost** [comment]
why would you want just both teams? that just makes it so much more confusing and you might get banned from TK when playing comp because of it. It would be one thing if each team had a different color.

**Comment by carsonoreilly** [comment]
no i said it shows both teams i want just enemy team

**Comment by ghost** [comment]
New Offsets

```
uint64_t glowInfoOffset = 0x594B840;
uint64_t LocalPlayerBase = 0x513BF78;
uint64_t playerBase = 0x50B85C8;
```

Courtesy of @gabsens

**Comment by ghost** [comment]
Thanks @gabsens @buzzel and has anyone got got any advancement on the Bhop script?

**Comment by Freek3** [comment]
@brendon111 Bhop scripts are extremely risky dude.

**Comment by ghost** [comment]
@Freek3 why is that?

**Comment by gabsens** [comment]
@brendon111 bhop is extremely easy to implement, the only hurdle is managing the "space bar pressed" event in a CPU-efficient way, while maintaining accurate hops. Regarding bans, there's no VAC risk, no untrusted risk, the only way you could get busted is through Overwatch, but this would entirely be your fault.

**Comment by ghost** [comment]
@iseekwonderful usleep is still set to 100 milisecond btw...might want to change that again.

**Comment by ghost** [comment]
@gabsens I found a bhop script in c++. Could I post it here, and would you be able to suggest how to implement it with with @iseekwonderful 's way of accessing memory?

**Comment by ghost** [comment]
new update

**Comment by ghost** [comment]
Local Player Offset should be `0x513BFC8` These last two updates I have had some trouble getting the GlowOffsets. @gabsens Hows your new way coming along?

**Comment by ghost** [comment]
@brendon111 Feel free to get the glow offset

**Comment by ThaddyBear** [comment]
wow every glow offset i got doesn't work even after i updated the entity list and local player :( why is it so hard

**Comment by ghost** [comment]
@ThaddyBear I'll have a look tonight when I get home

**Comment by ghost** [comment]
@buzzel I thought I had all of them, but turns out they where all wrong, must've made a mistake.

**Comment by gabsens** [comment]
@brendon111 show me what you got I can tell you which one's wrong

**Comment by DooubleO** [comment]
@gabsens Do you have the correct/working ones?

**Comment by gabsens** [comment]
@DooubleO of course

**Comment by DooubleO** [comment]
@gabsens Will you be sharing?

**Comment by ghost** [comment]
@dooubleO They are pretty easy to grab. I kinda rushed through it last night so I might of just overlooked something. Take it slow and try again. I'll have another go when I get home.

**Comment by DooubleO** [comment]
@buzzel Let us know if you get any luck :)

**Comment by gabsens** [comment]
@DooubleO entitylist is 0x50B85E0

the rest you can find with enough motivation here https://github.com/iseekwonderful/csgoGlow/issues/33

**Comment by DooubleO** [comment]
@gabsens Ill give it a ago

**Comment by ghost** [comment]
New LocalPlayerBase should be `0x513C058` 

@gabsens For the GlowOffset, several of my offsets calculate correctly, but none work. I got `0x50F8710` and `0x50B86F8`. I haven't looked for the EntityList for this afternoons update but I've set my playerBase = LocalPlayerBase and it kills the game. What offset do I have wrong?

**Comment by ghost** [comment]
For LocalPlayerBase I found it to be `0x50A66E8`. Working on Glow rn

**Comment by e-retailer** [comment]
They don't work for me.. can you fill them in pls?

uint64_t glowInfoOffset = ...;
uint64_t LocalPlayerBase = ...;
uint64_t playerBase = ...;

**Comment by ghost** [comment]
@gabsens I'm determined on finding the offsets myself without help, but what is the difference between the LocalPlayerBase and PlayerBase?

**Comment by ghost** [comment]
@tr1kyyy playerBase is an offset to the EntityList. Its not needed persay. It just helps to determine the teams with the way that its currently implemented. 

Set both LocalPlayer and PlayerBase the same offset when testing.

**Comment by ghost** [comment]
@buzzel Okay done. After multiples time tho, I still get getting the same LocalPlayer, but it's different from yours.

**Comment by gabsens** [comment]
@tr1kyyy did you get 0x513BFC8 for the local player ? 

@buzzel offsets change very little from one update to another. the new offset I found for glow starts with 0x594B (same as the one in the previous update)

**Comment by ghost** [comment]
@tr1kyyy Roll with yours first and see if it works.

**Comment by ghost** [comment]
@gabsens I got 0x594BXXX last night, but it didnt work for me. I'll check again but I dont think I got that for todays update.

**Comment by ghost** [comment]
@gabsens I got `0x50A66E8` for LocalPlayer...is this correct?

**Comment by gabsens** [comment]
It's your your lucky day

LocalPlayer 0x513BFC8
EntityList 0x50B85E0
Glow 0x594B890

Keep a close eye on https://github.com/gabsens/Pattern-scanner-for-OSX
Tomorrow I'll release the finished code so that it fetches offsets for you.

**Comment by ghost** [comment]
@gabsens Thank you so much! I'm going to give it a go myself again anyways.

**Comment by e-retailer** [comment]
uint64_t glowInfoOffset = 0x594B890;
uint64_t LocalPlayerBase = 0x513BFC8;
uint64_t playerBase = 0x50B85E0;

Doesn't work for me :(

**Comment by ghost** [comment]
@gabsens @e-retailer They don't work for me either...

**Comment by ghost** [comment]
Do offsets differ on Windows and Mac because my friend on Windows said the glow is 0x29B4

**Comment by gabsens** [comment]
Ahem my game wasn't up-to-date, sorry (f Valve)

LocalPlayer 0x513C058
EntityList 0x50B8698
Glow 0x594B920

Pattern-scanning is OP, all offsets found in 1 second

**Comment by ghost** [comment]
@gabsens Just starred and downloaded the project :D

**Comment by ghost** [comment]
sameee :)

**Comment by ghost** [comment]
also, can someone delete all the issues, so we only have 1 open therefore its more organized.

**Comment by ghost** [comment]
Glow offsets get me every time!! LocalPlayer takes like 4 seconds

**Comment by ghost** [comment]
@gabsens Just compiled and ran your code:

`client: 0x128000000 18605964
cf
128548e2c
1285259a0
0
30`

That was my console output...

**Comment by ghost** [comment]
@tr1kyyy Yeah, it doesn't fetch the offsets yet.

**Comment by DooubleO** [comment]
Any luck anyone?

**Comment by gabsens** [comment]
It's working now

**Comment by ghost** [comment]
@gabsens You are a GOD!

**Comment by flipembois** [comment]
@tr1kyyy How did you compile it? I'm following this http://stackoverflow.com/questions/4403253/how-to-run-g-from-a-terminal-window-on-my-mac and its not working for me.

**Comment by ghost** [comment]
@flipembois 
1. Download the program, open terminal, navigate to the directory of main.cpp using `cd (Drag the folder main.cpp is in here)`. Press enter.
2. Then use `g++ main.cpp`. Press enter again.
3. In the same folder it will generate an a.out file. This is your program. To run it go to terminal and type `sudo (Drag a.out here)`
4. Note that the offsets will be in the order below

LocalPlayerBase: 0x_________
playerBase: 0x_________
glowInfoOffset: 0x_________

Did this help?

**Comment by DooubleO** [comment]
Got this message @tr1kyyy 
task_for_pid() failed with message (os/kern) failure!

**Comment by gabsens** [comment]
@DooubleO run as root. If the problem persists and you're running on OSX El Capitan, disable SIP

**Comment by DooubleO** [comment]
@gabsens Disabled SIP but still does it, not sure how to run with root.

**Comment by carsonoreilly** [comment]
@gabsens by entity list do u mean playerbase

**Comment by gabsens** [comment]
Seriously, learn the basics of Unix before you even consider hacking anything

http://askubuntu.com/questions/207466/how-to-run-applications-as-root

**Comment by carsonoreilly** [comment]
@tr1kyyy please link the bhop script

**Comment by ghost** [comment]
@DooubleO Use sudo, it will ask you for a password, but after, you will have all the privileges needed to run it. Also make sure you're in CS:GO in a sever on a team.

**Comment by ghost** [comment]
@carsonoreilly The bhop script is some old c++, and it won't work with iseekwonderful's way off accesing and reading OSX memory. I was just going to post it here in a few days to see if @gabsens could give advice regarding how to possibly convert it to OSX.

**Comment by flipembois** [comment]
@tr1kyyy It helped me create the program, unfortunately I can't turn SIP off (It can't find the command csrutil) to run the program as root.
