### ISSUE TITLE
Global Offensive structs/offsets

### ISSUE THREAD

**Issue by jananne** [iseekwonderful/csgoGlow#43]
### Posts that are not related to the things stated above, will be deleted. Please create a new issue for all other questions.

> If you feel the need to find new offsets your self, take a look at the tutorials of @gabsens on '#33 Tutorial: updating offsets'.
> 
> If you want to use the pattern scanner of @gabsens that fetches offsets, see https://github.com/gabsens/Pattern-scanner-for-OSX.
> 
> For those of you confused on how to use @gabsens pattern scanner, see 
> https://youtu.be/3kMyiZ5yuvE

**Comment by jananne** [comment]
Latest offsets, found 06/07/16 by @gabsens:
`uint64_t glowInfoOffset = 0x594B920;`
`uint64_t LocalPlayerBase = 0x513C058;`
`uint64_t playerBase = 0x50B8698;`

**Comment by ghost** [comment]
For those of you confused on how to Use @Gabsens project 
https://youtu.be/3kMyiZ5yuvE
courtesy of friend.

**Comment by ghost** [comment]
Latest offsets as of July 15th, 2016
`uint64_t glowInfoOffset = 0x594A900;`
`uint64_t LocalPlayerBase = 0x513B038;`
`uint64_t playerBase = 0x50B7678;`

**Comment by carsonoreilly** [comment]
ya i got the glow and localplayer from the scanner but it gave me the wrong playerbase? anyone know why? i followed the video tutorial

**Comment by tr1kyyy** [comment]
@carsonoreilly This is a discussion thread, no questions here. Make sure when you run @gabsens program that you are on a team in a csgo server of some sort. Also, using activity monitor, make sure there are no extra 'wall' processes running.

**Comment by sulik12345** [comment]
The Pattern scanner video went private for some reason.....

**Comment by ggothreau** [comment]
Latest offsets as of Aug 3, 2016:
uint64_t glowInfoOffset = 0x5955F00;
uint64_t LocalPlayerBase = 0x5146638;
uint64_t playerBase = 0x50C3248;

**Comment by gabsens** [comment]
@ggothreau it seems to me that the EntityList offset is rather 0x50c3228, do you confirm ?

**Comment by ggothreau** [comment]
@gabsens is it? 0x50C3248 seems to work for me. I may have found that incorrectly, though. I just took the local base and subtracted 0x833F0. I used your scanner, but not your tutorial, so I may have done that wrong, but I tested it and it seems to work.

**Comment by gabsens** [comment]
@ggothreau I see now, you added +0x20 to the one given by the pattern scanner

I see the entitylist as [MyPlayer, Bot1, Bot2,...]
You're looking at it like [Bot1, Bot2,...]

Implementation-wise, you're probably right, it makes no difference with the source on github since all it does is looping through the list, _looking for players to glow_, and you yourself isn't supposed to glow.

Sorry for doubting

Also, thanks for retrieving the glow offset, the pattern broke again, I don't know why

**Comment by gabsens** [comment]
The pattern I used previously was a tiny bit not flexible enough, damn

**Comment by ggothreau** [comment]
@gabsens I see what you mean with +0x20 making sense, since it will skip *self*, but I'd be worried it might corrupt memory by writing outside of what is allocated through entitylist, since the pointer is now offset +0x20. That was an accident though, probably a typo. But so far it seems to work and is stable.

How do you find the patterns? I wonder if regular expressions might be more flexible than string.compare()

**Comment by gabsens** [comment]
Let's continue this discussion here [here](https://github.com/gabsens/Pattern-scanner-for-OSX/issues/3) 

Is it ok if I delete all our messages (except the first one you posted) ?

**Comment by ggothreau** [comment]
@gabsens Sounds good. Sorry, I am in North America and it was very late for me so I had to sleep.

**Comment by ggothreau** [comment]
Latest offsets as of Aug 5, 2016:

```
uint64_t glowInfoOffset = 0x5958F20;
uint64_t LocalPlayerBase = 0x5149658;
uint64_t playerBase = 0x50C6228;
```

**Comment by DooubleO** [comment]
Half of the team doesn't show up help?

**Comment by ggothreau** [comment]
In testing it shows me both teams, minus one player. So something is wrong with the offsets, but I'm not sure what. I'll look into it. I used @gabsens' pattern scanner to find the new offset, so maybe he has some idea.

**Comment by DooubleO** [comment]
@ggothreau Had any luck?

**Comment by gabsens** [comment]
@ggothreau lol,this time you added +0x40 to the Entitylist offset given by the pattern scanner, hence missing players

**Comment by ggothreau** [comment]
Yeah, I was using an older version of pattern scanner. Sorry, stupid mistake!

**Comment by Commonly** [comment]
Have trouble finding the glowInfoOffset with PatternScanner can anybody help me?

**Comment by StatTrackFender** [comment]
Latest offsets as of Aug 19, 2016:

```
uint64_t glowInfoOffset = 0x595a2d0;
uint64_t LocalPlayerBase = 0x514aa08;
uint64_t playerBase = 0x50c7588;
```

**Comment by ggothreau** [comment]
Is that not working for anybody else, or is it just me?
I only see the glows briefly, when they're behind walls, and it isn't consistent (only some players) and it is usually red. I feel like one of those values is offset by an incorrect amount in the wrong direction (or my computer is dying).

**Comment by StatTrackFender** [comment]
Pull the latest changes from the repo.

**Comment by ggothreau** [comment]
Ah, thanks dude!

**Comment by ggothreau** [comment]
Latest offsets as of Sep 21, 2016:

```
uint64_t glowInfoOffset = 0x595c4a0;
uint64_t LocalPlayerBase = 0x514cbd8;
uint64_t playerBase = 0x50c9748;
```

**Comment by ggothreau** [comment]
Latest offsets as of Sep 28, 2016:

```
uint64_t glowInfoOffset = 0x595c570;
uint64_t LocalPlayerBase = 0x514cca8;
uint64_t playerBase = 0x50c9818;
```

*edit: there was an update 5 hours after I posted this, but these offsets still seem to work.

**Comment by brendon11** [comment]
thx
@ggothreau

**Comment by ggothreau** [comment]
Latest offsets as of Oct 13, 2016:

```
uint64_t glowInfoOffset = 0x59ec010;
uint64_t LocalPlayerBase = 0x51dc6e8;
uint64_t playerBase = 0x5158fe8;
```

**Comment by ggothreau** [comment]
Latest offsets as of Oct 17, 2016:

```
uint64_t glowInfoOffset = 0x59ebf90;
uint64_t LocalPlayerBase = 0x51dc668;
uint64_t playerBase = 0x5158f68;
```

**Comment by ggothreau** [comment]
Latest offsets as of Oct 25, 2016:

```
uint64_t glowInfoOffset = 0x59ed160;
uint64_t LocalPlayerBase = 0x51dd828;
uint64_t playerBase = 0x515a128;
```

**Comment by swayamz** [comment]
uint64_t glowInfoOffset = 0x59f14f0;
uint64_t LocalPlayerBase = 0x51e1bb8;
uint64_t playerBase = 0x515d4a8;

Offsets as of Oct 28, 2016

**Comment by joejoepojoe** [comment]
1.35.5.7 offsets? Tried finding them myself but what i thought to be the PlayerBase struct came up blank

**Comment by DooubleO** [comment]
uint64_t glowInfoOffset = 0x59f1590;
uint64_t LocalPlayerBase = 0x51e1c58;
uint64_t playerBase = 0x515d548;

**Comment by aKalisch** [comment]
I think we don't need this any more :-)
