### ISSUE TITLE
Walls Failing After ~15 minutes of Use

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#44]
With every build of wall there is the same problem, after about 15 minutes my console reads `State changed 0`. What does this mean? It appears to happen randomly and requires me to pause my game, close old wall process, run new one with sudo which takes about a minute. How can I fix this?

**Comment by gabsens** [comment]
`CGEventSetIntegerValueField(event, kCGKeyboardEventKeycode, (int64_t)keycode);`
   `if (keycode == 9) {`
`states = !states;`
`printf("State Changed! %i\n", states);`
`}`

`if (states){`
`int i_teamNum = testLocalPlayerAddress(task, moduleStartAddress);`
`readPlayerPointAndHealth(task, current_task(), moduleStartAddress,``glowObjectLoopStartAddress, i_teamNum);`
`}`

`9` is the keycode for the V key according to [this](http://web.archive.org/web/20100501161453/http://www.classicteck.com/rbarticles/mackeyboard.php)

If my understanding is correct, pressing V negates `states`, which means no more wallhack.

**Comment by ghost** [comment]
Right, Hitting Command + V will toggle it on and off. I'm planning on actually making an app which will handle the keyboard shortcuts and such and just run or terminate the executable or the C++ code itself.

**Comment by ghost** [comment]
@buzzel @gabsens Had no idea it was even toggleable, all is well now. Also the pattern identifier works like a charm. In new updates of CS:GO is it possible the memory patterns will change ?
