### ISSUE TITLE
CS:GO Crashing Every 20 Minutes

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#45]
Console shows no errors of any sort, the game just crashes. Typically the walls will stop working and within 10 seconds CS:GO closes itself. I have no idea why this is happening, and I am wondering if this is happening to anyone else. This may be a problem specific to me, but if not, how can I check CS:GO's logs?

EDIT: Just to clarify, when walls are not activated my game runs perfectly for hours.

**Comment by gabsens** [comment]
You can ask Valve's employees here https://github.com/ValveSoftware/csgo-osx-linux/issues

lol

**Comment by ghost** [comment]
@gabsens Sounds great, I'll link them to my profile as well.

edit: I was VACed

**Comment by DooubleO** [comment]
You must've been way too obvious rip

**Comment by gabsens** [comment]
They don't ban manually and VAC on OSX is sleeping, you're safe

**Comment by ghost** [comment]
@DooubleO It was a joke lel. Overwatch is the only chance of a ban with walls.
