### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by sulik12345** [iseekwonderful/csgoGlow#46]
When I hit Command + B in xcode with the Wall.xcodeproj it says there are 2 errors. 

Unused Entity Issue | Unused variable 'g'

Unused Entity Issue | Unused variable 'kr3'

If possible could  you link me to a tutorial on how to do this? Thanks

**Comment by ghost** [comment]
Those errors do not matter, as long as you're in CS:GO on a team the build will work. Also you should run the build directly as an exec instead of running it through xcode each time.
