### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by sulik12345** [iseekwonderful/csgoGlow#47]
I used it for 3 days, and now it just stopped working.... Idk... CSGO wasnt updated or anything. Anyone else having these issues? I tried the updated version aswell

**Comment by sulik12345** [comment]
I found the offsets of 

uint64_t glowInfoOffset = 0x594A900;
uint64_t LocalPlayerBase = 0x513B038;
uint64_t playerBase = 0x50B5288;

Could someone please check and confirm?

**Comment by gabsens** [comment]
> uint64_t playerBase = 0x50B7678;

according to https://github.com/iseekwonderful/csgoGlow/issues/43

**Comment by ghost** [comment]
Latest offsets as of July 15th, 2016
`uint64_t glowInfoOffset = 0x594A900;`
`uint64_t LocalPlayerBase = 0x513B038;`
`uint64_t playerBase = 0x50B7678;`

THESE are working. @sulik12345 your playerBase if off somehow...

**Comment by sulik12345** [comment]
Thanks tr1kyyy! I wasnt sure how to find the player base.....

**Comment by ghost** [comment]
@sulik12345 I am using @gabsens pattern detector. Works like a charm. Thank him, not me.

**Comment by sulik12345** [comment]
@tr1kyyy I found the scanner, but could you tell me how to use it? Doesnt provide information on how to use. Do I launch CSGO with -insecure then build it in Xcode?

**Comment by ghost** [comment]
@sulik12345 Build the project with the g++ command. Then run it with sudo.

**Comment by gabsens** [comment]
@sulik12345 read **all** of this 

https://github.com/iseekwonderful/csgoGlow/issues/43

**Comment by sulik12345** [comment]
@gabsens Im bad at looking for things xD Thanks! I favorited the video. Btw, I saw one of your videos about no recoil, will you ever upload that to here?

**Comment by ghost** [comment]
@gabsens Aimlock would be amazing. Would you ever plan to release it?

**Comment by ghost** [comment]
@gabsens I've commented on a few of your videos asking if you would ever release your project. Make it a challenge or a riddle to get it working so only those who work for it can get it to work. I appreciate your work and I am deeply interested in a functional aimlock.

**Comment by Galenika** [comment]
@tr1kyyy @sulik12345 where are those videos?
