### ISSUE TITLE
Unused strings and Format Specific Types? Is it because i need to update the offsets?

### ISSUE THREAD

**Issue by rawrchad** [iseekwonderful/csgoGlow#48]
I am just curious if i only need to update the offsets, I don't want to waste my time learning how to update if that isnt the problem?

<img width="1280" alt="offsets" src="https://cloud.githubusercontent.com/assets/12880229/17109024/cc407a88-525b-11e6-814a-0d90de0f4673.png">

**Comment by ghost** [comment]
Yes you will only need to update offsets. In the left menu navigate to all of the files in this xcode project, go to the main.cpp, and replace the old offsets with the new offsets. Also make sure cs:go is running when you do so.

**Comment by ghost** [comment]
Ill check offsets in two hours to make sure walls are functional. If not I'll update them here again.

**Comment by rawrchad** [comment]
Thanks Tr1kyyy i figured it out :P I also learned how to find offsets :] well with the scanner lol
