### ISSUE TITLE
Using Pattern Scanner

### ISSUE THREAD

**Issue by K2QGIT** [iseekwonderful/csgoGlow#51]
so I've used this twice now with perfect results, until tonights update and the offsets never seem to be correct. This is what im getting
<img width="215" alt="screen shot 2016-07-27 at 10 30 01 pm" src="https://cloud.githubusercontent.com/assets/20144499/17201243/e718d766-5449-11e6-9014-e0463f148b5f.png">

**Comment by DooubleO** [comment]
Getting the same, but it doesn't seem to work for me aswell

**Comment by DooubleO** [comment]
This is what I'm getting
client: 0x125000000 18640220
LocalPlayer: 0x5145338
EntityList: 0x12a0c1f48

**Comment by DooubleO** [comment]
Glow: 0x85

**Comment by gabsens** [comment]
EntityList: 0x50C1F48 and the glow pattern is indeed broken

**Comment by DooubleO** [comment]
Will there be an update to the program to get the glow pattern finder working?

**Comment by gabsens** [comment]
try 0x5954c18 for glow and tell me if that works

**Comment by DooubleO** [comment]
It's making my game crash.

**Comment by gabsens** [comment]
my bad, try 0x5954c00

**Comment by DooubleO** [comment]
Makes it crash also..
Should I have my other offsets as anything other than:
glowInfoOffset = 0x50C1F48
LocalPlayerBase = 0x5145338
playerBase = 0x5145338

**Comment by gabsens** [comment]
try this 

glowInfoOffset = 0x5954c00
LocalPlayerBase = 0x5145338
playerBase = 0x50C1F48

**Comment by DooubleO** [comment]
how about m_iGlowIndex

**Comment by DooubleO** [comment]
0x5954c00 as well?

**Comment by gabsens** [comment]
glowInfoOffset = 0x5954c00
LocalPlayerBase = 0x5145338
playerBase = 0x50C1F48

these are correct

**Comment by DooubleO** [comment]
Ding ding, we have a set of working offsets, thanks once again to @gabsens

**Comment by gabsens** [comment]
Now I go watch Mr Robot. I'll fix the pattern scanner when I'm back

**Comment by DooubleO** [comment]
Sweet, Thanks!
