### ISSUE TITLE
Crash on Assault map

### ISSUE THREAD

**Issue by kukhtoa** [iseekwonderful/csgoGlow#52]
After vote map, when map changes to Assault, hack and csgo is crashing. How I can to fix this?

**Comment by gabsens** [comment]
Are you sure you can reproduce that ?

**Comment by kukhtoa** [comment]
I'll try make video

**Comment by kukhtoa** [comment]
I can't make video. It happens randomly.  When map changes to assault, when you start move, jump, glow is stopped. Then cs go crashes.

**Comment by kukhtoa** [comment]
Chance to crash ~ 25-30%

**Comment by iseekwonderful** [comment]
we will add a judgement that round is start to invoid memory write to known heap which may cause crash

**Comment by sacredgeo** [comment]
Assault is the only map that causes this to crash for me. Great work regardless. I've been hoping for a mac osx hack for years. You guys are legends!

**Comment by gabsens** [comment]
@sacredgeo it's weird, please provide more details

**Comment by sacredgeo** [comment]
@gabsens  Sure. It works fine on every other map. Usually when I join assault, the game keeps going, but the hack stops. So I open a new terminal and launch the hack again. It usually crashes quickly. I'll do some tests and figure out exactly when. I think when  the round changes. I'll get back to you.

**Comment by sacredgeo** [comment]
@gabsens 

Test #1: Join cs_assault. The hack worked during warmup. I was on T side, and it was fine. I switched to CT side and it still worked. Warmup ended. During round 1, the hack was no longer working. I launched a new terminal, sudo -s, and it worked again. I played the next round and it was working. When the next round started (round 2), the CSGO application crashed.

**Comment by aKalisch** [comment]
Does anyone have problems with assault these days?

**Comment by Brazzone** [comment]
yeah, experienced same problems.

**Comment by aKalisch** [comment]
Will close this by now as there is no verification.
If someone verifies it i'll reopen it.
