### ISSUE TITLE
How do you reduce RAM usage with game and Glow?

### ISSUE THREAD

**Issue by K2QGIT** [iseekwonderful/csgoGlow#53]
Ive been trying out multiple things lately as far as game w/ hack vs fps vs RAM... Ive had to switch to 4:3 for frames and thats working very well, but I cannot do Full screen without the hack w/ xcode failing. Also map switches cause it to crash... Also anything above 2XMSAA multicore rend will use too much RAM. Does anyone have tips or suggestions for freeing RAM before game. I understand you cant ask for everything haha, just trying to optimize.

**Comment by gabsens** [comment]
Give us numbers at least: how much RAM  you have on your system, how much RAM csgo uses when you're in-game and how much the hack uses.

The code here on github is absolutely not optimized (CPU-wise more than anything else)

**Comment by K2QGIT** [comment]
4GB Total, Computer uses about 2GB with normal running, CS-GO Alone will use 1-1.5GB, X-code will use up to 1GB, once running, the system will prioritize the game and Hack but any slight change in usage (opening the internet) will max it out and X-code is the first on the hit list. I've tried terminal, but it uses more than X-code funny enough. Computer Specs: 
<img width="244" alt="screen shot 2016-07-29 at 10 32 32 am" src="https://cloud.githubusercontent.com/assets/20144499/17255762/d2094778-5577-11e6-9336-c092a392add0.png">

**Comment by gabsens** [comment]
You don't need Xcode whatsoever... get the binary Xcode built and run it as root with Terminal

I got quite the same specs and I can't get above 80fps on dust2, with lowest settings

**Comment by Wolf-88** [comment]
I literally cannot find the exec wall file, I searched the developer folders and no luck, I also do not know how to compile multiple C++ files into an executable, only one at a time, otherwise I wouldve been trying this all along and dump x-code cause it takes up 10gb of space.

**Comment by K2QGIT** [comment]
Solved: for FPS I used lowest setting with trillinear and 2xMSAA,4:3, Then found a program to clear RAM easily while still in game, and used hack in terminal, 1GB free RAM while playing and no down time, also fullscreen capable, but switching maps still causes it to halt the process.

Getting 150 frames now

**Comment by gabsens** [comment]
here's how you find the binary file and run it

https://www.youtube.com/watch?v=pvMQeYRM4d4

**Comment by K2QGIT** [comment]
@gabsens Thanks! I did some googling to find that aswell, you should put that link on your pattern scanner page too
