### ISSUE TITLE
Walls not working

### ISSUE THREAD

**Issue by markwu-sde** [iseekwonderful/csgoGlow#55]
Hello,

Forgive me if I did something horribly wrong(I hope not but it could very well have happened), but when I updated the offsets and ran it either through xcode(Product-Run), or executable(sudo- executable that I built through xcode), it always says it is running successfully but I do not see the glow hack in process. One of the potential causes is that when I initially tried to run it was that i was on mac osx 10.9.5 and it says that it does not meet the minimum development build so I lowered it. Any help/ suggestions? Thanks in advance!

**Comment by gabsens** [comment]
What version of OSX are you using now ? 

Are you launching the program as root ?

**Comment by markwu-sde** [comment]
I am using 10.9.5 osx.
- I am unfamiliar with launching this program as root. I just built the executable dragged it to my desktop and then just typed in sudo (Wall)

**Comment by rawrchad** [comment]
No I think there might have been an update it doesn't work for me either. I just haven't looked for the new ints yet.

**Comment by gabsens** [comment]
Copy paste the output of the console after you've launched the executable

the code uses functions that exist since the beginning of OSX so there should be no compatibility issues

**Comment by markwu-sde** [comment]
Could you tell me how you would launch the executable? Like I said earlier, I just kind of guessed and dragged the executable into the terminal after sudo

**Comment by markwu-sde** [comment]
I did what you asked and just straight up clicked the executable. 

Family$ /Users/Family/Desktop/Wall ; exit;
Segmentation fault: 11
logout

[Process completed]

**Comment by gabsens** [comment]
Have a look here https://www.youtube.com/watch?v=pvMQeYRM4d4

You're failing to run the executable with the right privileges.

Also, you're supposed to start csgo first.

**Comment by markwu-sde** [comment]
I have cs go started currently. Just ran it again. 

-MacBook-Pro:~ Family$ sudo -s
Password:
bash-3.2# cd Desktop
bash-3.2# ./Wall
Segmentation fault: 11
bash-3.2#

**Comment by gabsens** [comment]
Nope, the latest version of this repo is working perfectly fine.

Delete everything and re-download the project from github

**Comment by markwu-sde** [comment]
I went back and did what I thought I needed to do 1 more time. Same error as above?
1. Download file from github

open .xproj in x-code program

Went to Products-Build

Went over to build then pressed the little i button to show it in finder

dragged Wall exe program onto desktop

-MacBook-Pro:~ Family$ sudo -s
Password:
bash-3.2# cd Desktop
bash-3.2# ./Wall
Segmentation fault: 11
bash-3.2#

**Comment by gabsens** [comment]
try with this executable 
[Walltest.zip](https://github.com/iseekwonderful/csgoGlow/files/392521/Walltest.zip)

PS: if you're a VAC employee trying to sig this, go fu*\* yourself :)

**Comment by markwu-sde** [comment]
I dragged the Walltest executable on the desktop and got the same error:

-MacBook-Pro:~ Family$ sudo -s
Password:
bash-3.2# cd desktop
bash-3.2# ./Walltest
Segmentation fault: 11
bash-3.2#

**Comment by gabsens** [comment]
Either:
- I missed a CSGO update
- You missed a CSGO update
- there's a different CSGO build for Mavericks

**Comment by markwu-sde** [comment]
if it helps you, I can record my screen and send it to you

**Comment by ghost** [comment]
@MysticIridium Add me on skype if u want and ill walk u through it. Make sure you're using the right executable from the Developer folder.

**Comment by ghost** [comment]
@gabsens Any chance you would release your aimlock? I would love you forever :)

**Comment by markwu-sde** [comment]
Thanks. What is your skype?

**Comment by tr1kyyy** [comment]
@MysticIridium "nathanmarchantpro" pls no ddos XD

**Comment by markwu-sde** [comment]
So... I have decided to upgrade my mac software and try it once more. Will keep you updated @gabsens

**Comment by markietard** [comment]
Hi @TypicalPleb I am Marcus and I am kinda new to coding, but I am trying my very best to get a better understanding of how this thing works. I am still a little bit confuse regarding the compile/build of the project. Can you add me on Skype and explain a little more about this because I am really interested in knowledge of coding. My Skype ID is Parabot911

**Comment by markwu-sde** [comment]
UPDATE:

After installing new software from Maverick to El Capitan, everything seems to be working very smoothly. @gabsens hinted at this being a Maverick problem, and this is further verification that it probably is. Only problem is that memory gets overloaded after playing for an extended period of time so the frame rate goes drastically down, but its a inevitable side effect of running the program simultaneously. @gabsens thank you for the support, its a very nice hack. Although less useful if you dont want to get overmatched quickly(I would not recommend wallhanging), it provides an significant advantage. 

P.S @gabsens Is there any chance you would release your no-recoil or aimlock programs? I would love you forever.
