### ISSUE TITLE
Does it randomly stop working in the middle of games for you?

### ISSUE THREAD

**Issue by rawrchad** [iseekwonderful/csgoGlow#56]
Sometimes the wall hack stops working and i have to open a new terminal and run it again or sometimes re enter my password.

**Comment by sulik12345** [comment]
Yes, just restart it.

**Comment by gabsens** [comment]
This used to happen to me as well when I actually used this cheat, it's probably the spam in the terminal that does this.

**Comment by DooubleO** [comment]
It happens if you leave the game to go on google or something

**Comment by ghost** [comment]
@rawrchad @sulik12345 Note that pressing "v" will toggle the hack on and off, even if you're not in csgo. Typing in chat and using the letter "v" will toggle it. Just press v if they get turned off. And after about an hour and a half the cheat fails for some reason, just restart it.

**Comment by gabsens** [comment]
@sulik12345 @tr1kyyy 
Download the latest version of the repository and tell me if it still crashes.

**Comment by ghost** [comment]
@gabsens btw u have the refresh time still at 100 micro seconds. Yeah I'll test in in 30 min.

**Comment by ghost** [comment]
@gabsens Why isn't all the extra code not being implement just removed from the file entirely, like the useless print functions.

**Comment by ghost** [comment]
@gabsens Btw everything works great, only tested for a short time.

EDIT: I hope when reading these comments you do so with squidward's voice.

**Comment by gabsens** [comment]
@tr1kyyy you're free to make pull requests if you think some parts need improvement (and many do)

**Comment by ggothreau** [comment]
Yep, it is the console spam that is killing it. I got rid of the print functions within loops and I haven't had that problem since. I also disabled the V button toggle because I was accidentally hitting it all the time. I also increased usleep to 20000 and it lowered CPU usage for me significantly.

**Comment by ghost** [comment]
@gabsens I was trying to change the keybind to a simultaneous key press, but it looks like in Xcode there is no way to detect keys held down. Is there a way to setup a key sequence to toggle it? I might just throw out the dumb toggle option anyways.
