### ISSUE TITLE
Unconventional way to run program without lag in game

### ISSUE THREAD

**Issue by K2QGIT** [iseekwonderful/csgoGlow#58]
So, I along with most people have had lots of lag while running the hack with terminal and playing the game... but I found a way to reduce the usage of terminal and the script with a weird trick.
1. Open Game and prep terminal with sudo command
2. Set your video settings to windowed
3. Get in game, wait all the way til youre in a game 
4. Start hack, in game, switch to fullscreen
5. Switch back to windowed and quit terminal, just quit it and press ok.
6. Go back to game and switch to fullscreen

The hack will keep running without terminal open and the lag is completely gone... Will last into other games.

Hope this helps, 
WOLF88

**Comment by ghost** [comment]
@Wolf-88 Go to activity monitor and search "Wall". You might want to shut these processes down.  Closing terminal just prevents you from seeing the text. After a few days of running the walls the program will build up a ton of these processes, and they seriously lag your computer. Remember to clear these soon for optimal fps :D

**Comment by Freek3** [comment]
Thankyou !!!! @tr1kyyy @Wolf-88

**Comment by K2QGIT** [comment]
@tr1kyyy This essentially does that, just quicker and easier to understand for some, It keeps one process running that uses 20 kb of RAM instead of Terminal + Process. But I do understand what you do and its helpful.

**Comment by markietard** [comment]
@Wolf-88 Can you teach me how to prep the terminal with sudo command?

**Comment by aKalisch** [comment]
This should not be needed anymore as the hack was optimized.
So I can close this here.
