### ISSUE TITLE
That code runs but nothing it's not working

### ISSUE THREAD

**Issue by jananne** [iseekwonderful/csgoGlow#6]
Steps i did:
- Build the project.
- Open CSGO.
- Open Terminal
- Go to the build and run it with ./External (as root)

The code runs, showing:
----------updated----------
----------updated----------
----------updated----------
----------updated----------
----------updated----------
...

And when i push CMD + SHIFT + X, i see:
on! and states is 0

But the glow is not showing.

What am i doing wrong?

**Comment by iseekwonderful** [comment]
hello, In my mac it glows when after ./External
if not, please check both the version of this and csgo are newest
if still can't, tell me here and i will update some console log to find the problems

**Comment by jananne** [comment]
Yes they are both up-to-date. I also tried an older version, still no glow seen. If needed you can look on my macbook to see if you can find the problem. Do you have skype?

**Comment by ghost** [comment]
mine isnt working either after small update today

**Comment by iseekwonderful** [comment]
I was pretty busy these day, but i update some console log to show some more information, if u see this plz post what u see in ur mac, thx

**Comment by jananne** [comment]
I see it reads the health of the players, but still no glow is seen. I've tried this on a local play against bots. I don't know if that makes any difference. This is what i get in the terminal:

...
----------updated----------
Read player 2 health is 100 team is 2, glow index is 7
glow state is 1, alpha is 0.800000
Read player 4 health is 100 team is 2, glow index is 15
glow state is 1, alpha is 0.800000
Read player 5 health is 100 team is 2, glow index is 16
glow state is 1, alpha is 0.800000
Read player 7 health is 15 team is 2, glow index is 18
glow state is 1, alpha is 0.800000
Read player 10 health is 100 team is 2, glow index is 29
glow state is 1, alpha is 0.800000
----------updated----------
Read player 2 health is 100 team is 2, glow index is 7
glow state is 1, alpha is 0.800000
Read player 4 health is 100 team is 2, glow index is 15
glow state is 1, alpha is 0.800000
Read player 5 health is 100 team is 2, glow index is 16
glow state is 1, alpha is 0.800000
Read player 7 health is 15 team is 2, glow index is 18
glow state is 1, alpha is 0.800000
Read player 10 health is 100 team is 2, glow index is 29
glow state is 1, alpha is 0.800000
...

I hope this helps.

If you want to take a look into my macbook, just give me a shout.

**Comment by ghost** [comment]
Get the newest version it does work. If you need a hand download teamviewer
and I will do it for you

**Comment by jananne** [comment]
@CoHuff can you add me on skype? dehaanmedia is my user.
I'll give you my teamviewer info over there, that's more save ;).

**Comment by ghost** [comment]
resolved

**Comment by jananne** [comment]
Yes, i consider this issue closed.

**Comment by iseekwonderful** [comment]
so closed
