### ISSUE TITLE
Cannot get latest offsets

### ISSUE THREAD

**Issue by K2QGIT** [iseekwonderful/csgoGlow#60]
Ive used @gabsens pattern scanner and the old method and am successfully able to find local player and player base but glow is not working and I have found 3 different offsets for it... Im sorry im asking for help again like everyone. Many thank yous.

**Comment by gabsens** [comment]
Read last post here

https://github.com/iseekwonderful/csgoGlow/issues/43#issuecomment-237432304

and yes, glow pattern broke again.

**Comment by K2QGIT** [comment]
@gabsens Saw that, and have been trying different methods to no prevail, was wondering if anyone had successfully figured it out yet. Not to repeat the question, was using this more of as a brain storming session.

**Comment by gabsens** [comment]
@Wolf-88 do you want me to film another video ? Finding the glow offset is indeed tricky

**Comment by gabsens** [comment]
There was a tiny byte that made the glow pattern fail, it should work fine in future updates.

**Comment by K2QGIT** [comment]
@gabsens Thanks, I'm trying to learn myself and I dont want to inconvenience you.. It was a matter of an extra letter I pressed on my keyboard before saving XD coding is meticulous
Can close if you want.
