### ISSUE TITLE
1 or 2 of the enemy team do not show up.

### ISSUE THREAD

**Issue by DooubleO** [iseekwonderful/csgoGlow#61]
Current offsets i'm using 
uint64_t glowInfoOffset = 0x5958F20;
uint64_t LocalPlayerBase = 0x5149658;
uint64_t playerBase = 0x50C6268;

int m_iGlowIndex = 0x5958f20;

**Comment by ghost** [comment]
@DooubleO Are you positive they're just not rendered yet because they're behind several walls?

**Comment by DooubleO** [comment]
I look at the 1 or two people right in the eye multiple times, but no glow

**Comment by DooubleO** [comment]
@tr1kyyy

**Comment by ggothreau** [comment]
Yeah, I can reproduce it consistently not showing 1 enemy's glow. I'm trying to figure out if it's the offsets (offset by one playerbase) or if it's something in the code that needs to change.

**Comment by DooubleO** [comment]
Another update, my pattern finder isnt working... Anyone want to help me out?

**Comment by gabsens** [comment]
@DooubleO the **latest** version of the pattern scanner yields 

```
LocalPlayer: 5149658

EntityList : 50c6228

Glow: 5958f20
```

**Comment by ggothreau** [comment]
Whoops, it turned out I was using an older version of pattern scanner. Sorry!
