### ISSUE TITLE
Glow ESP not working?

### ISSUE THREAD

**Issue by completenoob2** [iseekwonderful/csgoGlow#66]
So I don't have the errors anymore but it says build successful and I did the route but there is no Glow ESP ingame

Using these offsets:

uint64_t glowInfoOffset = 0x5955F00;
 uint64_t LocalPlayerBase = 0x5146638;
 uint64_t playerBase = 0x50C3248;

**Comment by gabsens** [comment]
https://www.youtube.com/watch?v=AefIiBg2HKU
