### ISSUE TITLE
Using this hack

### ISSUE THREAD

**Issue by gabsens** [iseekwonderful/csgoGlow#67]
I've made a video here https://www.youtube.com/watch?v=AefIiBg2HKU

Every issue along the lines of "I can't compile", "I can't use root", "how to run" will be closed as a duplicate and locked immediately.

**Comment by gabsens** [comment]
And another one for the pattern scanner https://www.youtube.com/watch?v=aP99mdDzwQk

**Comment by klimikus2003** [comment]
stopped working

**Comment by trich7** [comment]
What is the point of the pattern scanner? is that crucial?
