### ISSUE TITLE
VAC

### ISSUE THREAD

**Issue by Commonly** [iseekwonderful/csgoGlow#68]
I've been using this hack for around 1 month. Haven't been vacced. I'm pretty sure (for now) that this is vac-proof. I recently however have been banned by Overwatch. So if you're not careful how you use this hack, then you'll end up getting banned. So as long as you're careful no need to worry about vac getting you.

**Comment by gabsens** [comment]
No one has ever been VAC banned with these open source cheats on Linux and OSX. I guess Valve does not care

**Comment by K2QGIT** [comment]
Use this hack as an assist, not a crutch. Using this, I ignore most people through walls, just know you have to die sometimes...Mainly this is very helpful for dark areas of the map or finding the right headshot easier....been using this for months and am a high rank and no one has said anything ever. I'm even on a team with viewed matches of 300+.

**Comment by gabsens** [comment]
August 16: 

> A new Steam client has been released and is being automatically downloaded. Changes since the last major release include the following:
> 
> Mac OS X / macOS
> 
> The Steam application has been reworked for better compatibility with macOS Sierra. This may result in an older copy of the Steam application being placed in your Trash. It is safe to delete the older copy by emptying the trash.

Maybe they updated VAC lmao

**Comment by K2QGIT** [comment]
@gabsens Still undetected :D played comp and ESEA. It was just a compatibility update for sierra to download steam, it was a old version. No VAC updates or security as far as i can see.

**Comment by gabsens** [comment]
@Wolf-88 indeed, the VAC 2 module on OSX has not been updated for a long time

**Comment by inormalize** [comment]
@Wolf-88 You've got ESEA working on OS X? How?
