### ISSUE TITLE
Recent Update

### ISSUE THREAD

**Issue by K2QGIT** [iseekwonderful/csgoGlow#69]
The recent update kind of killed the glow... It very dim except for when a player is talking...Testing this out multiple times, you can literally only see someone when they're talking on their mic. 

[SPECTATOR]
– Player xray glow now dims when player is not making any audible sound. Several convars are available to tweak this behavior; “find spec_glow” for a list.

Calling @gabsens 

"spec_glow_decay_time" = "2.0" min. 0.000000 client                              - Time to decay glow from 1.0 to spec_glow_silent_factor after spec_glow_full_time
"spec_glow_full_time" = "3.5" min. 0.000000 client                               - Noisy players stay at full brightness for this long.
"spec_glow_silent_factor" = "0.7" min. 0.000000 max. 1.000000 client             - Lurking player xray glow scaling.
"spec_glow_spike_factor" = "1.2" min. 1.000000 max. 3.000000 client              - Noisy player xray glow scaling (pop when noise is made).  Make >1 to add a 'spik
"spec_glow_spike_time" = "0.5" min. 0.000000 client                              - Time for noisy player glow 'spike' to show that they made noise very recently.

**Comment by zrichmond3** [comment]
It doesn't even work for me after that last update.

**Comment by markwu-sde** [comment]
@zrichmond3 did you try using the new glow offsets? Does anyone by any chance have them?

**Comment by markwu-sde** [comment]
nvm... I see what you are saying. you see glimpses of them(always red btw) when they talk but then they quickly disappear

**Comment by markwu-sde** [comment]
@Wolf-88 so What settings should I make it to get the optimal settings?

**Comment by zrichmond3** [comment]
@MysticIridium nope, I may try to get it going tomorrow.  Is your hack working?

**Comment by markwu-sde** [comment]
it was working a little bit(I could see the glows for a split second- but after attempting to modify the console glow settings it is no longer working.

**Comment by zrichmond3** [comment]
I've seen the glow for a split second too. Dang! I wonder how quickly they will fix this. @Wolf-88 awesome job finding this issue after the update.

**Comment by markwu-sde** [comment]
i mean, if you are decent at the game, even that split second glow will help you

**Comment by K2QGIT** [comment]
This is not a quick fix, most of the code needs to be fixed now to account for the different times and ratios....Unless we can make it fully glow all the time...But that external assistance.

**Comment by StatTrackFender** [comment]
What part of the projects needs to be scrapped/rewritten?

**Comment by K2QGIT** [comment]
So the entirety of finding the specific glows to each volume of noise and then the corresponding health of the player when glowed...or... You dont access the memory of the game and find a way to glow players fully all the time.

**Comment by K2QGIT** [comment]
Of-course I could be totally wrong about everything I've said and it just a matter of finding the correct offsets the game has now

**Comment by treflo** [comment]
I just compiled this, updated offsets using the pattern scanner.

Mac OSX El Captain 10.11.3
Running as root, Disabled SIP.

Seems the offsets are changed or glow isn't working properly.

Anyone send me the updated source or offsets.

 i'd gladly donate a few dollars for your help

Steam: http://steamcommunity.com/id/coder1337smile

**Comment by gabsens** [comment]
Fixed, download the latest version of the repository.

The pattern scanner still gives the right offsets, only some netvars were changed.

Paypal donations accepted here mariemromon@yahoo.fr
