### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by ghost** [iseekwonderful/csgoGlow#7]
Hey, there was a small update today and since i have not been able to get the glow working.

**Comment by CoHuff** [comment]
p.s I failed my C# class so this would be cool to learn.

**Comment by ghost** [comment]
The pid is 499
Version: 14, 292 images at offset 0x2000000
[Gaben:] I tell U /Users/***_/Library/Application Support/Steam/steamapps/common/Counter-Strike Global Offensive/bin/engine.dylib
, address is 0x94e8000 
[Gaben:] I tell U /Users/**_/Library/Application Support/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/bin/client.dylib
, address is 0x2f800000 
glow loop address is 0x0----------updated----------
----------updated----------

**Comment by iseekwonderful** [comment]
Hi, I have update the offset

**Comment by ghost** [comment]
Im currently taking computer programmer analyst, if we could talk via skype or something id love to learn.

**Comment by iseekwonderful** [comment]
yeah, where are u come from?

**Comment by ghost** [comment]
Ontario, Canada!

**Comment by iseekwonderful** [comment]
I am in GuangZhou China, and do u use other IM tool other than Skype?

**Comment by ghost** [comment]
Oh wow awesome! Not currently but im free to download whatever, i have steam obviously aswell.

**Comment by iseekwonderful** [comment]
All right~, I download Skype and u can add me:  steamedsheep@hotmail.com
and my steam is : http://steamcommunity.com/profiles/76561198248092082/

**Comment by ghost** [comment]
another update, and added!
