### ISSUE TITLE
Player and LocalPlayer structs

### ISSUE THREAD

**Issue by aKalisch** [iseekwonderful/csgoGlow#73]
I've rewritten the source to add more features (TriggerBot, Bunnyhop).

I think the your Code could be rewritten to use structs on top of the main.cpp to get all the Informations we need in later stages.

So we don't read the memory on demand. Just when while loop in main method executes.

```
struct moduleInfo_t
{
    pid_t pid;
    task_t task = 0;
    mach_vm_address_t moduleStartAddress;
    unsigned long moduleLength = 0x0511e000;
    uint64_t glowObjectLoopStartAddress;

    void readInformation()
    {
        pid = get_process();
        task = get_client_module_info(task, pid, &moduleStartAddress, &moduleLength);
        getEntityGlowLoopStartAddress(task, moduleStartAddress, glowInfoOffset, &glowObjectLoopStartAddress);

        printf("%llx\n", glowObjectLoopStartAddress);
    }
}moduleInfo;

struct myPlayer_t
{
    uint64_t playerBase;
    int teamNum;
    int state;
    int chID;
    int weapon;

    void readInformation()
    {
        Utils::ReadMemAndDeAllocate(moduleInfo.task,
                                    current_task(),
                                    moduleInfo.moduleStartAddress + localPlayerOffset,
                                    &playerBase);

        Utils::ReadMemAndDeAllocate(moduleInfo.task,
                                    current_task(),
                                    playerBase + teamOffset,
                                    &teamNum);

        Utils::ReadMemAndDeAllocate(moduleInfo.task,
                                    current_task(),
                                    playerBase + flagOffset,
                                    &state);

        Utils::ReadMemAndDeAllocate(moduleInfo.task,
                                    current_task(),
                                    playerBase + crosshairIDOffset,
                                    &chID);

        Utils::ReadMemAndDeAllocate(moduleInfo.task,
                                    current_task(),
                                    playerBase - currentWeaponOffset,
                                    &weapon);
    }
}myPlayer;

struct enemyList_t
{
    uint64_t enemyBase;
    int teamNum;
    int glowIndex;

    void readInformation(int currentPlayer)
    {
        Utils::ReadMemAndDeAllocate(moduleInfo.task,
                                    current_task(),
                                    moduleInfo.moduleStartAddress + playerOffset + 0x20 * currentPlayer,
                                    &enemyBase);

        Utils::ReadMemAndDeAllocate(moduleInfo.task,
                                    current_task(),
                                    enemyBase + teamOffset,
                                    &teamNum);

        Utils::ReadMemAndDeAllocate<int>(moduleInfo.task,
                                         current_task(),
                                         enemyBase + glowIndexOffset,
                                         &glowIndex);
    }
}enemyList[60];
```

and at main method in the while loop:

```
            myPlayer.readInformation();
            for (int i = 0; i < 60; i++)
            {
                enemyList[i].readInformation(i);
            }
```

If someone is interessted in Bunnyhop and TriggerBot contact me.

**Comment by aKalisch** [comment]
I can say that my hack runs very stable without any crashes.

**Comment by godmaker11** [comment]
Can u make build for non-experience users ?
Many ppl really don't know how to use this code.

**Comment by DooubleO** [comment]
@aKalisch I'm interested in that bunny hop, hit us up.

**Comment by StatTrackFender** [comment]
At the end of the day, if something like this is to be implemented, the entire app should be rewritten with a UI to handle enabling/disabling actions. The glow is the only thing i've ever cared about just because it makes it easier to see the people in front of me. Trigger and aimbots are useless to me because then you aren't even playing the game. 

I also feel like that once aimbots and such take notice on the mac, valve will bring VAC detection to the mac. Currently its not fully implemented or disabled all together, and I personally would want to keep it that way :P

**Comment by jacc** [comment]
I agree with @StatTrackFender. We're trying to keep a low-profile here.

**Comment by gabsens** [comment]
LOL, the wankers at Valve can't even sig public cheats correctly on Windows, and you expect them to do something on OSX ?

**Comment by jacc** [comment]
That is true. Valve probably doesn't notice us on OSX.

**Comment by gabsens** [comment]
you can shoot them a message here https://github.com/ValveSoftware/csgo-osx-linux/issues and see if anything happens

@Tele42 what do you say ?

**Comment by StatTrackFender** [comment]
True, but it might give them incentive to try on OS X. Thats the last thing you want, is them to actually _try_ and do something for this.

**Comment by aKalisch** [comment]
I think VAC should be the smallest Problem with Anti-Cheat.
Overwatch is more critical. And know what? Overwatch will ban suspected cheaters cross-platform ;-)

**Comment by gabsens** [comment]
Be blatant one match a day, change account, rinse and repeat

**Comment by aKalisch** [comment]
For those who want to look at my hack they can look here:
https://github.com/aKalisch/GOSX-Multihack

**Comment by sulik12345** [comment]
@aKalisch Could you maybe help me with your BHOP script? I have downloaded the file, but nothing happens when i run the license thing...

**Comment by aKalisch** [comment]
You need to checkout the development branch,  clone to your machine, open in xcode and build the executable. 
After that run it as root after you are connected to server.

**Comment by sulik12345** [comment]
@aKalisch COuld you add me on skype? I think I might have something to show you to improve it. sulik12345 - skype

**Comment by aKalisch** [comment]
Sorry m8. But i don't have Sykpe ;-)

Create a pull-request on my repo so i can review it.

**Comment by DooubleO** [comment]
Getting the error: 

error: couldn't create directory /Users/akalisch/Games/Tools: Permission deniederror: open /Users/akalisch/Games/Tools/GOSX-Multihack: No such file or directory

**Comment by aKalisch** [comment]
Build directory is missing. In xCode click on the project on the left and then go to the Build Phases tab in the middle.
Open Copy-Files and remove the entry GOSX-Multihack

**Comment by DooubleO** [comment]
@aKalisch Is there a way to only have glow and bhop and not trigger?

**Comment by aKalisch** [comment]
Press CTRL + L
That will switch of the trigger bot ;-)
You also can see the state when you launch the hack ;-)

**Comment by DooubleO** [comment]
ty

**Comment by aKalisch** [comment]
Updated my code and added a README :-) We might close this here. Would be better to discuss issues on my hack on my Repo :-)
