### ISSUE TITLE
PID: 1840

### ISSUE THREAD

**Issue by godmaker11** [iseekwonderful/csgoGlow#74]
Hello.

Can't start in xCode. After i presed "Play" in log i see these errors:

Found CSGO PID: 1840
Process reallocation: 1840 -> 0 [5 - (os/kern) failure]
Failed to get get info.
Failed to get the Client.dylib address
Program ended with exit code: 9

CS:GO is running.

**Comment by rawrchad** [comment]
run it is Terminal, I use this code 

sudo /Users/Chad/Library/Developer/Xcode/DerivedData/Wall-gifxcnmvcwiksnehpbpyvgfifbrk/Build/Products/Debug/Wall 

While in XCode Press Command B then you will see the exec/Terminal Bash and it will be titled wall, just type in terminal Sudo then right click that wall bash file click find in finder then drag into terminal. I tried explaining the best I could.

**Comment by godmaker11** [comment]
@rawrchad thanks for help, i did all what you say, but in game nothing changes.
Terminal text - 

Found CSGO PID: 45544
Process reallocation: 45544 -> 1503 [0 - (os/kern) successful]
CSGO Memory 4528177152 
Version: 14, 293 images at offset 0x101800000
Found the Client.dylib address: 0x128800000 
Module should end at 0x12d91e000

Have no idea how to set wallhack on.

`Last login: Fri Aug 26 10:51:22 on console
iMac-Alexander:~ godmaker$ sudo /Users/godmaker/Library/Developer/Xcode/DerivedData/Wall-dkigwcgmtvdzapcyoujiugqqdbwr/Build/Products/Debug/Wall
Password: **********
Found CSGO PID: 1143
Process reallocation: 1143 -> 1503 [0 - (os/kern) successful]
CSGO Memory 4521050112 
Version: 14, 294 images at offset 0x102800000
Found the Client.dylib address: 0x128800000 
Module should end at 0x12d91e000
`

full list in terminal

**Comment by godmaker11** [comment]
ok. now it's work. thank you
