### ISSUE TITLE
Script for El Capitan to Run CSGO at Priority High?

### ISSUE THREAD

**Issue by rawrchad** [iseekwonderful/csgoGlow#75]
I know you use to be able to do it on older version of mac as shell script renice -20 but I can not figure it out for El Capitan. I believe that it may help the crash issue, if anyone can help me and also fellow Macbook Pro Players for this that would be great :]

**Comment by rawrchad** [comment]
Sorry  I know this isn't really the right place, but you guys know more about scripts than I do, as I am newer to the mac scene.

**Comment by gabsens** [comment]
Didn't ever give me the slightest FPS boost, I'd stick to `mat_queue_mode 2`if I were you

**Comment by rawrchad** [comment]
Thank you! What do you set your max fps to as well? 
Also what about your launch options here is what I have set, 
-console -novid -lv -nod3d9ex -threads 4 -high
