### ISSUE TITLE
CS GO Crashing Randomly?

### ISSUE THREAD

**Issue by markwu-sde** [iseekwonderful/csgoGlow#76]
I doubt that this is a glitch pertaining to the hack,

but CS GO randomly closes and shuts down after around 15-20 minutes(with the hack running). It usually starts with glitches once in a while(stutters) , and then is followed up with a long stutter and the game closing down. Is this because the hack is taking too much much memory?

**Comment by rawrchad** [comment]
It is just the fact of using a macbook lol oh and if you hold TAB it might crash lol

**Comment by jacc** [comment]
@rawrchad Try without using the hack and report back to us.

**Comment by iseekwonderful** [comment]
does anyone here know how to find the log related to a crash in macOS?

**Comment by markwu-sde** [comment]
UPDATE:

So after looking around and typing in the console mat_queue_mode 2, it helps a little bit with the crashing. However, what I found most helpful in restarting the walls after each game.

**Comment by markwu-sde** [comment]
@iseekwonderful @gabsens 

Also, is it theoretically possible to create aimlock in xcode? I was thinking of trying to make it but I dont know how I would go about doing it. Advice?

**Comment by NexieCSGO** [comment]
Happens to me too :/

**Comment by aKalisch** [comment]
Will close this as the hack has been completly refactored.
