### ISSUE TITLE
Detected by FACEIT

### ISSUE THREAD

**Issue by joejoepojoe** [iseekwonderful/csgoGlow#77]
I used the hack for 3 games in faceit, a round into my 4th game, i got perma banned for cheating on a premium account. Do no use this on FACEIT, their anti-cheat picks this up.

**Comment by iseekwonderful** [comment]
yeah, don't use this in any platform who has third part anti-cheat

**Comment by rawrchad** [comment]
It's because FACEIT has a program that takes screenshots, so like if you take a screenshot with your steam it shows the chams? Well same for faceit

**Comment by gabsens** [comment]
@rawrchad  faceit anticheat is 100% server sided, what are you talking about ?

**Comment by rawrchad** [comment]
Then the only way they could tell is if you are blatantly looking at the through the walls? I haven't been banned on faceit lol but a lot of faceit players have told me thats what they do.

**Comment by gabsens** [comment]
@rawrchad they review people's demo when they get reported too much. Their anticheat looks for blatant no-recoil, triggerbot and perfect bunnyhop.

**Comment by joejoepojoe** [comment]
@gabsens maybe it was bhops? I mean i am a bhopper but i dont know if i bhopped much
@rawrchad also i have used this long enough to know how to make myself look legit
