### ISSUE TITLE
Issue with TeamNum

### ISSUE THREAD

**Issue by gabsens** [iseekwonderful/csgoGlow#8]
I've compiled the project and the glow runs just fine, except the team matching does not work at all. When I check the logs in the console, it says 

> team is 0

for every players, so everyone (including the enemies) are glowed in blue.

After checking your code, it looks as if the variable `iTeamNum` is not modified at all...

**Comment by iseekwonderful** [comment]
yeah, some offset goes wrong, fixed

**Comment by gabsens** [comment]
It works indeed, thanks for the quick fix. 
Is there a simple way to read my own teamnumber as well ?  I want to glow only enemies.

**Comment by iseekwonderful** [comment]
actually the `iTeamNum` is used for check team(3=CT,2=T), and in windows there is a offset called player Base but i fail to find it, and current way to find iTeamNum is stable when playing with bot but in some online multiplayer server. I plan to fixed it  when there are some free time.

**Comment by gabsens** [comment]
Ok, until you come up with the relevant offset, here is what I've done.  I simply created a global variable `team` that tells which team should be glowed (`team` takes the values 2 or 3). I added a hotkey that changes `team` from 2 to 3 and from 3 to 2. I also added this simple check: 
`if (playerTeamNum != team)
            continue;
`

**Comment by ghost** [comment]
how did you set the hotkey?
