### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tkriews** [iseekwonderful/csgoGlow#81]
followed tutorial and didnt work is it because of the update?

**Comment by McSwaggens** [comment]
Did you run the hack as root?

**Comment by extrenebiibues** [comment]
i think the update ruined it?!? can we get a fix asap

**Comment by DooubleO** [comment]
you just need to find the new offsets

**Comment by tkriews** [comment]
I've ran this perfectly plenty of times and an update just came out a few hours ago and now it doesnt work. Is there an ETA for when it will be back working?

**Comment by extrenebiibues** [comment]
@DooubleO how do u do that?

**Comment by DooubleO** [comment]
Use the pattern scanner

**Comment by DooubleO** [comment]
https://www.youtube.com/watch?v=3kMyiZ5yuvE

**Comment by tkriews** [comment]
How would that help

**Comment by DooubleO** [comment]
The offsets change every update. You find the new offsets with the pattern scanner and change the offsets in the code....

**Comment by tkriews** [comment]
Is there a video on how to do that?

**Comment by DooubleO** [comment]
Have a look at this
https://github.com/gabsens/Pattern-scanner-for-OSX

**Comment by DooubleO** [comment]
There is a video on that

**Comment by extrenebiibues** [comment]
@DooubleO oi once i change the code how do i get the updated one?

**Comment by tkriews** [comment]
@DooubleO I changed it now what do I do with it

**Comment by hitmyquatch** [comment]
uint64_t glowInfoOffset = 595b3a0;
uint64_t LocalPlayerBase = 514bad8;
uint64_t playerBase = 50c8658;
these are the offsets I used yet it did not work

**Comment by tkriews** [comment]
I got the same but I get a compiling error when I change them on my main.cpp then open it in xcode and hit build

**Comment by hitmyquatch** [comment]
if anyone gets it to work please comment

**Comment by McSwaggens** [comment]
Anyone know the offset to `crossHairID`?

**Comment by markietard** [comment]
@tkriews Yea man, I'm sorta having the same problem as you. It says _BUILD FAILED_ whenever I hit the build button.

**Comment by sacredgeo** [comment]
It builds fine. The offsets provided by the pattern scanner don't seem to be working right.

**Comment by hitmyquatch** [comment]
for me it builds fine, it just seems that the offsets are not correct

**Comment by aKalisch** [comment]
It seems that the GlowInfoOffset changed.

**Comment by aKalisch** [comment]
Find 0xAC00 and replace it with 0xAC10

Working fine for me ;-)

**Comment by aKalisch** [comment]
Also I will now test my complete Offsets and post them here (I got some more for a Working Aimbot and all that stuff.

**Comment by sulik12345** [comment]
@aKalisch what happened to your Multihack!?!?!? THe page isnt opening

**Comment by aKalisch** [comment]
I've took it offline, because I don't want to risk to get Untrusted with it.

Will release something public soon.

**Comment by iPredictable** [comment]
@aKalisch can you hmu with any osx cheat bro? I miss trolling kids in casual :/

**Comment by aKalisch** [comment]
Sure you can ;-)

Make your Source Code public, get a Signature of it and Valve can bust you (Also on Mac :-))

**Comment by sulik12345** [comment]
@aKalisch When do you think you will release something public?

**Comment by aKalisch** [comment]
Issue fixed in PR #86

**Comment by aKalisch** [comment]
@sulik12345 I don't know yet.

It will be just something basic (Glow, Trigger, Bhop, Autopistol switch, No-Flash, Radar Hack).

**Comment by extrenebiibues** [comment]
@sulik12345 where u from i need soemoen to play with since glow only is not enough to get to a high rank solo q

**Comment by sulik12345** [comment]
@extrenebiibues In the EU
