### ISSUE TITLE
offsets?

### ISSUE THREAD

**Issue by extrenebiibues** [iseekwonderful/csgoGlow#83]
i just got the offsets changed them on xcode and the glow still aint working?

**Comment by hitmyquatch** [comment]
Yes for me too, I entered the offsets
uint64_t glowInfoOffset = 595b3a0;
uint64_t LocalPlayerBase = 514bad8;
uint64_t playerBase = 50c8658;
yet it still doesnt work

**Comment by sacredgeo** [comment]
Those are also the new offsets I've found with the pattern scanner. Sometimes it will give a glow to one of my team mates, and I can see only that person through the walls. The hack will still work, but I believe the offsets are changed. From the youtube tutorials, I've followed the instructions exactly to find the local player offset, but it's just not working. It's supposed to be 0x12C away from your health, but I think that may have changed. I'm no expert though.

**Comment by hitmyquatch** [comment]
I updated it to these,
uint64_t glowInfoOffset = 0x595B3A0;
uint64_t LocalPlayerBase = 0x514BAD8;
uint64_t playerBase = 0x50C8658;
building it is just fine, but i think that someone will have to manually find each offset

**Comment by sacredgeo** [comment]
Unless I misunderstood the video, the location of the player offset was 0x12C away, but I found it at 0x134. I'm still working on getting it working. Making progress...

**Comment by hitmyquatch** [comment]
you're a real hero thank you for your service

**Comment by sacredgeo** [comment]
The weird part is, I still got the same offset: 

Player Health - 0x134 -> base("/client.dylib") + 0x514BAD8

So now I have no idea what to do.

Edit: I'm using bit slicer, like he instructs in the youtube video. The entity list offset also still appears to be 0x50C8658.

**Comment by sacredgeo** [comment]
Manually found the glow offset as well. It's 0x595B3A0. So it seems the pattern scanner was right.

**Comment by aKalisch** [comment]
Fixed in PR #86

**Comment by extrenebiibues** [comment]
@aKalisch yo i was a fan of ur cheats what happend to them? did u privatise them? nevertheless thank you for ur help i hope u find 50 euros on the pavement and find a puppy u really like
