### ISSUE TITLE
Problem with New Update.

### ISSUE THREAD

**Issue by sulik12345** [iseekwonderful/csgoGlow#84]

**Comment by sulik12345** [comment]
When trying to build with the new update, I get an issue saying 
"Unknown type name 'LocalPlayer' and also another one.

**Comment by DooubleO** [comment]
@gabsens Help us all out

**Comment by ggothreau** [comment]
The most recent update is not valid C++ code.

`+LocalPlayer: 514bad8
+EntityList : 50c8658
+Glow: 595b3a0`

It should be:

`uint64_t glowInfoOffset = 0x595b3a0;
uint64_t LocalPlayerBase = 0x514bad8;
uint64_t playerBase = 0x50c8658;`

But those offsets don't seem to work to me, I suspect the health / teamnum / etc variable offsets have changed. Can't figure out what they are right now.

**Comment by aKalisch** [comment]
The Offsets work correctly.

int m_iGlowIndex = 0xA2E0; <<< This is wrong. Add 0xC to it.

int m_iGlowIndex = 0xAC10; <<< This is my Offset that works correctly.

**Comment by extrenebiibues** [comment]
@aKalisch dude im trying that but the build still fails? Im new to c++ can u tell me what to do?

**Comment by extrenebiibues** [comment]
@aKalisch https://gyazo.com/1092679159615f902d7be5755d069fd6 this is what it looks like

**Comment by aKalisch** [comment]
So u've commited something without knowing what you are doing?

**Comment by extrenebiibues** [comment]
@aKalisch lol i did it by accident im only now learning how to use github

**Comment by extrenebiibues** [comment]
@aKalisch well im learning i doubt u coded 30 websites every day when u first started

**Comment by aKalisch** [comment]
Created a pull request. Please be patient until it's approved.
Then glow should work.

PR is #86

**Comment by sulik12345** [comment]
@aKalisch this happens...

Found CSGO PID: 954
Process reallocation: 954 -> 0 [5 - (os/kern) failure]
Failed to get get info.
Failed to get the Client.dylib address

**Comment by sulik12345** [comment]
with all your changes

**Comment by aKalisch** [comment]
I've tested it and it works.

You've made something wrong.

Post the code that you've changed.

**Comment by sulik12345** [comment]
http://pastebin.com/0ShYT1WN

**Comment by aKalisch** [comment]
It works ;-)

**Comment by ggothreau** [comment]
@sulik12345 is probably not running as root. There are instructions in other issues, search previous issues.

**Comment by extrenebiibues** [comment]
@ggothreau do u play mm? if u do wanna play? xD

**Comment by sacredgeo** [comment]
@aKalisch Can you tell me more about m_iGlowIndex? I was able to find the other offsets with bitslicer. How do you find that one? Thanks!

**Comment by aKalisch** [comment]
I've researched it one by one (+ 0x4) until my glow was working.

I'd know that some netvars (offsets) changed during the Update. So I've did it this way.

https://www.youtube.com/watch?v=3HhD7WNzSno watch this video how to find the glow offset ;-)

**Comment by sacredgeo** [comment]
@aKalisch I have watched all the youtube videos. They're great. Using that video I found the glow offset 0x595b3a0. It's actually really fun playing with bit slicer to find these values. But I still don't understand how you get m_iGlowIndex = 0xAC10. I see you just added 4 bytes at a time, but how do you know where to start?

**Comment by aKalisch** [comment]
https://github.com/iseekwonderful/csgoGlow/pull/86/files

Look the changed parts in my PR. There you see the old GlowIndexOffset (m_iGlowIndex). I've took this to get it.
If you want to go deeper into memory reading and manipulating memory you should have a look at Hopper. That's a great tool to get Offsets for almost everything.

Also searching for byte arrays could give you some great Offsets :-)

**Comment by gabsens** [comment]
@aKalisch you got a license for the latest version of Hopper ?

**Comment by aKalisch** [comment]
Not the latest. Using 3.9.15 ;-)

**Comment by sacredgeo** [comment]
@aKalisch Thank you :]

**Comment by gabsens** [comment]
@aKalisch with the shitty debugger then

**Comment by aKalisch** [comment]
@gabsens could be :-P I don't use it because just read the dylib ;-)

**Comment by gabsens** [comment]
@aKalisch off-topic, but be mindful of script kiddies like [him](https://www.youtube.com/watch?v=i-GuxLkRKk4) who's seeking easy profit from open-source OSX cheats (which is why I haven't released anything publicly)

**Comment by aKalisch** [comment]
Yes sure. That's why I've took my hack offline.
When releasing a public one without any warranty ... If they want to steal it, they should. Also if there will be any changes to VAC they get busted until I've got a running hack without been busted by VAC ;-)
