### ISSUE TITLE
Not Working 9/17

### ISSUE THREAD

**Issue by iPredictable** [iseekwonderful/csgoGlow#85]
When the new update came out, I thought the csgoglow would be updated and downloaded it it, but when I tried to install/build it, this happened. Any help?
<img width="1116" alt="screen shot 2016-09-17 at 1 48 43 pm" src="https://cloud.githubusercontent.com/assets/22254866/18607492/ee2acab0-7cde-11e6-9d9a-50552d527acf.png">

**Comment by aKalisch** [comment]
Fixed in PR #86
