### ISSUE TITLE
Source Code For Bhop Scripts

### ISSUE THREAD

**Issue by iPredictable** [iseekwonderful/csgoGlow#88]
Feeling Nice Today, Feel Free To Steal It.
https://gyazo.com/036df30296110c0240a3acf087b7142e

**Comment by aKalisch** [comment]
Sorry this one would never work ;-)

It's for Windows.
Also you need to obtain the Offsets for dwForceJump.

In my opinion the dwForceJump is not that good because it triggers to slow.
I've did it by sending a keypress on space when my player hits the ground. Working more nicely ;-)

**Comment by sulik12345** [comment]
@aKalisch could you send me it please :P

**Comment by aKalisch** [comment]
You already got it ;-) (In my hack, you know?)

**Comment by extrenebiibues** [comment]
@aKalisch the one ur making or the old one? cuz u removed one

**Comment by iPredictable** [comment]
@aKalisch is your bhop script public or private?

**Comment by MyNameIsLebronJames** [comment]
@sulik12345 you have Skype add me?
