### ISSUE TITLE
Pull-Requests and approvement

### ISSUE THREAD

**Issue by aKalisch** [iseekwonderful/csgoGlow#89]
As of today there happens a big mistake and a PR was merged without notice that it holds a bug where you not even can compile.

Would be great to approve that the PR is working correctly before merging.

**Comment by gabsens** [comment]
Would be great if kids with 0 knowledge of programming precluded themselves from suggesting retarded commits that result in tens of other kids asking why the code is not compiling. 

@extrenebiibues
