### ISSUE TITLE
Build not successful 

### ISSUE THREAD

**Issue by GreyWolf25** [iseekwonderful/csgoGlow#91]
I am trying to compile the exec but does seem to work because there is this error with the:

int m_iGlowIndex = 0xAC10;

And the error is "Unknown type name 'LocalPlayer'"
And the error is "Expected unqualified-id

Can anyone help me get this thing to work cheers

Here's Picture of code don't know if it will work.
<img width="846" alt="screen shot 2016-09-18 at 7 42 37 am" src="https://cloud.githubusercontent.com/assets/22263269/18610548/8324fc0a-7d73-11e6-842d-1ba9da2aacb2.png">

**Comment by aKalisch** [comment]
Fixed in PR #92
