### ISSUE TITLE
How to change colour?

### ISSUE THREAD

**Issue by extrenebiibues** [iseekwonderful/csgoGlow#93]
how do i change the base colour before amber orange and bright red? Im only asking so i can get to understand this whole coding thing since im learning to realise from watching gabsens videos u can do a lot more with xCode than i thought

**Comment by aKalisch** [comment]
Line 411: `Color color = {float((100 - health) / 100.0), float((health) / 100.0), 0.0f, 0.8f};`

Google for Colorpicker in Google.
Pick the color you want and have a look at R, G, B.

Make a new color struct: `Color color {(<R value> / 255), (<G value> / 255), (<B value> / 255)};`
So for Color Pink: `Color color {(255 / 255), (0 / 255), (255 / 255)};`

**Comment by extrenebiibues** [comment]
@aKalisch hmm i tried it but either there is an error, the glow doesnt work at all, or nothing happens can u send me an ss of an example it doesnt have to be pink it can be blue or something just so i can have an idea of what to mess with

**Comment by aKalisch** [comment]
Oh yes sure. Missed the alpha value.

The code should be: 
`float alpha = 80.0f; // percentage of glow effect`
`Color color {(<R value> / 255), (<G value> / 255), (<B value> / 255), (alpha / 100)};`

**Comment by extrenebiibues** [comment]
@aKalisch https://gyazo.com/1e5384ee9b1012a39e59931c4d78169c
I dont know whats wrong with it the code, the glow just doesnt come up at all the original source code is
       Color color = {float((100 - health) / 100.0), float((health) / 100.0), 0.0f, 0.8f};

**Comment by aKalisch** [comment]
In you screen the variable is not used.

Correct that and it should work.
Did this in my hack to and works like a charm.

**Comment by extrenebiibues** [comment]
@aKalisch i did and the glow wont show up

**Comment by extrenebiibues** [comment]
@aKalisch i did it omg took me a week but hells yea im lurning!!11!111!
