### ISSUE TITLE
Other OSX Hacks

### ISSUE THREAD

**Issue by iPredictable** [iseekwonderful/csgoGlow#94]
I know I shouldn't be asking this here, but everywhere else nobody understands that hacks can be coded in osx, I was just wondering if anyone has other hacks that they either want to share or sell, Im interested , Thanks.

**Comment by extrenebiibues** [comment]
just make one  dude its so much more satisfying and safer.

**Comment by iPredictable** [comment]
@extrenebiibues I would but I dont know how ;/

**Comment by extrenebiibues** [comment]
@PredictEr if u find some tell me we need an aimbot that slows down your dpi / sensitivity when hovering an enemy or something like that

**Comment by aKalisch** [comment]
@extrenebiibues why you want to do that?
Just make smooth aim and you are fine.

**Comment by iPredictable** [comment]
@aKalisch do you have a smooth aim hack?

**Comment by aKalisch** [comment]
Yeah. But it's not public. Today i had Stats 46 2 3 on public MM :-D working so freaking good if I want :-)

**Comment by iPredictable** [comment]
@aKalisch do you sell anything privately?

**Comment by aKalisch** [comment]
@PredictEr at the moment I'll not share my hack as it's still in development.

**Comment by iPredictable** [comment]
@aKalisch aww rip. you planning to in the future?

**Comment by extrenebiibues** [comment]
@aKalisch will ur hack have smooth aim? If u can make on thats not obvious it would be greatly appreciated

**Comment by DooubleO** [comment]
@aKalisch You had your multihack up for a while that had bhop, trigger and walls. By any chance could I get the bhop seperate?

**Comment by extrenebiibues** [comment]
@DooubleO its source mod detected just wait for his next multihack

**Comment by aKalisch** [comment]
@extrenebiibues No it's not ;-) it could be detected because it's "perfect" ... that means it made every hop perfect.

**Comment by extrenebiibues** [comment]
@aKalisch Can you release a smooth aim separate? I would literally be contempt with that and i could try go through it and make a rage one? I need mac source codes so i can learn c++. Also an aimbot would be so cool

**Comment by aKalisch** [comment]
Ok Guys. As some of u requesting my stuff I will shortly release some public sources.

But. These are just sources. No Offsets, no implementation, no support.
You need to get it yourself into your hack base.

@EDIT:
Here we go.
https://github.com/aKalisch/source-bunnyhop/

Have Fun ;-)

ps: more to come soon

**Comment by sulik12345** [comment]
@aKalisch what do i do with this lmao xD

**Comment by loco41211** [comment]
@sulik12345 if you don't know what to do with these, then you're not ready or they aren't for you:

> But. These are just sources. No Offsets, no implementation, no support.
> You need to get it yourself into your hack base.

**Comment by iPredictable** [comment]
@aKalisch Cheers for the hack but could you just like teach us kinda how to use it, not like a video just a brief idea. Thanks again, if you would share any more everyone in the community would love it <3

**Comment by BlackCrab** [comment]
@aKalisch How do you use it though? Sorry Im a complete noob, but I don't really know.

**Comment by xxShrekxx** [comment]
@aKalisch Your multihack coming back?

**Comment by DooubleO** [comment]
Guys, legit look at what he said. 
"if you don't know what to do with these, then you're not ready or they aren't for you"
If you don't know how to use them, then learn to. If you cant take the time too then you shouldn't be using it.

**Comment by aKalisch** [comment]
@DooubleO thx. Could not say it in better words.

Please feel free this source.
As I said, I don't will give support for it.

YOU need to implement it on ur OWN!

**Comment by xxShrekxx** [comment]
@DooubleO @aKalisch But we just want a brief explanation or just where do we learn this? Why can't you just take 5 minutes out of your lives to help out people.

**Comment by aKalisch** [comment]
@xxShrekxx goto www.unknowncheats.me and learn this stuff.
I for myself didn't even need to learn as I'm a senior PHP Developer. And the structure is almost the same as CPP. So you need to understand the structure of the code and then it should be easy to implement this code.

If you have no knowledge about cpp you should ignore my source and just use hacks that are done.

**Comment by xxShrekxx** [comment]
@aKalisch I have no knowledge, but there are no other hacks that are "done" for osx. I've used the csgoglow, so I know how it is. Can you just please please please tell me an idea to what Im supposed to do with your source, so I can research it and learn.

**Comment by DooubleO** [comment]
What said is said.
If you don't know what to do with it then you shouldn't use it. 
Put in the time, put in the effort. Then you will be rewarded.

**Comment by aKalisch** [comment]
@xxShrekxx put this in a into your code, and call it in the `while(true)` loop. Then get the offset `m_iFlags` offset (now it's 0x138). You also may need to initialize the Bunnyhop class.
Whenever you press and hold space and you hit the ground you should jump. Also note the comments in this source.

And what you've learned now? Exactly nothing I think.

**Comment by xxShrekxx** [comment]
@DooubleO Thanks for being a complete asshole to the community. You can't even help someone get started, we want to put in the effort. But if you'd tell us where to start. Not just unkowncheats then maybe we could. Im sure someone helped you out when you started, but you have to be an asshole.

**Comment by xxShrekxx** [comment]
@aKalisch Thank you so much.

**Comment by xxShrekxx** [comment]
@aKalisch So I put I implement this in main right?

**Comment by aKalisch** [comment]
@xxShrekxx please learn C++ before ask more questions. I think I will close this here as this is now Support board. Visit www.unknowncheats.me if you need more help.

**Comment by xxShrekxx** [comment]
@aKalisch is this a good place to start http://www.unknowncheats.me/forum/counterstrike-global-offensive/129168-making-hacks-c.html

**Comment by aKalisch** [comment]
@xxShrekxx yes ... but u need to translate it to Mac OS X as this is a Tutorial for Windows.
But you have all in this repository here.

**Comment by xxShrekxx** [comment]
@aKalisch is there a specific term for the Mac OS X language? Like, whats the difference

**Comment by xxShrekxx** [comment]
@aKalisch how about this guys series? https://www.youtube.com/watch?v=XgV76LapvGs

**Comment by aKalisch** [comment]
@xxShrekxx The language is the same. But the functions and class methods are different. So you need to find the equivalents for OS X and translate the shown code.

When you notice my hint you can take all thing from this repository.

**Comment by gabsens** [comment]
![spoonfeeding-teachers-021](https://cloud.githubusercontent.com/assets/17448712/19019847/6552abaa-8895-11e6-9bbf-e599d0c07d75.png)
