### ISSUE TITLE
currently not working 

### ISSUE THREAD

**Issue by oscargriffin** [iseekwonderful/csgoGlow#96]
Found CSGO PID: 809
Process reallocation: 809 -> 1603 [0 - (os/kern) successful]
CSGO Memory 4426080256 
Version: 14, 292 images at offset 0x101800000
Found the Client.dylib address: 0x134800000 
Module should end at 0x13991e000
this is the lines i get after doing sudo -s and typing password in

**Comment by macosxuser** [comment]
can confirm, the esp glow broke with new update

**Comment by hitmyquatch** [comment]
It does work, make sure you replace the code 
uint64_t glowInfoOffset = 0x595c4a0;
uint64_t LocalPlayerBase = 0x514cbd8;
uint64_t playerBase = 0x50c9748;
and build it again

**Comment by rissc** [comment]
Offset for Localplayer is wrong.

Correct Offsets are:
m_dwLocalPlayer: 0x50B2EB8;
m_dwEntityList: 0x50C9748;
m_dwGlowInfo: 0x595C4A0;

**Comment by aKalisch** [comment]
Offset for Localplayer is wrong.

Correct Offsets are:
m_dwLocalPlayer: 0x50B2EB8;
m_dwEntityList: 0x50C9748;
m_dwGlowInfo: 0x595C4A0;

Corrected in PR #92

**Comment by rawrchad** [comment]
I had posted a merge for the offsets idk if it was uploaded or not though. These comments have the right offsets though.

**Comment by MyNameIsLebronJames** [comment]
Basically, this is undetected correct? since its like running chrome in the background, valve can't detect it.

**Comment by oscargriffin** [comment]
cheers lads my bad but cheers for the help

**Comment by aKalisch** [comment]
Fixed @commit 20379c351cd7e4174c2d55d159d41716d970bb85
