### ISSUE TITLE
Guys how do i make it toggle-able 

### ISSUE THREAD

**Issue by extrenebiibues** [iseekwonderful/csgoGlow#97]
i want it to toggle whenever i click CMD

**Comment by aKalisch** [comment]
You can toggle with the "V" key.

**Comment by extrenebiibues** [comment]
@aKalisch just V? I dont think u can i have tried it

**Comment by iPredictable** [comment]
@aKalisch V doesnt work,

**Comment by deezysleazy** [comment]
anyone figure it out?

**Comment by aKalisch** [comment]
Will fix this soon. The key is now `CMD` + `ALT` + `SHIFT` + `\`

Will change it to `CTRL`\+ `ALT` + `V`

**Comment by aKalisch** [comment]
Now fixed @commit 2cc35d6
