### ISSUE TITLE
Starting To Code

### ISSUE THREAD

**Issue by iPredictable** [iseekwonderful/csgoGlow#98]
Hi guys, I've never known how to code but I want to learn how to, especially for hacks for mac and windows. Anyone has an idea on how to start and where to learn things?

**Comment by aKalisch** [comment]
go to www.unknowncheats.me and look through the board. You will find good source code and tutorials as you need them.

**Comment by extrenebiibues** [comment]
@aKalisch speaking of coding how do i make a toggle button?

**Comment by iPredictable** [comment]
@aKalisch yeah but for mac osx

**Comment by extrenebiibues** [comment]
@PredictEr he means learning the language, idk why but he needs to be more reciprocal cuz right now he needs to think about c++ as a language and not some game
